### ISSUE TITLE
[create-theme]: Yasb 001

### ISSUE THREAD

**Issue by amnweb** [amnweb/yasb-themes#16]
### Name

Yasb 001

### Description

Simple yasb theme

### Homepage

https://github.com/amnweb/yasb

### Image

https://i.imgur.com/nH33oPf.png

### Theme Styles

```css
* {
	font-size: 12px;
	color: #bec8e7;
	font-weight: 500;
	font-family: "JetBrainsMono NFP";
	margin: 0;
	padding: 0;
}
.yasb-bar {
	padding: 0;
	margin: 0;
    background-color: rgb(30, 30, 46);
}
.widget {
	padding: 0 8px;
	margin: 0 4px;
}
.widget .label {
	padding: 0px 2px; 
}
.widget .label.alt {
	padding: 0px 8px;
}
.active-window-widget {
	border-radius: 18px;
	margin-left: 8px;
}
.komorebi-workspaces .ws-btn {
	font-size: 14px;
    border: none;
    color: #6c7086;
	margin: 0 1px 0 1px;
    height: 30px;
    padding: 0 12px;
    border-bottom: 1px solid #6c7086;
}
.komorebi-workspaces .ws-btn:hover {
    color: #7f849c;
    border-bottom: 1px solid #7f849c;
}
.komorebi-workspaces .ws-btn.populated {
	color: #b4befe;
}
.komorebi-workspaces .ws-btn.active {
    color: #94e2d5;
    font-weight: 900;
    width: 30px;
    border-bottom-color: #94e2d5;
}
.uptime {
	font-size: 14px;
	margin-bottom: 10px;
	color: rgba(191, 202, 219, 0.726);
	font-weight: 600;
	font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
}
.power-menu-widget .label {
	color: #f38ba8;
	font-size: 13px;
}
.power-menu-popup {
	background-color: rgba(24, 24, 37, 0.9);
	border-radius: 12px;
	border: 4px solid rgb(41, 42, 58);
}
.power-menu-popup .button {
	padding: 0;
	width: 240px;
	height: 120px;
	border-radius: 8px;
	background-color: rgb(41, 42, 58);
	font-family: "SegoeUI";
	color: white;
	border: 1px solid rgba(255, 255, 255, 0.1);
	margin: 8px;
}
.power-menu-popup .button.hover {
	background-color: rgb(55, 56, 75);
	border: 1px solid rgb(55, 56, 75);
}
.power-menu-popup .button .label {
	margin-bottom: 8px;
	font-size: 16px;
	font-weight: 600;
	color: rgba(255, 255, 255, 0.95);
	font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
}
.power-menu-popup .button .icon {
	font-size: 48px;
	padding-top: 8px;
	color: rgba(255, 255, 255, 0.25);
}
.power-menu-popup .button.cancel .icon {
	color: rgba(243, 139, 168, 0.55);
}
.power-menu-popup .button.cancel .label {
	color: rgba(243, 139, 168, 0.95);
}
.power-menu-popup .button.shutdown .icon {
	color: rgba(137, 180, 250, 0.55);
}
.power-menu-popup .button.shutdown .label {
	color: rgba(137, 180, 250, 0.95);
}

/* ICONS */
.icon {
	font-size: 16px;
    margin-right:4px;
}
.cpu-widget .icon,
.memory-widget .icon {
	font-size: 14px;
	color: #cba6f7;
} 
.weather-widget{
    border-bottom: 1px solid #eba0ac;
    background-color: rgba(235, 160, 173, 0);
}
.weather-widget .label,
.weather-widget .icon {
    color: #eba0ac;
}
.weather-widget .icon {
	font-size: 16px;
}
.weather-widget .icon.clearNight {
	font-size: 16px;
}
.weather-widget .icon.cloudyNight {
    font-size: 18px;
} 
.memory-widget {
    border-bottom: 1px solid #cba6f7;
    background-color: rgba(203, 166, 247, 0);
}
.memory-widget .label {
    color: #cba6f7;
}
.volume-widget {
    border-bottom: 1px solid #89b4fa;
    background-color: rgba(137, 180, 250, 0);
}
.volume-widget .icon {
	color: #89b4fa;
}
.volume-widget .label {
	color: #89b4fa;
}
.taskbar-widget .app-icon{
    padding:0 6px;
    border: none;
    margin: 0;
}
.power-menu-widget {
    border-bottom: 1px solid #f38ba8;
    background-color: rgba(243, 139, 168, 0);
}
.clock-widget {
    border-bottom: 1px solid #bec8e7;
    background-color: rgba(190, 200, 231, 0);
}
/* NEW MEDIA WIDGET */
.media-widget {
	padding: 0;
	margin: 0;
    border-radius: 0;
}
.media-widget .label {
	color: #bac2db;
	padding: 0 4px;
	font-size: 11px;
}
.media-widget .btn {
	color: #acb2c9;
	padding: 0 3px;
	margin: 4px 0;
	font-family: Segoe Fluent Icons;
}
.media-widget .btn:hover {
	color: #babfd3;
}
.media-widget .btn.play {
	background-color: #313244;
	font-size: 16px;
}
.media-widget .btn.disabled:hover,
.media-widget .btn.disabled {
	color: #4e525c;
	font-size: 12px;
	background-color: rgba(0, 0, 0, 0);
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false # Blur effect will be applied to the bar
      acrylic: false # Acrylic effect will be applied to the bar
      dark_mode: false # Dark mode will also add more shadow to the bar
      round_corners: false # Default radius from OS
      border_color: None # If is None border will be removed, System will use OS accent color, otherwise you can set your own HEX color (this option is related to round_corners=true) 
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
          "active_window"
      ]
      center: [
        "komorebi_workspaces"
        ]
      right: [
          "media",
          "memory",
          "weather",
          "volume",
          "power_menu",
          "clock"
      ]
widgets:
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{artist}"
      max_field_size:
        label: 30
        label_alt: 24
      show_thumbnail: false
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 250
      thumbnail_padding: 0
      thumbnail_corner_radius: 0
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uf4bc</span> {virtual_mem_outof}"
      label_alt: "<span>\uf4bc</span> {virtual_mem_outof}"
      update_interval: 10000
      callbacks:
        on_right: "exec cmd /c Taskmgr"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\udb80\udd50</span> {%a, %d %b %H:%M}"
      label_alt: "<span>\udb80\udd50</span> {%A, %d %B %Y %H:%M}"
      timezones: []
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "Komorebi Offline"
        label_workspace_btn: "{index}"
        label_workspace_active_btn: "{index}"
        label_workspace_populated_btn: "{index}"
        label_default_name: "{index}"
        label_zero_index: false
        hide_empty_workspaces: false
        hide_if_offline: false
        animation: true
        container_padding:
          top: 0
          left: 8
          bottom: 0
          right: 8
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts: ['bsp', 'columns', 'rows', 'grid', 'vertical_stack', 'horizontal_stack', 'ultrawide_vertical_stack','right_main_vertical_stack']
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        vertical_stack: "V-STACK"
        horizontal_stack: "H-STACK"
        ultrawide_vertical_stack: "W-STACK"
        right_main_vertical_stack: "RMV-STACK"
        monocle: "MONOCLE"
        maximised: "MAX"
        floating: "FLOATING"
        paused: "PAUSED"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      callbacks:
        on_left: 'next_layout'
        on_middle: 'toggle_monocle'
        on_right: 'prev_layout'
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp_c}"
      label_alt: "{location}: Min {min_temp_c}, Max {max_temp_c}, Humidity {humidity}"
      api_key: '24b6c2cda6d84066b0304531241908'
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: 'London' # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: "toggle_label"
      icons: 
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd94"
        cloudyDay: "\uebaa"
        cloudyNight: "\uebaa"
        rainyDay: "\udb81\udd96"
        rainyNight: "\udb81\udd96"
        snowyIcyDay: "\udb81\udd92"
        snowyIcyNight: "\udb81\udd92"
        blizzard: "\udb81\udd93"
        default: "\uebaa"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound" 
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 250 # Milisecond 
      button_row: 3 # Number of buttons in row, min 1 max 5
      buttons:
        lock: ["\uea75","Lock"]
        signout: ["\udb80\udf43","Sign out"]
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        hibernate: ["\uf28e","Hibernate"]
        cancel: ["\udb81\udf3a","Cancel"]
```

### Readme

```markdown
## Yasb 001 Theme

![Windows 11 Theme](https://i.imgur.com/JkXTTI3.png)
```
