### ISSUE TITLE
[create-theme]: Yasb 002 Dynamic

### ISSUE THREAD

**Issue by amnweb** [amnweb/yasb-themes#21]
### Name

Yasb 002 Dynamic

### Description

Yasb 002 Dynamic is a theme which follows your OS style.

### Homepage

https://github.com/amnweb/yasb

### Image

https://i.imgur.com/kEaFjkI.png

### Theme Styles

```css
* {
	font-size: 12px;
	font-weight: 600;
	font-family: "JetBrainsMono NFP";
	margin: 0;
	padding: 0;
    color: #a6abcc;
}
.yasb-bar {
	padding: 0;
	margin: 0;
} 
.widget {
	background-color: #24273a;
	padding: 0 4px;
	margin: 0 4px;
    border-radius: 12px;
}
.dark .widget {
	background-color: #cad3f5;
}
.widget .label {
	padding: 0px 2px; 
}
.widget .label.alt {
	padding: 0px 8px;
}
.icon {
	font-size: 16px;
}
.komorebi-workspaces {
    margin: 0;
    padding: 0;
}
.komorebi-workspaces .offline-status {
    color: #627199;
    font-size: 12px;
    padding: 0 4px;
    font-weight:600;
}
.komorebi-workspaces .ws-btn {
    border: none;
    background-color: #b8c0e0;
	margin:0 2px;
    font-size: 12px;
	color:  #3a3e4d;
    width: 20px;
    height: 20px;
    border-radius: 10px;
}
.komorebi-workspaces .ws-btn:hover {
    background-color: #a5adcb;
}
.komorebi-workspaces .ws-btn.populated {
    background-color: #a5adcb;
}
.komorebi-workspaces .ws-btn.active {
	color: #181926;
    background-color:#8087a2;
    width:48px;
}
.apps-widget,
.dark .apps-widget {
	padding: 0;
    background-color: transparent;
}
.apps-widget .label {
	font-size: 15px;
	padding: 0 2px;
    color: #cad3f5;
}
.apps-widget .label:hover {
	color: #a5b8e9;
}
.uptime {
	font-size: 14px;
	margin-bottom: 10px;
	color: rgba(191, 202, 219, 0.726);
	font-weight: 600;
}
.power-menu-widget,
.dark .power-menu-widget {
    background-color: transparent;
}
.power-menu-widget .label {
	font-size: 13px;
}
.power-menu-popup {
	background-color: rgba(24, 24, 37, 0);
	border-radius: 12px; 
}
.power-menu-popup .button {
	padding: 0;
	width: 180px;
	height: 230px;
	border-radius: 8px;
	background-color: rgba(41, 42, 58, 0.5);
	color: white;
	border-left: 4px solid rgba(58, 59, 83, 0);
    border-right: 4px solid rgba(58, 59, 83, 0);
    border-top: 8px solid rgba(58, 59, 83, 0);
    border-bottom: 8px solid rgba(58, 59, 83, 0);
	margin: 0px;
}
.power-menu-popup .button.hover {
	background-color: rgb(41, 42, 58);
	border-left: 4px solid rgb(41, 42, 58);
    border-right: 4px solid rgb(41, 42, 58);
    border-top: 8px solid rgb(41, 42, 58);
    border-bottom: 8px solid rgb(41, 42, 58);
}
.power-menu-popup .button .label {
	margin-bottom: 8px;
	font-size: 16px;
	font-weight: 500;
	color: rgba(255, 255, 255, 0.5);
 
}
.power-menu-popup .button .icon {
	font-size: 64px;
	padding-top: 32px;
	color: rgba(255, 255, 255, 0.25);
}
.power-menu-popup .button.cancel .icon {
    padding: 0;
    margin: 0;
}
.power-menu-popup .button.cancel .label {
	color: rgba(243, 139, 168, 0.95);
    margin: 0;
}
.power-menu-popup .button.cancel {
    height: 32px;
    border-radius: 4px;
}
.volume-widget .icon {
	margin: 1px 2px 0 0;
}
.wifi-widget .icon {
	padding: 0 6px;
	margin: 0;
}
.weather-widget,
.volume-widget {
    padding:0 6px;
}
.weather-widget .icon {
	font-size: 16px;
	margin: 0 2px 0px 0;
}
.custom-menu-widget {
	padding: 0 8px 0 8px;
	border-radius: 12px;
}
.custom-menu-widget .label {
    font-weight: bold;
}
.taskbar-widget,
.dark .taskbar-widget {
    padding: 0;
    margin: 0;
    border: none;
    background-color: transparent;
}
.taskbar-widget .app-icon{
    padding:0 6px;
    border: none;
    margin: 0;
}
.whkd-widget,
*.dark .whkd-widget {
    background-color: transparent;
    padding: 0 6px 0 6px;
}
.whkd-widget .icon {
    font-size: 15px;
}
.label,
.icon {
	color: #cad3f5
}
*.dark .label,
*.dark .icon {
	color: #292c3c
}
.apps-widget .label,
.power-menu-widget .label,
.whkd-widget .icon {
    color: #292c3c;
}
*.dark .apps-widget .label,
*.dark .power-menu-widget .label,
*.dark .whkd-widget .icon {
    color: #cad3f5;
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["*"] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false 
      border_color: None 
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 24
    padding:
      top: 4
      left: 4
      bottom: 0
      right: 4
    widgets:
      left:
        ["win","apps","active_window"]
      center: ["komorebi_workspaces"]
      right: ["weather","whkd","taskbar","volume","power_menu","clock"]
widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 36
      max_length_ellipsis: "..."
      monitor_exclusive: true
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M %a}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      timezones: []
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "\u26a1 Offline"
        label_workspace_btn: "{index}"
        label_workspace_active_btn: "{index}"
        label_workspace_populated_btn: "{index}"
        label_default_name: "{index}"
        label_zero_index: false
        hide_empty_workspaces: false
        hide_if_offline: false
        animation: true
        container_padding:
          top: 0
          left: 1
          bottom: 0
          right: 1
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp_c}"
      label_alt: "{location}: Min {min_temp_c}, Max {max_temp_c}, Humidity {humidity}"
      api_key: '3bf4cf9a7c3f40d6b31174128242807'
      update_interval: 1200 # Seconds
      hide_decimal: true
      location: "USA Los Angeles 90006"
      callbacks:
        on_left: "toggle_label"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        signout: ["\udb80\udf43","Sign out"]
        hibernate: ["\uf28e","Hibernate"]
        sleep: ["\u23fe","Sleep"]
        cancel: ["","Cancel"]
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label: "{data}"
      app_list:
        - {icon: "\ueb51", launch: "quick_settings"}
        - {icon: "\uf422", launch: "search"}
        - {icon: "\ueb03", launch: "cmd /c Taskmgr"}
        - {icon: "\uf489", launch: "wt"}
        - {icon: "\uf1ff", launch: "C:\\Users\\amn\\AppData\\Local\\Discord\\Update.exe --processStart Discord.exe"}
        - {icon: "\udb80\ude39", launch: "C:\\Program Files\\Mozilla Firefox\\firefox.exe"}
  whkd:
    type: "yasb.whkd.WhkdWidget"
    options:
      label: "<span>\uf11c</span>"
  win:
    type: "yasb.custom.CustomWidget"
    options:
      label: "Menu"
      label_alt: "Menu"
      class_name: "custom-menu-widget"
      callbacks:
        on_left: "exec start_menu"
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation: true
      icon_size: 16
      ignore_apps:
        processes: []
        titles: []
        classes: []
```

### Readme

```markdown
# Yasb 002 Dynamic

![Project Logo](https://i.imgur.com/kEaFjkI.png)

## Description

Yasb 002 Dynamic is a theme which follows your OS style.

![Theme Preview](https://i.imgur.com/zxt9cSo.gif)
```
