### ISSUE TITLE
[create-theme]: Yasb 003

### ISSUE THREAD

**Issue by amnweb** [amnweb/yasb-themes#23]
### Name

Yasb 003

### Description

Yasb 003 is the theme posted on the Komorebi repository README page.

### Homepage

https://github.com/amnweb/yasb

### Image

https://i.imgur.com/3c1EBTh.png

### Theme Styles

```css
* {
    font-size: 12px;
    color: #e0e3ee;
    font-weight: 600;
    font-family: "Segoe UI", "JetBrainsMono NFP";
    margin: 0;
    padding: 0;
}
.yasb-bar {
    padding: 0 8px;
    margin: 0;
    background-color: rgba(14, 18, 26, 0.712);
    border-radius: 8px;
    border: 1px solid rgb(45, 54, 68);
}
.widget {
    padding: 0 8px;
    margin: 0;
}
.widget .label {
    padding: 0px 2px 1px 0;
}
.widget .label.alt {
    padding: 0px 8px;
}
.komorebi-workspaces .widget-container {
    margin-left: 0px;
}
.komorebi-workspaces .widget-container {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
    border-left: none
}
.komorebi-workspaces .offline-status {
    color: #627199;
    font-size: 12px;
    padding: 0 4px;
    font-weight: 600;
}
.komorebi-workspaces .ws-btn {
    border: none;
    background-color: rgb(83, 86, 99);
    margin: 0 3px;
    width: 10px;
    height: 10px;
    border-radius: 5px;
    color: rgba(0, 0, 0, 0);
}
.komorebi-workspaces .ws-btn:hover {
    color: rgba(0, 0, 0, 0);
    background-color: rgb(139, 143, 156);
}
.komorebi-workspaces .ws-btn.populated {
    color: rgba(0, 0, 0, 0);
    background-color: rgb(139, 143, 156);
}

.komorebi-workspaces .ws-btn.active {
    color: rgba(0, 0, 0, 0);
    background-color: rgb(191, 195, 209);
    width: 36px;
    height: 10px;
}
.apps-widget .label {
    font-size: 12px;
    font-weight: 700;
}
.apps-widget .label:hover {
    color: #ffffff;
    background-color: rgba(191, 202, 219, 0.07);
}
.uptime {
    font-size: 14px;
    margin-bottom: 10px;
    color: rgba(191, 202, 219, 0.726);
    font-weight: 600;
}
.power-menu-widget .label {
    font-size: 13px;
}
.power-menu-popup {
    background-color: rgba(24, 24, 37, 0);
    border-radius: 12px;

}
.power-menu-popup .button {
    padding: 0;
    width: 180px;
    height: 230px;
    border-radius: 8px;
    background-color: rgba(41, 42, 58, 0.5);
    color: white;
    border-left: 4px solid rgba(58, 59, 83, 0);
    border-right: 4px solid rgba(58, 59, 83, 0);
    border-top: 8px solid rgba(58, 59, 83, 0);
    border-bottom: 8px solid rgba(58, 59, 83, 0);
    margin: 0px;
}
.power-menu-popup .button.hover {
    background-color: rgb(41, 42, 58);
    border-left: 4px solid rgb(41, 42, 58);
    border-right: 4px solid rgb(41, 42, 58);
    border-top: 8px solid rgb(41, 42, 58);
    border-bottom: 8px solid rgb(41, 42, 58);
}
.power-menu-popup .button .label {
    margin-bottom: 8px;
    font-size: 16px;
    font-weight: 500;
    color: rgba(255, 255, 255, 0.5);

}
.power-menu-popup .button .icon {
    font-size: 64px;
    padding-top: 32px;
    color: rgba(255, 255, 255, 0.25);
}
.power-menu-popup .button.cancel .icon {
    color: rgba(243, 139, 168, 0.3);
}
.power-menu-popup .button.cancel .label {
    color: rgba(243, 139, 168, 0.95);
}
.icon {
    font-size: 16px;
}
.weather-widget {
    padding: 0 6px;
}
.weather-widget .icon {
    font-size: 16px;
    margin: 0 2px 0px 0;
}
.weather-widget .icon.sunnyDay {
    color: rgb(221, 210, 107);
}
.weather-widget .icon.clearNight {
    color: rgb(107, 189, 221);
    font-size: 16px;
    margin: 0px 2px 1px 0;
}
.weather-widget .icon.cloudyNight {
    color: rgb(107, 189, 221);
    font-size: 18px;
    margin: 0px 2px 1px 0;
}
.weather-widget .icon.cloudyDay {
    color: rgb(129, 173, 248);
}
.traffic-widget .tr_sep {
    margin: 0 6px;
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 28
    padding:
      top: 3
      left: 6
      bottom: 0
      right: 6
    widgets:
      left:
        [ 
          "app_button",
          "apps",
          "komorebi_workspaces"
        ]
      center: []
      right:
        [
          "traffic",
          "weather",
          "clock",
          "power_menu"
        ]
widgets:
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      timezones: []
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "\u26a1 Offline"
        label_workspace_btn: "\udb81\udc3d"
        label_workspace_active_btn: ""
        label_workspace_populated_btn: "\udb81\udc3e"
        label_default_name: "{index}"
        label_zero_index: false
        hide_empty_workspaces: false
        hide_if_offline: false
        animation: true
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp_c}"
      label_alt: "{location}: Min {min_temp_c}, Max {max_temp_c}, Humidity {humidity}"
      api_key: '3bf4cf9a7c3f40d6b31174128242807'
      update_interval: 600
      hide_decimal: true
      location: 'London'
      callbacks:
        on_left: "toggle_label"
      icons: 
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd94"
        cloudyDay: "\uebaa"
        cloudyNight: "\uebaa"
        rainyDay: "\udb81\udd96"
        rainyNight: "\udb81\udd96"
        snowyIcyDay: "\udb81\udd92"
        snowyIcyNight: "\udb81\udd92"
        blizzard: "\udb81\udd93"
        default: "\uebaa"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200 # Milisecond 
      button_row: 3 # Number of buttons in row, min 1 max 5
      buttons:
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        signout: ["\udb80\udf43","Sign out"]
        hibernate: ["\uf28e","Hibernate"]
        sleep: ["\u23fe","Sleep"]
        cancel: ["\udb81\udf3a","Cancel"]
  traffic:
      type: "yasb.traffic.TrafficWidget"
      options:
        label: "<span>\udb86\uddb3</span>{download_speed}<span class=\"tr_sep\">\ue621</span><span>\udb86\uddb2</span>{upload_speed}"
        label_alt: "Download {download_speed} \ue621 Upload {upload_speed}"
        update_interval: 1000 # Update interval should be a multiple of 1000
        callbacks:
          on_left: "toggle_label"
          on_right: "exec cmd /c Taskmgr"
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - {icon: "File", launch: "explorer"}
        - {icon: "Code", launch: "code"}
        - {icon: "Terminal", launch: "wt"}
        - {icon: "Notepad", launch: "notepad"}
  app_button:
      type: "yasb.custom.CustomWidget"
      options:
        label: "<span>\uf40e</span>"
        label_alt: "<span>\uf40e</span>"
        class_name: "app-button"
        callbacks:
          on_left: "exec start_menu"
```

### Readme

```markdown
Yasb 003 is the theme posted on the Komorebi repository README page. Demo https://github.com/LGUG2Z/komorebi?tab=readme-ov-file#demonstrations
```
