### ISSUE TITLE
[create-theme]: Spectrum Symphony

### ISSUE THREAD

**Issue by amnweb** [amnweb/yasb-themes#25]
### Name

Spectrum Symphony

### Description

A vibrant theme with a harmonious blend of colors for a visually stunning experience.

### Homepage

https://github.com/amnweb/yasb

### Image

https://i.imgur.com/8Spop3z.png

### Theme Styles

```css
* {
    font-size: 12px;
    color: #bec8e7;
    font-weight: 500;
    font-family: "JetBrainsMono NFP";
    margin: 0;
    padding: 0;
}
.yasb-bar {
    padding: 0;
    margin: 0;
}
.widget {
    padding: 0 8px;
    margin: 0 4px;
    border-radius: 6px;
}
.widget .icon {
    font-size: 18px;
}
.win-btn {
    background-color: #F3BF7D;
}
.win-btn .icon {
    color: #142123;
}
.komorebi-workspaces {
    background-color: #221f2e;
}
.komorebi-workspaces .offline-status {
    color: #627199;
    font-size: 12px;
    padding: 0 4px;
    font-weight: 600;
}
.komorebi-workspaces .ws-btn {
    border: none;
    background-color: #9cd1dd;
    margin: 0px 4px;
    padding: 0;
    color: rgba(0, 0, 0, 0);
    border-radius: 5px;
    height: 10px;
    width: 10px;
}
.komorebi-workspaces .ws-btn:hover {
    background-color: #91b2e7;
}
.komorebi-workspaces .ws-btn.populated {
    background-color: #ea7094;
}

.komorebi-workspaces .ws-btn.active {
    color: rgba(149, 177, 255, 0);
    background-color: #c0aae8;
    width: 36px;
    height: 10px;
    border-radius: 5px;
}
.traffic-widget {
    background-color: #9ecfd7;
    padding: 0;
}
.traffic-widget .icon {
    color: #142123;
    padding-right: 6px;
    padding-left: 6px;
}
.traffic-widget .label {
    background-color: #221f2e;
    margin: 1px;
    border-radius: 6px;
    padding: 0 6px;
    color: #9ecfd7;
}

.clock-widget {
    background-color: #c2a8e3;
    padding: 0;
}
.clock-widget .icon {
    color: #142123;
    padding: 0 6px;
}
.clock-widget .label {
    background-color: #221f2e;
    color: #c2a8e3;
    padding: 0 6px;
    margin: 1px;
    border-radius: 6px;
}
.volume-widget {
    background-color: #f38ba8;
    padding: 0;
}
.volume-widget .icon {
    color: #142123;
    padding: 0 6px;
}
.volume-widget .label {
    background-color: #221f2e;
    color: #f38ba8;
    padding: 0 8px;
    margin: 1px;
    border-radius: 6px;
}
.weather-widget {
    background-color: #9ecfd7;
    padding: 0;
}
.weather-widget .icon {
    color: #142123;
    padding: 0 6px;
}
.weather-widget .label {
    background-color: #221f2e;
    color: #9ecfd7;
    padding: 0 6px;
    margin: 1px;
    border-radius: 6px;
}

.power-menu-widget {
    background-color: #c4a7e7;
    padding: 0;
}

.power-menu-widget .label {
    color: #142123;
    padding: 0 8px;
    font-weight: bold;
    font-size: 14px;
}

.language-widget {
    background-color: #f5c276;
    padding: 0;
}
.language-widget .icon {
    color: #142123;
    padding: 0 6px;
}
.language-widget .label {
    background-color: #221f2e;
    color: #f5c276;
    padding: 0 8px;
    margin: 1px;
    border-radius: 6px;
}
.taskbar-widget {
    background-color: #221f2e;
    padding: 0;
}
.taskbar-widget .app-icon {
    padding: 0 8px;
    border: none;
    margin: 0;
}
.active-window-widget {
    background-color: #c6a7e8;
    padding: 0;
}
.active-window-widget .label {
    color: #c6a7e8;
    background-color: #221f2e;
    padding: 0 8px;
    margin: 1px;
    border-radius: 6px;
}
.active-window-widget .icon {
    padding: 0 8px;
    border: none;
    margin: 0;
    background-color: #c6a7e8;
}


/*POWER MENU POPUP*/
.uptime {
    font-size: 14px;
    margin-bottom: 10px;
    color: rgba(191, 202, 219, 0.726);
    font-weight: 600;
}
.power-menu-popup {
    background-color: rgba(24, 24, 37, 0);
    border-radius: 12px;

}
.power-menu-popup .button {
    padding: 0;
    width: 180px;
    height: 230px;
    border-radius: 8px;
    background-color: #221f2e;
    color: #c2a7e2;
    border: 8px solid #1b1925;
    margin: 0px;
}
.power-menu-popup .button.hover {
    background-color: #1b1925;
}
.power-menu-popup .button .label {
    margin-bottom: 8px;
    font-size: 16px;
    font-weight: 500;
    color: #c5a6e7;

}
.power-menu-popup .button .icon {
    font-size: 64px;
    padding-top: 32px;
    color: #c5a6e7;
}
.power-menu-popup .button.cancel .icon {
    padding: 0;
    margin: 0;
}
.power-menu-popup .button.cancel .label {
    margin: 0;
}

.power-menu-popup .button.cancel {
    height: 32px;
    border-radius: 4px;
    border: none;
    background-color: #221f2e;
}
.power-menu-popup .button.cancel:hover {
    background-color: #1b1925;
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 28
    padding:
      top: 4
      left: 4
      bottom: 0
      right: 4
    widgets:
      left:
        [
          "win_button",
          "komorebi_workspaces",
          "traffic"
        ]
      center: [
         "active_window"
        ]
      right:
        [
          "taskbar",
          "language",
          "weather",
          "volume",
          "clock",
          "power_menu",
        ]
widgets:
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "<span>\uf11c</span>{lang[country_code]}"
      update_interval: 5
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\udb83\ude17</span>{%a %b %d %H:%M}"
      label_alt: "<span>\udb83\ude17</span>{%A, %d %B %Y %H:%M}"
      timezones: []
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "\u26a1 Offline"
        label_workspace_btn: ""
        label_workspace_active_btn: ""
        label_workspace_populated_btn: ""
        label_default_name: "{index}"
        label_zero_index: false
        hide_empty_workspaces: false
        hide_if_offline: false
        animation: true
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp_c}"
      label_alt: "<span>{icon}</span> {location}: Min {min_temp_c}, Max {max_temp_c}, Humidity {humidity}"
      api_key: '24b6c2cda6d84066b0304531241908'
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: 'USA Los Angeles 90006'
      callbacks:
        on_left: "toggle_label"
      icons: 
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd99"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\udb81\udd99"
        rainyDay: "\udb81\udd99"
        rainyNight: "\udb81\udd99"
        snowyIcyDay: "\udb81\udd99"
        snowyIcyNight: "\udb81\udd99"
        blizzard: "\udb81\udd99"
        default: "\udb81\udd99"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "<span>\uf011</span>"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200 # Milisecond 
      button_row: 5 # Number of buttons in row, min 1 max 5
      buttons:
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        signout: ["\udb80\udf43","Sign out"]
        hibernate: ["\uf28e","Hibernate"]
        sleep: ["\u23fe","Sleep"]
        cancel: ["","Cancel"]
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation: true
      icon_size: 14
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  win_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      label_alt: "<span>\udb80\udf5c</span>"
      class_name: "win-btn"
      callbacks:
        on_left: "exec start_menu"
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\udb82\udcfa</span> \uea9a{download_speed} \ueaa1{upload_speed}"
      label_alt: "<span>\udb82\udcfa</span> Download {download_speed} | Upload {upload_speed}"
      update_interval: 1000
      callbacks:
        on_left: 'toggle_label'
        on_right: 'exec cmd /c Taskmgr'
```

### Readme

```markdown
## Spectrum Symphony
![Windows 11 Theme](https://i.imgur.com/8Spop3z.png)

A vibrant theme with a harmonious blend of colors for a visually stunning experience.

![Windows 11 Theme](https://i.imgur.com/L7Skwtm.png)
```
