### ISSUE TITLE
[create-theme]: Yasb 004

### ISSUE THREAD

**Issue by amnweb** [amnweb/yasb-themes#27]
### Name

Yasb 004

### Description

My personal and favorite theme

### Homepage

https://github.com/amnweb/yasb

### Image

https://i.imgur.com/ZEaPyRJ.png

### Theme Styles

```css
:root {
    --rosewater: #f5e0dc;
    --flamingo: #f2cdcd;
    --pink: #f5c2e7;
    --mauve: #cba6f7;
    --red: #f38ba8;
    --maroon: #eba0ac;
    --peach: #fab387;
    --yellow: #f9e2af;
    --green: #a6e3a1;
    --teal: #94e2d5;
    --sky: #89dceb;
    --sapphire: #74c7ec;
    --blue: #89b4fa;
    --lavender: #b4befe;
    --text: #cdd6f4;
    --subtext1: #bac2de;
    --subtext0: #a6adc8;
    --overlay2: #9399b2;
    --overlay1: #7f849c;
    --overlay0: #6c7086;
    --surface2: #585b70;
    --surface1: #45475a;
    --surface0: #282936;
    --base: #1e1e2e;
    --mantle: rgba(24, 24, 37, 0.5);
    --crust: rgba(17, 17, 27, 0.5);
}
*{
	font-size: 12px;
	color: var(--subtext0);
	font-weight: 600;
	font-family: "JetBrainsMono NFP";
	margin: 0;
	padding: 0;
}
.yasb-bar {
	padding: 0;
	margin: 0; 
    background-color: var(--crust)
}
.widget {
	padding: 0 12px;
	margin: 0;
}
.icon {
	font-size: 16px;
}
.widget .label {
	padding: 0px 2px; 
}

.apps-widget {
	padding: 0 4px 0 2px;
}
.komorebi-active-layout {
	padding: 0 4px 0 0;
}
.komorebi-active-layout .label {
	font-weight: 600;
	padding: 2px 0 0 0;
}
.apps-widget .widget-container,
.komorebi-workspaces .widget-container,
.komorebi-active-layout .widget-container{
	background-color: var(--crust);
	margin: 4px 0 4px 0;
	border-radius: 12px;
    border: 0px solid var(--surface1);
}
.komorebi-workspaces .widget-container {
    border-top-left-radius: 6px;
	border-bottom-left-radius: 6px;
    margin-left: 4px;
}
.komorebi-workspaces {
	border-top-right-radius: 14px;
	border-bottom-right-radius: 14px;
	padding: 0 4px 0 0;
}
.komorebi-workspaces .offline-status {
    color: var(--surface2);
    font-size: 12px;
    padding: 0 0 0 4px;
    font-weight:600;
}
.komorebi-workspaces .ws-btn {
    border: none;
    background-color:transparent;
	margin:0;
    font-size: 12px;
	color:  var(--overlay1);
    height: 28px;
    width: 18px;
}
.komorebi-workspaces .ws-btn:hover {
    color: var(--subtext1);
}
.komorebi-workspaces .ws-btn.populated {
    color:transparent;
    width: 10px;
    height: 10px;
    background-color: var(--lavender);
    border-radius: 5px;
    margin: 0 4px;
    font-size: 1px;
}
.komorebi-workspaces .ws-btn.active {
	color: transparent;
    background-color: var(--blue);
    width: 36px;
    height: 10px;
    margin: 0 4px;
    border-radius: 5px; 
}
.apps-widget .label {
	font-size: 14px;
	padding: 0 2px;
    color: var(--subtext0);
}
.apps-widget .label:hover {
	color: var(--text);
}
.uptime {
	font-size: 14px;
	margin-bottom: 10px;
	color: var(--surface2);
	font-weight: 600;
 
}
.power-menu-widget .label {
	color: #f38ba8;
	font-size: 13px;
}
.power-menu-popup {
	background-color: transparent	 
}
.power-menu-popup .button {
	padding: 0;
	width: 180px;
	height: 230px;
	border-radius: 8px;
	background-color: var(--base);
	color:var(--text);
	border-left: 4px solid rgba(58, 59, 83, 0);
    border-right: 4px solid rgba(58, 59, 83, 0);
    border-top: 8px solid rgba(58, 59, 83, 0);
    border-bottom: 8px solid rgba(58, 59, 83, 0);
	margin: 0px;
}
.power-menu-popup .button.hover {
	background-color:var(--surface0);
	border-left: 4px solid var(--surface0);
    border-right: 4px solid var(--surface0);
    border-top: 8px solid var(--surface0);
    border-bottom: 8px solid var(--surface0);
}
.power-menu-popup .button .label {
	margin-bottom: 8px;
	font-size: 16px;
	font-weight: 500;
	color: var(--surface2)
 
}
.power-menu-popup .button .icon {
	font-size: 64px;
	padding-top: 32px;
	color: var(--surface2)
}
.power-menu-popup .button.cancel .icon {
    padding: 0;
    margin: 0;
}
.power-menu-popup .button.cancel .label {
	color: var(--red);
    margin: 0;
}
.power-menu-popup .button.cancel {
    height: 32px;
    border-radius: 4px;
}
.volume-widget .icon {
	color: var(--blue);
	margin: 1px 2px 0 0;
}
.github-widget .icon {
    font-size: 14px;
	color: var(--text)
}
.github-widget .icon.new-notification {
    color: var(--red);
}
.weather-widget,
.github-widget,
.volume-widget {
    padding:0 6px;
}
.weather-widget .icon {
	font-size: 18px;
	margin: 0 2px 1px 0;
    color: var(--yellow);
}
.ai-widget {
	padding: 0 4px 0 4px;
    margin: 0;
}
.ai-widget .widget-container
 {
 	margin: 4px 0 4px 0;
	border-radius: 12px;
}
.ai-widget .icon {
	color: var(--sky);
	padding: 0 5px;
    font-size: 16px;
	margin: 0;
}
.ai-widget .icon:hover {
	color: #fff;
}
.taskbar-widget{
    padding: 0;
    margin: 0;
    border: none;
}
.taskbar-widget .app-icon{
    padding:0 6px;
    border: none;
    margin: 0;
}
.whkd-widget {
    padding: 0 6px 0 6px;
}
.whkd-widget .icon {
    font-size: 14px;
}
.wallpapers-widget {
    padding: 0 6px 0 6px;
}
.wallpapers-gallery-window {
    background-color: rgba(85, 42, 240, 0.01);
    border: 0;
    margin: 0;
}
.wallpapers-gallery-buttons {
    background-color:rgba(255, 255, 255, 0);
    color:var(--text);
    border: none;
    font-size: 14px;
    padding: 8px 0;
    border-radius: 8px;
    margin:0 8px 8px 8px;
    width: 600px;
}
.wallpapers-gallery-buttons:hover {
    background-color:rgba(255, 255, 255, 0.1)
}
.wallpapers-gallery-image {
    border: 4px solid transparent;
    border-radius: 10px;
 
}
.wallpapers-gallery-image:hover {
    border: 4px solid var(--sapphire);
}
.wallpapers-gallery-image.focused {
    border: 4px solid var(--sapphire);
}

.update-check-widget {
    padding: 0 0px 0 0px;
}
.update-check-widget .icon {
    font-size: 14px;
}
.update-check-widget .widget-container.winget,
.update-check-widget .widget-container.windows {
    background: var(--maroon);
    margin: 7px 2px 7px 2px;
    border-radius: 9px;
    border: 2px solid var(--red);
}
.update-check-widget .widget-container.windows {
    background: var(--lavender);
    margin: 7px 2px 7px 2px;
    border-radius: 9px;
    border: 2px solid var(--blue);
}
.update-check-widget .widget-container.winget .icon,
.update-check-widget .widget-container.windows .icon {
    color: var(--base);
    margin: 0 1px 0 6px;
}
.update-check-widget .widget-container.winget .label,
.update-check-widget .widget-container.windows .label {
    margin: 0 6px 0 1px;
    color: var(--base);
    font-weight: 900;
    font-size: 14px;
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 4
      left: 6
      bottom: 0
      right: 6
    widgets:
      left: ["komorebi_workspaces","active_window"]
      center: ["clock","apps"]
      right: ["update","ai","wallpapers","github","taskbar","weather","whkd","volume","power_menu"]
widgets:
  update:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      winget_update:
        enabled: true
        label: "<span>\uf0ab</span>{count}"
        interval: 30
        exclude: []
      windows_update:
        enabled: true
        label: "<span>\uf0ab</span>{count}"
        interval: 240
        exclude: []
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: false
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M:%S}"
      timezones: []
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "\u23fc Offline"
      label_workspace_btn: "\udb81\udc3d"
      label_workspace_active_btn: ""
      label_workspace_populated_btn: "\udb81\udc3e"
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: true
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "grid",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "right_main_vertical_stack",
        ]
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        vertical_stack: "V-STACK"
        horizontal_stack: "H-STACK"
        ultrawide_vertical_stack: "W-STACK"
        right_main_vertical_stack: "RMV-STACK"
        monocle: "MONOCLE"
        maximised: "MAX"
        floating: "FLOATING"
        paused: "PAUSED"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      callbacks:
        on_left: "next_layout"
        on_middle: "toggle_monocle"
        on_right: "prev_layout"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp_c}"
      label_alt: "{location}: Min {min_temp_c}, Max {max_temp_c}, Humidity {humidity}"
      api_key: "24b6c2cda6d84066b0304531241908"
      update_interval: 600
      hide_decimal: true
      location: "USA Los Angeles 90006"
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd99"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\udb81\udd99"
        rainyDay: "\udb81\udd99"
        rainyNight: "\udb81\udd99"
        snowyIcyDay: "\udb81\udd99"
        snowyIcyNight: "\udb81\udd99"
        blizzard: "\udb81\udd99"
        default: "\udb81\udd99"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      label: "{data}"
      app_list:
        - { icon: "\uf0a2", launch: "notification_center" }
        - { icon: "\uf422", launch: "launcher" }
        - { icon: "\ueb03", launch: "cmd /c Taskmgr" }
        - { icon: "\uf489", launch: "wt" }
        - { icon: "\udb84\udec7", launch: "C:\\Program Files\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE" }
        - { icon: "\uf1ff",launch: "C:\\Users\\amn\\AppData\\Local\\Discord\\Update.exe --processStart Discord.exe" }
        - { icon: "\ue217",launch: "C:\\Users\\amn\\AppData\\Roaming\\Telegram Desktop\\Telegram.exe" }
        - { icon: "\ued38",launch: "C:\\Users\\amn\\AppData\\Local\\Viber\\Viber.exe" }
        - { icon: "\uf17e",launch: "C:\\Program Files (x86)\\Microsoft\\Skype for Desktop\\Skype.exe" }
        - { icon: "\udb80\ude39",launch: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" }
        - { icon: "\udb82\ude1e",launch: "C:\\Users\\amn\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" }
  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\ueba1</span>"
      label_alt: "Notifications {data}"
      token: env
      max_notification: 30
      only_unread: false
      max_field_size: 54
      menu_width: 400
      menu_height: 400
      menu_offset: 240
      update_interval: 60
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation: true
      icon_size: 16
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  ai:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\udb81\ude74</span>"
      label_alt: "\udb81\ude74"
      class_name: "ai-widget"
      callbacks:
        on_left: "exec cmd.exe /c start \"C:\\Program Files\\Mozilla Firefox\\firefox.exe\" https://platform.openai.com/playground/chat?models=gpt-4o"
  whkd:
    type: "yasb.whkd.WhkdWidget"
    options:
      label: "<span>\uf11c</span>"
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\amn\\Pictures\\Wallpapers"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 296
        image_per_page: 6
        show_buttons: false
        orientation: "portrait"
        image_spacing: 10
        lazy_load: true
        lazy_load_delay: 10
        lazy_load_fadein: 200
        image_corner_radius: 20
        enable_cache: true
```

### Readme

```markdown
My personal and favorite theme
```
