### ISSUE TITLE
[create-theme]:  Minimal Glaze

### ISSUE THREAD

**Issue by hax2** [amnweb/yasb-themes#39]
### Name

Minimal Glaze

### Description

Practical, no bells or whistles, click the network traffic to show/hide it

### Image

https://files.catbox.moe/o5qfln.png

### Theme Styles

```css
/* 
This is default and very simple styles file for Yasb. 
For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
*/
:root {
    --rosewater: #f5e0dc;
    --flamingo: #f2cdcd;
    --pink: #f5c2e7;
    --mauve: #cba6f7;
    --red: #f38ba8;
    --maroon: #eba0ac;
    --peach: #fab387;
    --yellow: #f9e2af;
    --green: #a6e3a1;
    --teal: #94e2d5;
    --sky: #89dceb;
    --sapphire: #74c7ec;
    --blue: #89b4fa;
    --lavender: #b4befe;
    --text: #cdd6f4;
    --subtext1: #bac2de;
    --subtext0: #a6adc8;
    --overlay2: #9399b2;
    --overlay1: #7f849c;
    --overlay0: #6c7086;
    --surface2: #585b70;
    --surface1: #45475a;
    --surface0: #282936;
    --base: #1e1e2e;
    --mantle: rgba(24, 24, 37, 0.5);
    --crust: rgba(17, 17, 27, 0.85);
    --main: #10151d;
}
/* Global styles for ToolTip */
QToolTip {
    padding: 6px;
    color: #cdd6f4;
    font-size: 12px;
    background-color: #1e1e2e;
    border: 0px solid #313244;
    border-radius: 6px;
}
* {
    font-size: 12px;
    color: var(--subtext0);
    font-weight: 600;
    font-family: "JetBrainsMono NFP";
    margin: 0;
    padding: 0;
}
.yasb-bar {
    padding: 0;
    margin: 0;
    background-color: black;
    border-radius: 8px;
}
.widget {
    padding: 0 12px;
    margin: 0;
}
.icon {
    font-size: 16px;
}
.widget .label {
    padding: 0px 2px;
}
.komorebi-active-layout {
    padding: 0 4px 0 0;
}
.komorebi-active-layout .label {
    font-weight: 600;
    padding: 2px 0 0 0;
}
.apps-widget .widget-container,
.komorebi-workspaces .widget-container,
.komorebi-active-layout .widget-container {
    background-color: var(--crust);
    margin: 3px 0 3px 0;
    border-radius: 12px;
    border: 1px solid var(--surface0);
}
.komorebi-workspaces .widget-container {
    border-top-left-radius: 6px;
    border-bottom-left-radius: 6px;
    margin-left: 4px;
}
.komorebi-workspaces {
    border-top-right-radius: 14px;
    border-bottom-right-radius: 14px;
    padding: 0 4px 0 0;
}
.komorebi-workspaces .offline-status {
    color: var(--surface2);
    font-size: 12px;
    padding: 0 0 0 4px;
    font-weight: 600;
}
.komorebi-workspaces .ws-btn {
    border: none;
    background-color: transparent;
    margin: 0;
    font-size: 12px;
    color: var(--overlay1);
    height: 28px;
    width: 18px;
}
.komorebi-workspaces .ws-btn:hover {
    color: var(--subtext1);
}
.komorebi-workspaces .ws-btn.populated {
    color: transparent;
    width: 10px;
    height: 10px;
    background-color: var(--lavender);
    border-radius: 5px;
    margin: 0 4px;
    font-size: 1px;
}
.komorebi-workspaces .ws-btn.active {
    color: transparent;
    background-color: var(--blue);
    width: 36px;
    max-width: 36px;
    height: 10px;
    margin: 0 4px;
    border-radius: 5px;
}
.apps-widget {
    padding: 0 4px 0 2px;
}
.apps-widget .label {
    font-size: 14px;
    padding: 0 2px;
    color: var(--subtext0);
}
.apps-widget .label:hover {
    color: var(--text);
}

.power-menu-widget .label {
    color: #f38ba8;
    font-size: 13px;
}
.power-menu-popup {
    background-color: transparent
}
.power-menu-popup .button {
    padding: 0;
    width: 180px;
    height: 230px;
    border-radius: 8px;
    background-color: var(--crust);
    color: var(--text);
    border-left: 4px solid rgba(58, 59, 83, 0);
    border-right: 4px solid rgba(58, 59, 83, 0);
    border-top: 4px solid rgba(58, 59, 83, 0);
    border-bottom: 4px solid rgba(58, 59, 83, 0);
    margin: 0px;
}
.power-menu-popup .button.hover {
    background-color: var(--base);
    border-left: 4px solid var(--base);
    border-right: 4px solid var(--base);
    border-top: 4px solid var(--base);
    border-bottom: 4px solid var(--base);
}

.power-menu-popup .button .label {
    margin-bottom: 8px;
    font-size: 16px;
    font-weight: 500;
    color: var(--overlay2)
}
.power-menu-popup .button .icon {
    font-size: 64px;
    padding-top: 32px;
    color: var(--surface2)
}

.power-menu-popup .button.cancel .icon {
    padding: 0;
    margin: 0;
}
.power-menu-popup .button.cancel .label {
    color: var(--red);
    margin: 0;
}
.power-menu-popup .button.cancel {
    height: 32px;
    border-radius: 4px;
}
.glazewm-workspaces {
    margin: 0;
}

.glazewm-workspaces .ws-btn {
    font-size: 14px;
    background-color: transparent;
    border: none;
    padding: 4px 8px; /* Increased padding */
    margin: 0; /* Remove margin between buttons */
    color: #CDD6F4;
    transition: all 0.2s ease;
    height: 100%; /* Take full height of container */
    display: flex;
    align-items: center;
    justify-content: center;
}

.glazewm-workspaces .ws-btn.active,
.glazewm-workspaces .ws-btn:hover {
    background-color: #727272;
    border-radius: 4px; /* Optional: Add slight rounding */
}

/* Keep existing populated/empty state colors */
.glazewm-workspaces .ws-btn.populated {
    color: #C2DAF7;
}

.glazewm-workspaces .ws-btn.empty {
    color: #7D8B9D;
}
.glazewm-workspaces .ws-btn:hover,
.glazewm-workspaces .ws-btn.populated:hover,
.glazewm-workspaces .ws-btn.empty:hover {
    background-color: #727272;
    height: 100%;  /* Ensures full height */
    margin: 0;     /* Ensures no gaps */
    border-radius: 0;  /* Removes rounded corners */
    display: flex;  /* Ensures proper stretching */
    align-items: center;  /* Centers content vertically */
    justify-content: center;  /* Centers content horizontally */
}

}
.uptime {
    font-size: 14px;
    margin-bottom: 10px;
    color: var(--surface2);
    font-weight: 600;
}
.glazewm-tiling-direction {
    background-color: transparent;
    padding: 0;
    margin: 0;
}

.glazewm-tiling-direction .btn {
    font-size: 18px;
    width: 14px;
    padding: 0 4px 0 4px;
    color: #CDD6F4;
    border: none;
}

.glazewm-tiling-direction .btn:hover {
    background-color: #727272;
}

.microphone-widget {
    padding: 0 6px 0 6px;
}
.microphone-widget .icon {
    font-size: 18px;
}
.microphone-widget .icon {
    color: var(--mauve);
}
.volume-widget .icon {
    color: var(--blue);
    margin: 1px 2px 0 0;
}
.weather-widget,
.volume-widget {
    padding: 0 6px;
}
.weather-widget .icon {
    font-size: 18px;
    margin: 0 2px 1px 0;
    color: var(--yellow);
}
.media-widget {
    padding: 0;
    margin: 0;
    border-radius: 0;
}
.media-widget .label {
    color: #bac2db;
    padding: 0px;
    padding-right: 4px;
    font-size: 12px;
}
.media-widget .label.maintext {
    padding-top: 3px;
}
.media-widget .btn {
    color: #989caa;
    padding: 0 1px;
    margin: 0;
    font-family: Segoe Fluent Icons;
    font-weight: 400;
}
.media-widget .btn:hover {
    color: #babfd3;
}
.media-widget .btn.play {
    font-size: 16px;
}
.media-widget .btn.disabled:hover,
.media-widget .btn.disabled {
    color: #4e525c;
    font-size: 12px;
    background-color: rgba(0, 0, 0, 0);
}
.taskbar-widget {
    padding: 0;
    margin: 0;
    border: none;
}
.wifi-widget {}
.wifi-widget .widget-container {}
.wifi-widget .widget-container .label {}
.wifi-widget .widget-container .label.alt {}
.wifi-widget .widget-container .icon {}
.taskbar-widget .app-icon {
    padding: 0 6px;
    border: none;
    margin: 0;
}
.home-widget {
    padding: 0 0px 0 4px;
}
.home-widget .icon {
    color: var(--lavender);
}
.home-widget .icon:hover {
    color: var(--text);
}
.home-menu {
    background-color: var(--crust);
}
.home-menu .menu-item {
    padding: 8px 48px 9px 16px;
    font-size: 12px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: var(--text);
    font-weight: 600;
}
.home-menu .menu-item:hover {
    background-color: rgba(128, 130, 158, 0.15);
    color: #fff;
}
.home-menu:separator {
    height: 1px;
    background-color: rgba(128, 130, 158, 0.3);
}
.clock-widget .label {
    font-size: 14px;
    color: var(--pink);
}
/* Traffic Widget - Fixed Width Version */
.traffic-widget .widget-container {
    min-width: 200px;  /* Fixed width container */
    text-align: center;  /* Keep content centered */
}

.traffic-widget .label {
    font-family: monospace;  /* Use fixed-width characters */
    font-size: 0.9em;  /* Optional: adjust font size */
    letter-spacing: -0.5px;  /* Compensate for monospace spacing */
}

.traffic-widget .label.alt {
    font-family: monospace;  /* Keep consistent between states */
}

.traffic-widget .icon {
    font-family: "Segoe UI Symbol";  /* Ensure icon font loads */
}
```

### Theme Config

```yaml
# This is default and very simple configuration file for Yasb.  
# For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
watch_stylesheet: true
watch_config: true
debug: false
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "System"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 25
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
        "home",
        "glazewm_workspaces",
        "clock",
        "apps"
      ]
      center: [
        "media"
      ]
      right: [
        "traffic",
        "glazewm_tiling_direction",
        "battery",
        "volume",
        "brightness",
        "weather",
        "power_menu"
      ]
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>󰜗</span>"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "~\\Downloads" }
      - { title: "Documents", path: "~\\Documents" }
      - { title: "Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: false

  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{artist}"
      max_field_size:
        label: 64
        label_alt: 24
      show_thumbnail: false
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 150
      thumbnail_padding: 8
      thumbnail_corner_radius: 0
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
  
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b %I:%M %p}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      timezones: []
  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "󰓡"
      vertical_label: "󰓢"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807"
      update_interval: 600
      hide_decimal: true
      location: "Sweden Gothenburg 411 06"
      callbacks:
        on_left: "toggle_label"

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:network"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      wifi_icons: [
        "󰤮",  # 0% strength icon
        "󰤟",  # 1-20% strength
        "󰤢",  # 21-40% strength
        "󰤥",  # 41-80% strength
        "󰤨"   # 81-100% strength
      ]

  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: " \ueab4 {download_speed} | \ueab7 {upload_speed}"
      label_alt: " "
      update_interval: 1000
      callbacks:
        on_left: "toggle_label"
        on_right: "exec cmd /c Taskmgr"
      animation:
        enabled: true
        type: "fadeInOut"
        duration: 200

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false

  battery:
   type: "yasb.battery.BatteryWidget"
   options:
      label: "<span>{icon}</span>{percent}%"
      label_alt: "{icon} {percent}% | time: {time_remaining}"
      charging_options:
       icon_format: "{charging_icon}"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  
  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "Brightness {percent}%"
      tooltip: true
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - { icon: "\uf422", launch: "search" }
        - { icon: "\ueb03", launch: "cmd /c Taskmgr" }
        - { icon: "\uf07c", launch: "explorer" }
```

### Readme

```markdown
Small edits to the default YASB theme
```
