### ISSUE TITLE
[create-theme]: Soft Segment

### ISSUE THREAD

**Issue by amnweb** [amnweb/yasb-themes#42]
### Name

Soft Segment

### Description

Theme where each widget is segmented with a 1px margin. If you want to use this theme, please enter your Weather API key and set the weather location.

### Homepage

https://github.com/amnweb/yasb-themes

### Image

https://i.imgur.com/gFwoyGh.png

### Theme Styles

```css
:root {
    --rosewater: #f5e0dc;
    --flamingo: #f2cdcd;
    --pink: #f5c2e7;
    --mauve: #cba6f7;
    --red: #f38ba8;
    --maroon: #eba0ac;
    --peach: #fab387;
    --yellow: #f9e2af;
    --green: #a6e3a1;
    --teal: #94e2d5;
    --sky: #89dceb;
    --sapphire: #74c7ec;
    --blue: #89b4fa;
    --lavender: #b4befe;
    --text: #cdd6f4;
    --subtext1: #bac2de;
    --subtext0: #a6adc8;
    --overlay2: #9399b2;
    --overlay1: #7f849c;
    --overlay0: #6c7086;
    --surface2: #585b70;
    --surface1: #45475a;
    --surface0: #282936;
    --base: #1e1e2e;
    --mantle: #181825;
    --crust: #11111b;
    --main: #10151d;
}
/* Global menu section, widgets. labels and icons */
QToolTip {
    margin: 6px;
    color: #cdd6f4;
    font-size: 12px;
    background-color: #1e1e2e;
    border: 0px solid #313244;
    border-radius: 6px;
}
* {
    font-size: 12px;
    color: var(--subtext0);
    font-weight: 600;
    font-family: Arial, Helvetica, sans-serif;
    margin: 0;
    padding: 0;
}
.widget {
    padding: 0 14px;
    margin: 0;
    background-color: var(--mantle);
    margin: 0 1px;
    border-radius: 4px;
}
.icon,
.power-menu-widget .label {
    font-family: "JetBrainsMono NFP";
    font-size: 16px;
}
.widget .label {
    padding: 0 2px 0 2px;
}
.home-widget,
.disk-widget {
    border-top-left-radius: 16px;
    border-bottom-left-radius: 16px;
}
.power-menu-widget,
.apps-widget {
    border-top-right-radius: 16px;
    border-bottom-right-radius: 16px;
}

.traffic-widget {
    min-width: 76px;
}
.traffic-widget .label {
    font-size: 11px;
}
.apps-widget .label:hover {
    color: #fff;
}

.komorebi-workspaces .offline-status {
    color: var(--green);
    padding: 0;
}
.komorebi-workspaces .ws-btn {
    border: none;
    background-color: var(--overlay1);
    margin: 0 4px;
    font-size: 0px;
    color: transparent;
    width: 12px;
    height: 12px;
    border-radius: 6px;
}
.komorebi-workspaces .ws-btn:hover {
    background-color: var(--subtext1);
}
.komorebi-workspaces .ws-btn.populated {
    background-color: var(--lavender);
}
.komorebi-workspaces .ws-btn.active {
    color: transparent;
    background-color: var(--blue);
    width: 36px;
    max-width: 36px;
    height: 12px;
}
.komorebi-workspaces .float-override {
    color: var(--green);
    padding-left: 6px;
}

/* Icons settings and colors */
.home-widget .icon {
    color: var(--sky);
}
.cpu-widget .icon {
    color: var(--green);
    margin-right: 6px;
}
.memory-widget .icon {
    color: var(--yellow);
    margin-right: 6px;
}
.wifi-widget .icon {
    color: var(--blue);
}
.volume-widget .icon {
    color: var(--pink);
    margin-right: 6px;
}
.power-menu-widget .label {
    color: var(--red);
}
.disk-widget .icon {
    color: var(--lavender);
}
.notification-widget .icon {
    margin-right: 6px;
}
.notification-widget .icon,
.notification-widget .label {
    color: var(--sky);
}
.weather-widget .icon {
    color: var(--yellow);
    font-size: 20px;
    margin-right: 6px;
}

/* Popup window style */
.calendar {
    background-color: var(--mantle);
}
.calendar .calendar-table,
.calendar .calendar-table::item {
    background-color: transparent;
    color: rgba(162, 177, 196, 0.85);
    margin: 0;
    padding: 0;
    border: none;
    outline: none;
}
.calendar .calendar-table::item:selected {
    color: var(--crust);
    background-color: var(--blue);
    border-radius: 10px;
}
.calendar .day-label {
    margin-top: 20px;
}
.calendar .day-label,
.calendar .month-label,
.calendar .date-label {
    font-size: 16px;
    color: var(--subtext0);
    font-weight: 700;
    min-width: 180px;
    max-width: 180px;
}
.calendar .month-label {
    font-weight: normal;
}
.calendar .date-label {
    font-size: 88px;
    font-weight: 900;
    color: rgb(255, 255, 255);
    margin-top: -20px;
}
.home-menu {
    background-color: var(--mantle);
}
.home-menu .menu-item {
    padding: 8px 38px 9px 16px;
    font-size: 12px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: var(--text);
    font-weight: 600;
}

.home-menu .menu-item:hover {
    background-color: rgba(128, 130, 158, 0.15);
    color: #fff;
}

.home-menu .separator {
    max-height: 1px;
    background-color: rgba(128, 130, 158, 0.3);
}
.disk-group {
    background-color: var(--mantle);
}
.disk-group-row {
    min-width: 220px;
    max-width: 220px;
    max-height: 40px;
    margin: 0;
    padding: 0;
    border-radius: 6px;
    border: 1px solid rgba(128, 128, 128, 0);

}
.disk-group-row:hover {
    background-color: rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
}
.disk-group-label-bar {
    max-height: 8px;
    border: 0px solid rgba(128, 128, 128, 0);
    background-color: rgba(137, 180, 250, 0.1);
    border-radius: 4px;
}
.disk-group-label-bar::chunk {
    background-color: rgba(61, 135, 255, 0.3);
    border-radius: 14px;
}
.disk-group-label {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}
.disk-group-label-size {
    font-weight: 600;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-size: 11px;
    color: #666879;
}
.power-menu-popup {
    background-color: transparent
}
.power-menu-popup .button {
    padding: 0;
    width: 180px;
    height: 230px;
    border-radius: 8px;
    background-color: var(--mantle);
    color: var(--text);
    border-left: 4px solid rgba(58, 59, 83, 0);
    border-right: 4px solid rgba(58, 59, 83, 0);
    border-top: 4px solid rgba(58, 59, 83, 0);
    border-bottom: 4px solid rgba(58, 59, 83, 0);
    margin: 0px;
}
.power-menu-popup .button.hover {
    background-color: var(--base);
    border-left: 4px solid var(--base);
    border-right: 4px solid var(--base);
    border-top: 4px solid var(--base);
    border-bottom: 4px solid var(--base);
}

.power-menu-popup .button .label {
    margin-bottom: 8px;
    font-size: 16px;
    font-weight: 500;
    color: var(--overlay2)
}
.power-menu-popup .button .icon {
    font-size: 64px;
    padding-top: 32px;
    color: var(--surface2)
}

.power-menu-popup .button.cancel .icon {
    padding: 0;
    margin: 0;
}
.power-menu-popup .button.cancel .label {
    color: var(--red);
    margin: 0;
}
.power-menu-popup .button.cancel {
    height: 32px;
    border-radius: 4px;
}
.weather-card {
    background-color: var(--mantle)
}
.weather-card-today .label {
    font-size: 13px;
    font-weight: 600;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}
.weather-card-today .label.location {
    font-size: 24px;
    font-weight: 600;
}
.weather-card-day {
    background-color: var(--base);
    border: 1px solid rgba(128, 128, 128, 0.21);
    border-radius: 8px;
}
.weather-card-day .label {
    font-weight: 600;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}
.weather-card-today .label.arert {
    font-size: 12px;
    font-weight: 600;
    background-color: rgba(247, 199, 42, 0.05);
    border: 1px solid rgba(247, 209, 42, 0.1);
    color: rgba(196, 181, 162, 0.85);
    border-radius: 6px;
    padding: 5px 0;
}
.audio-menu {
    background-color: var(--mantle)
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false
hide_taskbar: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    animation:
      enabled: true
      duration: 800
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 36
    padding:
      top: 4
      left: 4
      bottom: 0
      right: 4
    widgets:
      left: [
        "home",
        "komorebi_workspaces",
        "clock",
        "apps"
      ]
      center: []
      right: [
        "disk",
        "cpu",
        "memory",
        "traffic",
        "wifi",
        "weather",
        "volume",
        "notifications",
        "power_menu"      
        ]
widgets:
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "<span>\uf473</span>"
        label_alt: "<span>\uf473</span>"
        group_label:
          volume_labels: ["C", "D", "E", "F"]
          show_label_name: true 
          blur: true
          round_corners: true
          border_color: None
          alignment: "center"
          distance: 4
        callbacks:
          on_left: "toggle_group"
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb81\udf17</span>"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "D:\\Downloads" }
      - { title: "Documents", path: "C:\\Users\\amn\\Documents" }
      - { title: "Pictures", path: "C:\\Users\\amn\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      border_color: None
      distance: 4
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
          on_left: "toggle_label"
      wifi_icons: [
          "\udb82\udd2e",  # Icon for 0% strength
          "\udb82\udd1f",  # Icon for 1-20% strength
          "\udb82\udd22",  # Icon for 21-40% strength
          "\udb82\udd25",  # Icon for 41-80% strength
          "\udb82\udd28"   # Icon for 81-100% strength
      ] 
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%b %d, %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      tooltip: false
      timezones: []
      callbacks:
        on_left: "toggle_calendar"
      calendar: 
        blur: true
        round_corners: true
        border_color: None
        distance: 4
        alignment: "left"
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: ""
      label_workspace_active_btn: ""
      label_workspace_populated_btn: ""
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: false
      animation: true
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: env
      update_interval: 120 #Update interval in seconds
      hide_decimal: true
      units: "metric" # "metric" or "imperial"
      location: env # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      show_alerts: true
      callbacks:
        on_left: "toggle_card"
        on_middle: "toggle_label"
      weather_card: 
        blur: true
        round_corners: true
        border_color: None
        alignment: "right"
        distance: 4
        icon_size: 32
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd99"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\udb81\udd99"
        rainyDay: "\udb81\udd99"
        rainyNight: "\udb81\udd99"
        snowyIcyDay: "\udb81\udd99"
        snowyIcyNight: "\udb81\udd99"
        blizzard: "\udb81\udd99"
        default: "\udb81\udd99"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
      audio_menu:
        blur: True
        round_corners: True
        border_color: None
        alignment: "right"
        direction: "down"
        distance: 4
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "<span>\uf011</span>"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200 # Milisecond
      button_row: 5 # Number of buttons in row, min 1 max 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - { icon: "Pictures", launch: "explorer C:\\Users\\amn\\Pictures" }
        - { icon: "Music", launch: "explorer C:\\Users\\amn\\Music" }
        - { icon: "Terminal", launch: "wt" }
        - { icon: "Mail", launch: "C:\\Program Files\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE" }
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<div style=\"text-align:right\">{upload_speed} \u25b2</div><div style=\"text-align:right;\">{download_speed} \u25bc</div>"
      update_interval: 1000
      hide_if_offline: false
      callbacks:
        on_left: 'do_nothing'
        on_middle: 'do_nothing'
        on_right: 'do_nothing'
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: true
      callbacks:
        on_left: "toggle_notification"
        on_right: "toggle_label"
        on_middle: "do_nothing" 
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
        label: "<span>\uefc5</span> {virtual_mem_used} / {virtual_mem_total}"
        label_alt: "<span>\uf4bc</span> VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
        update_interval: 5000
        callbacks:
            on_left: "toggle_label"
            on_middle: "do_nothing"
            on_right: "do_nothing"
        memory_thresholds:
            low: 25
            medium: 50
            high: 90
```

### Readme

```markdown
## Soft segment

Theme where each widget is segmented with a 1px margin. If you want to use this theme, please enter your Weather API key and set the weather location.

![Soft segment](https://i.postimg.cc/4yxvmB2G/Screenshot-2025-02-03-175708.png)
```
