### ISSUE TITLE
[create-theme]: Yasb 005

### ISSUE THREAD

**Issue by amnweb** [amnweb/yasb-themes#56]
### Name

Yasb 005

### Description

Theme based on catppuccin color scheme

### Homepage

https://github.com/amnweb

### Image

https://i.imgur.com/HjjWgMt.png

### Theme Styles

```css
:root {
    --red: #f38ba8;
    --yellow: #f9e2af;
    --green: #a6e3a1;
    --blue: #89b4fa;
    --lavender: #b4befe;
    --text: #cdd6f4;
    --overlay2: #9399b2;
    --surface2: #585b70;
    --surface1: #45475a;
    --base: #1e1e2e;
    --mantle: rgba(24, 24, 37, 0.5);
    --crust: rgba(17, 17, 27, 0.2);
    --main: #10151d;
    --widget-background: #24273a;
}
QToolTip {
    padding: 6px;
    color: #cdd6f4;
    font-size: 12px;
    background-color: #1e1e2e;
    border: 0px solid #313244;
    border-radius: 6px;
}
* {
    font-size: 12px;
    color: var(--blue);
    font-weight: 600;
    font-family: "JetBrainsMono NFP";
    margin: 0;
    padding: 0;
}
.yasb-bar {
    padding: 0 10px;
    margin: 0;
    background-color: var(--mantle);
}
.widget {
    padding: 0 2px;
    margin: 0;
}
.icon {
    font-size: 14px;
}
.widget .label {
    padding: 0px 2px;
}
.clock-widget .widget-container,
.volume-widget .widget-container,
.weather-widget .widget-container,
.media-widget .widget-container,
.notification-widget .widget-container,
.power-menu-widget .widget-container,
.memory-widget .widget-container,
.cpu-widget .widget-container,
.komorebi-workspaces .widget-container {
    background-color: var(--widget-background);
    margin: 2px 0 2px 0;
    border-radius: 8px;
}
.cpu-widget {
    padding-right: 0;
}
.memory-widget {
    padding-left: 0;
}
.cpu-widget .widget-container {
    border-bottom-right-radius: 0;
    border-top-right-radius: 0;
}
.memory-widget .widget-container {
    border-bottom-left-radius: 0;
    border-top-left-radius: 0;
}
.komorebi-workspaces .offline-status {
    color: var(--blue);
    font-size: 12px;
    padding: 0 0 0 4px;
    font-weight: 600;
}
.komorebi-workspaces .ws-btn {
    border: none;
    margin: 0;
    font-size: 14px;
    color: var(--blue);
    height: 28px;
    width: 18px;
}
.komorebi-workspaces .ws-btn:hover {
    color: var(--lavender);
}
.komorebi-workspaces .ws-btn.populated {
    color: var(--green);
}
.komorebi-workspaces .ws-btn.active {
    color: var(--green);
}
.apps-widget .label {
    font-size: 16px;
    padding: 0 1px;
}
.apps-widget .label:hover {
    color: var(--text);
}
.clock-widget .icon {
    color: var(--green);
    margin-right: 4px;
}
.calendar {
    background-color: var(--crust)
}
.calendar .calendar-table,
.calendar .calendar-table::item {
    background-color: rgba(17, 17, 27, 0);
    color: rgba(162, 177, 196, 0.85);
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    margin: 0;
    padding: 0;
    border: none;
    outline: none;  
}
.calendar .calendar-table::item:selected {
    color: var(--main);
    border-radius: 8px;
    background-color: var(--blue);
}
.calendar .day-label {
    margin-top: 20px;
}
.calendar .day-label,
.calendar .month-label,
.calendar .date-label {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-size: 16px;
    color: var(--blue);
    font-weight: 700;
    min-width: 180px;
    max-width: 180px;
}
.calendar .month-label {
    font-weight: normal;
}
.calendar .date-label {
    font-size: 88px;
    font-weight: 900;
    color: var(--blue);
    margin-top: -20px;
}
.power-menu-widget .label {
    font-size: 14px;
}
.power-menu-popup {
    background-color: transparent
}
.power-menu-popup .button {
    padding: 0;
    width: 180px;
    height: 230px;
    border-radius: 8px;
    background-color: var(--crust);
    color: var(--text);
    border-left: 10px solid rgba(58, 59, 83, 0);
    border-right: 10px solid rgba(58, 59, 83, 0);
    border-top: 10px solid rgba(58, 59, 83, 0);
    border-bottom: 10px solid rgba(58, 59, 83, 0);
    margin: 0px;
}
.power-menu-popup .button.hover {
    background-color: var(--base);
    border-left: 10px solid var(--base);
    border-right: 10px solid var(--base);
    border-top: 10px solid var(--base);
    border-bottom: 10px solid var(--base);
}
.power-menu-popup .button .label {
    margin-bottom: 8px;
    font-size: 16px;
    font-weight: 500;
    color: var(--overlay2)
}
.power-menu-popup .button .icon {
    font-size: 64px;
    padding-top: 32px;
    color: var(--surface2)
}
.power-menu-popup .button.cancel .icon {
    padding: 0;
    margin: 0;
}
.power-menu-popup .button.cancel .label {
    margin: 0;
}
.power-menu-popup .button.cancel {
    height: 32px;
    border-radius: 4px;
}
.power-menu-popup .button.hover .label,
.power-menu-popup .button.hover .icon {
    color: var(--green);
}
.uptime {
    font-size: 16px;
    margin-bottom: 10px;
    color: var(--overlay2);
    font-weight: 600;
}
.volume-widget .icon {
    color: var(--green);
    margin-right: 4px;
} 
.volume-slider {
    border: none;
}
.volume-slider::groove {
    background-color: var(--blue);
    border-radius: 2px;
    height: 4px;
    margin: 4px 0;
}
.volume-slider::handle{
    background-color: var(--blue);
    border: none;
    height: 16px;
    width: 10px;
    margin: -8px 0;
    border-radius: 2px;  
} 
.audio-menu {
    background-color:var(--crust); 
}
.audio-container .device {
    background-color:transparent;
    border: none;
    padding:6px 8px 6px 4px;
    margin: 2px 0;
    font-size: 12px;
    border-radius: 4px;
}
.audio-container .device.selected {
    background-color: rgba(255, 255, 255, 0.085);
}
.audio-container .device:hover {
    background-color: rgba(255, 255, 255, 0.06);
}
.weather-widget .icon {
    font-size: 18px;
    margin: 0 4px 1px 0;
    color: var(--green);
}
.weather-card {
    background-color:var(--crust);
}
 
.weather-card-today .label {
    font-size: 12px;
}
.weather-card-today .label.location {
    font-size: 24px;
    font-weight: 700;
}
.weather-card-today .label.arert {
    font-size: 12px;
    font-weight: 700;
    background-color: rgba(247, 199, 42, 0.05);
    border: 1px solid rgba(247, 209, 42, 0.1);
    color: rgba(196, 181, 162, 0.85);
    border-radius: 6px;
    padding: 5px 0;
}
.weather-card-day {
    border-radius: 8px;
    background-color: var(--crust);
}
.weather-card-day .label {
    font-size: 12px;
}
.taskbar-widget {
    padding: 0;
    margin: 0;
    border: none;
}
.taskbar-widget .app-icon {
    padding: 0 6px;
    border: none;
    margin: 0;
}
.home-widget {
    padding: 2px 4px 2px 0px;    
}
.home-widget .widget-container {
    background-color: var(--widget-background);
    border-radius: 8px;    
}
.home-widget .icon:hover {
    color: var(--text);
}
.home-menu {
    background-color: var(--crust);
}
.home-menu .menu-item {
    padding: 8px 48px 9px 16px;
    font-size: 12px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: var(--text);
    font-weight: 600;
}
.home-menu .menu-item:hover {
    background-color: rgba(157, 180, 141, 0.116);
    color: #fff;
}
.home-menu .separator {
    max-height: 1px;
    background-color: rgba(157, 180, 141, 0.116);
}
.media-widget {
	padding: 0;
	margin: 0;
    border-radius: 0;
}
.media-widget .label {
	color: var(--blue);
    padding: 0px;
	padding-left: 8px;
	font-size: 12px;
}
.media-widget .btn {
	color: var(--blue);
	padding:0 1px;
	margin: 0;
    font-size: 12px;
}
.media-widget .btn:hover {
	color: #babfd3;
}
.media-widget .btn.play {
	font-size: 17px;
}
.media-widget .btn.disabled:hover,
.media-widget .btn.disabled {
	color: var(--surface1);
}
.notification-widget .icon {
    color: var(--green);
}
.notification-widget .icon.new-notification {
    color: var(--red);
}
.notification-widget .label.new-notification {
    color: var(--red);
}
.cpu-widget .icon {
    color: var(--green);
    margin-right: 4px;
}
.memory-widget .icon {
    color: var(--green);
    margin-right: 4px;
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: true
      acrylic: false
    window_flags:
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
        "home",
        "komorebi_workspaces",
        "apps"
      ]
      center: [
        "clock"
      ]
      right: [
        "taskbar",
        "media",
        "cpu",
        "memory",
        "weather",
        "volume",
        "notifications",
        "power_menu"
        ]
widgets:
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 0
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 12
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 12
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb81\udf17</span>"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "~\\Downloads" }
      - { title: "Documents", path: "~\\Documents" }
      - { title: "Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      border_color: "None"
      round_corners_type: "small"
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 12
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{artist} - {title}"
      max_field_size:
        label: 48
        label_alt: 64
      show_thumbnail: false
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 150
      thumbnail_padding: 8
      thumbnail_corner_radius: 0
      icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 12
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span> {%H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      callbacks:
        on_left: "toggle_calendar"
      calendar: 
        blur: True
        round_corners: True
        round_corners_type: "small"
        border_color: "None"
        alignment: "center"
        direction: "down"
        distance: 6
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "\u23fc Offline"
      label_workspace_btn: "\uf444"
      label_workspace_active_btn: "\uf192"
      label_workspace_populated_btn: "\uf444"
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: false
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807"
      update_interval: 600
      hide_decimal: true
      location: "USA Los Angeles 90006"
      callbacks:
        on_left: "toggle_card"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd99"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\udb81\udd99"
        rainyDay: "\udb81\udd99"
        rainyNight: "\udb81\udd99"
        snowyIcyDay: "\udb81\udd99"
        snowyIcyNight: "\udb81\udd99"
        blizzard: "\udb81\udd99"
        default: "\udb81\udd99"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      weather_card: 
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "None"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 64
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
      audio_menu:
        blur: True
        round_corners: True
        round_corners_type: "small"
        border_color: "None"
        alignment: "right"
        direction: "down"
        distance: 6
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      label: "{data}"
      app_list:
        - { icon: "\uf422", launch: "search" }
        - { icon: "\ueb03", launch: "cmd /c Taskmgr" }
        - { icon: "\udb80\ude39",launch: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" }
        - { icon: "\uf489", launch: "wt" }
        - { icon: "\uf1ff",launch: "C:\\Users\\amn\\AppData\\Local\\Discord\\Update.exe --processStart Discord.exe" }
        - { icon: "\udb80\ude39",launch: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" }
        - { icon: "\udb82\ude1e",launch: "C:\\Users\\amn\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" }
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation:
        enabled: true
      icon_size: 16
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
```

### Readme

```markdown
Theme based on catppuccin color scheme, If you are going to use this theme, please change path for application widget and weather location/api. Theme support Komorebi.
```
