### ISSUE TITLE
[create-theme]: Aero Glass

### ISSUE THREAD

**Issue by manuelernestog** [amnweb/yasb-themes#60]
### Name

Aero Glass

### Description

Windows 11 macOS like theme

### Homepage

https://github.com/manuelernestog/aero-glass

### Image

https://i.ibb.co/059Lxcf/barra.png

### Theme Styles

```css
* {
	font-size: 13px;
	color: #ffffff;
	font-weight: 600;
	font-family: "Segoe UI","JetBrainsMono NFP";
	margin: 0;
	padding: 0;
}
.yasb-bar {
	padding: 0 8px;
	margin: 0;
    background-color: rgba(25, 25, 25, 0.7);
}
.widget {
	padding: 0 8px;
	margin: 0;
}
.widget .label {
	padding: 0px 2px 2px 2px;
}
.widget .label.alt {
	padding: 1px 8px 1px 8px;
}
.apps-widget {
    padding: 0;
}
.apps-widget .widget-container {
    background-color: transparent;
}
.apps-widget .label {
	font-size: 14px;
	padding:0px 2px 1px 2px;
	margin: 0 8px;
}
.apps-widget .label:hover {
	color: #fff;
}
.active-window-widget .icon {
    padding: 0 0 0 0;
}
/*POWER MENU WIDGET*/
.uptime {
	font-size: 14px;
	margin-bottom: 10px;
	color: #ffffff;
	font-weight: 600;
	font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
}
.power-menu-widget .label {
	font-size: 13px;
}
.power-menu-popup {
	background-color: rgba(24, 24, 37, 0.103);
	border-radius: 12px;
}
.power-menu-popup .button {
	padding: 0;
	width: 240px;
	height: 120px;
	border-radius: 8px;
	background-color: rgba(41, 42, 58, 0.497);
	font-family: "SegoeUI";
	color: white;
	border: 1px solid rgba(255, 255, 255, 0.1);
	margin: 8px;
}
.power-menu-popup .button.hover {
	background-color: rgba(41, 42, 58, 0.74);
	border: 1px solid rgb(55, 56, 75);
}
.power-menu-popup .button .label {
	margin-bottom: 8px;
	font-size: 16px;
	font-weight: 600;
	color: rgb(255, 255, 255);
	font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
}
.power-menu-popup .button .icon {
	font-size: 48px;
	padding-top: 8px;
}
.power-menu-popup .button.cancel .icon {
	color: rgba(243, 139, 168, 0.75);
}
.power-menu-popup .button.cancel .label {
	color: rgba(243, 139, 168, 0.95);
}
.power-menu-popup .button.shutdown .icon {
	color: rgba(137, 180, 250, 0.75);
}
.power-menu-popup .button.shutdown .label {
	color: rgba(137, 180, 250, 0.95);
}

/* ICONS */
.icon {
	font-size: 16px;
}
.volume-widget .icon {
	color: #89b4fa;
	margin: 1px 2px 0 0;
}
 
/* WEATHER WIDGET */
.weather-widget .icon {
	font-size: 16px;
	margin: 0 2px 1px 0;
}
.weather-widget .icon.sunnyDay {
	color: rgb(221, 210, 107);
}
.weather-widget .icon.clearNight {
	color: rgb(107, 189, 221);
	font-size: 22px;
	margin: 1px 2px 0px 0;
}

/* MEDIA WIDGET */
.media-widget {
	padding: 0;
	margin: 0 8px 0 0px;
	border-radius: 16px;
}
.media-widget .label {
	display: none;
	background-color: rgba(0, 0, 0, 0.0);
}
.media-widget .btn {
	color: #ffffff;
	padding: 0 0;
	margin: 0px 0;
    font-weight: 500;
	font-family: Segoe Fluent Icons;
	font-size: 1px;
}
.media-widget .btn:hover {
	color: #ffffff;
}
.media-widget .btn.play {
	font-size: 17px;
}
.media-widget .btn.disabled:hover,
.media-widget .btn.disabled {
	color: #7d8297;
	background-color: rgba(0, 0, 0, 0);
}

/* TASBAR WIDGET */
.taskbar-widget {
    padding: 0;
    margin: 0;
}
.taskbar-widget .app-icon {
    padding: 0 8px;
}
.win-button-widget .label {
    font-size: 18px;
}


/* SYSTEM TRY */

.systray {
    background: transparent;
    border: None;
    margin: 0;
}

.systray .unpinned-container {
    background: transparent;
    border-radius: 8px;
}

.systray .pinned-container {
    background: transparent;
}

.systray .button {
    border-radius: 4px;
    padding: 0 6px;
	margin: 4px;
}

.systray .button:hover {
    background: transparent;
}

.systray .button[dragging=true] {
    border-color: rgba(211, 211, 211, 0.705);
}

.systray .unpinned-visibility-btn {
    border-radius: 4px;
    height: 20px;
    width: 16px;
}

.systray .unpinned-visibility-btn:checked {
    background: transparent;
}

.systray .unpinned-visibility-btn:hover {
    border-radius: 4px;
}

/* HOME MENU */

.home-widget {
    padding: 2px 4px 2px 0px;    
}
.home-widget .widget-container {
    background-color: transparent;
}
.home-widget .icon:hover {
    color: white;
}
.home-menu {
    background-color: rgba(36, 36, 36, 0.604);
}
.home-menu .menu-item {
    padding: 8px 48px 9px 16px;
    font-size: 12px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color:white;
    font-weight: 600;
}
.home-menu .menu-item:hover {
    background-color: rgba(157, 180, 141, 0.116);
    color: #fff;
}
.home-menu .separator {
    max-height: 1px;
    background-color: rgba(157, 180, 141, 0.116);
}


/* NOTIFICATIONS */

.notification-widget {
    padding: 0 8px 0 8px;
}

.notification-widget .widget-container {
	margin: 0;
}

.notification-widget .icon {
    font-size: 15px;
}

/*AUDIO DROPDOWN*/

.audio-menu {
	background-color: rgba(36, 36, 36, 0.604);
	padding: 0 0 12px 0 
}
.audio-container .device {
	font-size: 13px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background-color: transparent;
    border: none;
    padding: 7px 4px 7px 4px;
    margin: 2px 0;
    border-radius: 4px;
	text-align: left;
}
.audio-container .device.selected {
    background-color: rgba(255, 255, 255, 0.085);
}
.audio-container .device:hover {
    background-color: rgba(255, 255, 255, 0.06);
}

/*CLOCK - CALENDAR WIDGET DROPDOWN*/

.calendar {
    background-color: rgba(36, 36, 36, 0.604);
	padding: 10px 25px 10px 0px;
}

.calendar .calendar-table,
.calendar .calendar-table::item {
    background-color: transparent;
    color: white;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    margin: 0;
    padding: 0;
    border: none;
    outline: none;  
}

.calendar .calendar-table::item:selected {
	background-color: #4cc2ff;
	color: #153647;
	border-radius: 12px;
}
.calendar .day-label {
    margin-top: 10px;
}
.calendar .day-label,
.calendar .month-label,
.calendar .date-label {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-size: 16px;
    color: #fff;
    font-weight: 700;
    min-width: 180px;
    max-width: 180px;
}
.calendar .month-label {
    font-weight: normal;
}
.calendar .date-label {
    font-size: 88px;
    font-weight: 900;
    color: rgb(255, 255, 255);
    margin-top: -20px;
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic reload-configuration"
bars:
  status-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true 
      acrylic: false 
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 30
    widgets:
      left:
        [
          "home",
          "active_window"
        ] 
      center: [
         "clock","weather"
        ]
      right:
        [
          "systray",
          "media",
          "volume",
          "vpn",
          "wifi",
          "battery",
          "settings",
          "notifications",
          "power_menu"
        ]
widgets:
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: "{title}"
      max_field_size:
        label: 20
        label_alt: 30
      show_thumbnail: false
      controls_only: true
      controls_left: true
      hide_empty: true
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\uf01d"
        pause: "\uf28c"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %d, %b %H:%M}"
      label_alt: "{%A %d %B %Y, %H:%M}"
      #locale: 'en_EN' # Langugae for date, you can set your own, example fr_FR
      timezones: [] #Looking up time zone info from registry
      #timezones: ["America/Montreal"]
      callbacks:
        on_right: "exec cmd.exe /c start ms-clock:"
      calendar: 
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: '3bf4cf9a7c3f40d6b31174128242807' # Get your free API key from https://www.weatherapi.com/
      update_interval: 600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      location: 'Havana, Cuba' # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      icons: 
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzard: "\uebaa"
        default: "\uebaa"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "{icon}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: 'normal'
        border_color: 'System'
        alignment: 'center'
        direction: 'down'
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 300 # Milisecond 
      button_row: 3 # Number of buttons in row, min 1 max 5
      buttons:
        lock: ["\uea75","Lock"]
        signout: ["\udb80\udf43","Sign out"]
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        hibernate: ["\uf28e","Hibernate"]
        cancel: ["\udb81\udf3a","Cancel"]
  settings:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - {icon: "\ue690", launch: "quick_settings"}
      container_padding: 
        top: 0
        left: 0
        bottom: 0
        right: 0
  vpn:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - {icon: "\udb81\udd82", launch: "wireguard.exe"}
      container_padding: 
        top: 0
        left: 0
        bottom: 0
        right: 0
  win_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\ue62a"
      label_alt: "\ue62a"
      class_name: "win-button-widget"
      callbacks:
        on_left: "exec start_menu"
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "\udb82\udea5"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "~\\Downloads" }
      - { title: "Documents", path: "~\\Documents" }
      - { title: "Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      border_color: "System"
      round_corners_type: "normal"
      container_padding:
        top: 0
        left: 6
        bottom: 0
        right: 12
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "{icon}"
      label_alt: "{icon} {percent}%"
      charging_options:
        icon_format: "{charging_icon}"
      callbacks:
        on_left: "exec quick_settings"
        on_right: "exec cmd.exe /c start ms-settings:powersleep"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "exec quick_settings"
        on_middle: "do_nothing"
        on_right: "exec cmd.exe /c start ms-settings:network"
      wifi_icons: [
        "\udb82\udd2e",  # Icon for 0% strength
        "\udb82\udd1f",  # Icon for 1-20% strength
        "\udb82\udd22",  # Icon for 21-40% strength
        "\udb82\udd25",  # Icon for 41-80% strength
        "\udb82\udd28"   # Icon for 81-100% strength
      ]
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\udb81\udeb6"
      label_expanded: "\udb82\ude03"
      label_position: "left" # Can be "left" or "right"
      icon_size: 15 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\udb80\udd78</span>"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "do_nothing"
```

### Readme

```markdown
A Windows 11 minimalist macOS like theme preserving windows aero vibes.
```
