### ISSUE TITLE
[create-theme]: sky-theme

### ISSUE THREAD

**Issue by sete22stey** [amnweb/yasb-themes#63]
### Name

Sky Theme

### Description

Thema with blue and yellow pastel colors

### Image

https://i.imgur.com/NOdTMGB.png

### Theme Styles

```css
:root {
    --red: #f393ae;
    --yellow: #f9e2af;
    --transparent: rgba(9, 35, 54, 0.62);
    --green: #a6e3a1;
    --blue: #89b4fa;
    --lavender: #b4befe;
    --text: #fff4bd;
    --pink: #f5c2e7;
    --mauve: #70C4BD;
    --sky: #89dceb;
    --overlay2: #9399b2;
    --surface2: #585b70;
    --surface1: #45475a;
    --base: #1e1e2e;
    --mantle: rgba(24, 24, 37, 0.5);
    --crust: rgba(17, 17, 27, 0.2);
    --main: #10151d;
    --widget-background: #bc8bf7;
}
QToolTip {
    padding: 6px;
    color: #cdd6f4;
    font-size: 12px;
    background-color: #1e1e2e;
    border: 0px solid #313244;
    border-radius: 6px;
}
* {
    font-size: 12px;
    color: var(--text);
    font-weight: 400;
    font-family: "JetBrainsMono NFP";
    margin: 0;
    padding: 0;
}
.yasb-bar {
    padding: 0 -2px;
    margin: 0;
    border-radius: 8px;
    margin-left: 9px;
    margin-right: 9px;
    margin-top: 6px;
}
.widget {
    padding: 0 2px;
    margin: 0;
}
.icon {
    font-size: 14px;
}
.widget .label {
    padding: 0px 2px;
}
.clock-widget .widget-container,
.volume-widget .widget-container,
.weather-widget .widget-container,
.media-widget .widget-container,
.notification-widget .widget-container,
.power-menu-widget .widget-container,
.memory-widget .widget-container,
.cpu-widget .widget-container,
.active-window-widget .widget-container,
.language-widget .widget-container,
.taskbar-widget .widget-container,
.wifi-widget .widget-container,
.komorebi-workspaces .widget-container {
    background-color: var(--transparent);
    margin: 0px 0 0px 0;
    border-radius: 6px;
}

/* WIFI Setting */
.wifi-widget .icon{
    color: var(--mauve) !important;
}

/* CPU MEMORY Setting */
.cpu-widget {
    padding-right: 0;
}
.memory-widget {
    padding-left: 0;
}
.cpu-widget .widget-container {
    border-bottom-right-radius: 0;
    border-top-right-radius: 0;
}
.memory-widget .widget-container {
    border-bottom-left-radius: 0;
    border-top-left-radius: 0;
}
.memory-widget .label {
    min-width: 34px;
    max-width: 34px;
}
.cpu-widget .label {
    min-width: 34px;
    max-width: 34px;
}
.cpu-widget .icon {
    color: var(--mauve);
    margin-right: 4px;
}
.memory-widget .icon {
    color: var(--mauve);
    margin-right: 4px;
}

/* WORKSPACE Setting */
.komorebi-workspaces .offline-status {
    color: var(--overlay2);
    padding: 0 4px;
    font-size: 12px;
    font-weight: 600;
}
.komorebi-workspaces .ws-btn {
    border: none;
    background-color: #9cd1dd;
    margin: 0px 4px;
    padding: 0;
    color: rgba(0, 0, 0, 0);
    border-radius: 5px;
    height: 10px;
    width: 10px;
}
.komorebi-workspaces .ws-btn:hover {
    background-color: #91b2e7;
}
.komorebi-workspaces .ws-btn.populated {
    background-color: var(--red);
}
.komorebi-workspaces .ws-btn.active {
    background-color: var(--mauve); 
    width: 36px;
    height: 10px;
    border-radius: 5px;
}


/*DISK WIDGET*/
.disk-widget {
    padding-right: 0px;
    padding-left: 12px;
}
/*DISK DROPDOWN*/
.disk-group {
    background-color: var(--mantle);    
}
.disk-group-row {
    min-width: 220px;
    max-width: 220px;
    max-height: 40px;
    margin: 0;
    padding: 0;
    border-radius: 6px;
    border: 1px solid rgba(128, 128, 128, 0);
}
.disk-group-row:hover {
    background-color:rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
}
.disk-group-label-bar{
    max-height: 8px;
    border:0px solid rgba(128, 128, 128, 0);
    background-color: rgba(148, 226, 213, 0.3);
    border-radius: 4px;
}
.disk-group-label-bar::chunk{
    background-color: rgba(148, 226, 213, 1);
    border-radius: 4px;
}
.disk-group-label {
    font-size: 13px;
}
.disk-group-label-size {
    font-size: 12px;
    color: rgba(205, 214, 244, 0.5);
}

/* APP Settings */
.apps-widget .label {
    font-size: 16px;
    padding: 0 1px;
}
.apps-widget .label:hover {
    color: var(--text);
}

/* CLOCK and CALENDAR Settings */
.clock-widget .icon {
    color: var(--mauve);
    margin-right: 4px;
}
.calendar {
    background-color: var(--crust)
}
.calendar .calendar-table,
.calendar .calendar-table::item {
    background-color: rgba(17, 17, 27, 0);
    color: rgba(162, 177, 196, 0.85);
    font-family: 'JetBrainsMono NFP', Tahoma, Geneva, Verdana, sans-serif;
    margin: 0;
    padding: 0;
    border: none;
    outline: none;  
}
.calendar .calendar-table::item:selected {
    color: var(--main);
    border-radius: 8px;
    background-color: var(--mauve);
}
.calendar .day-label {
    margin-top: 20px;
}
.calendar .day-label,
.calendar .month-label,
.calendar .date-label {
    font-family: 'JetBrainsMono NFP', Tahoma, Geneva, Verdana, sans-serif;
    font-size: 16px;
    color: var(--mauve);
    font-weight: 700;
    min-width: 180px;
    max-width: 180px;
}
.calendar .month-label {
    font-weight: normal;
}
.calendar .date-label {
    font-size: 88px;
    font-weight: 900;
    color: var(--mauve);
    margin-top: -20px;
}

/* POWER Settings */
.power-menu-widget .label {
    font-size: 14px;
}
.power-menu-popup {
    background-color: transparent
}
.power-menu-popup .button {
    padding: 0;
    width: 180px;
    height: 230px;
    border-radius: 8px;
    background-color: var(--crust);
    color: var(--text);
    border-left: 10px solid rgba(58, 59, 83, 0);
    border-right: 10px solid rgba(58, 59, 83, 0);
    border-top: 10px solid rgba(58, 59, 83, 0);
    border-bottom: 10px solid rgba(58, 59, 83, 0);
    margin: 0px;
}
.power-menu-popup .button.hover {
    background-color: var(--base);
    border-left: 10px solid var(--base);
    border-right: 10px solid var(--base);
    border-top: 10px solid var(--base);
    border-bottom: 10px solid var(--base);
}
.power-menu-popup .button .label {
    margin-bottom: 8px;
    font-size: 16px;
    font-weight: 500;
    color: var(--overlay2)
}
.power-menu-popup .button .icon {
    font-size: 64px;
    padding-top: 32px;
    color: var(--surface2)
}
.power-menu-popup .button.cancel .icon {
    padding: 0;
    margin: 0;
}
.power-menu-popup .button.cancel .label {
    margin: 0;
}
.power-menu-popup .button.cancel {
    height: 32px;
    border-radius: 4px;
}
.power-menu-popup .button.hover .label,
.power-menu-popup .button.hover .icon {
    color: var(--mauve);
}
.uptime {
    font-size: 16px;
    margin-bottom: 10px;
    color: var(--overlay2);
    font-weight: 600;
}

/* WHKD Settings */
.whkd-widget {
    padding: 0 6px 0 6px;
}
.whkd-widget .icon {
    font-size: 18px;
}
.whkd-popup .edit-config-button {
    background-color:#1743a1;
    color: #ffffff;
    padding: 4px 8px 6px 8px;
    font-size: 14px;
    font-weight: 600;
    border-radius: 4px;
    font-family: 'Segoe UI', sans-serif;
}
.whkd-popup .keybind-buttons-container {
    min-width: 240px;
}
.whkd-popup .keybind-button {
    background-color: #343538;
    color: white;
    padding: 4px 8px 6px 8px;
    font-size: 14px;
    font-weight: 600;
    border: 1px inset #4f5055;
    border-bottom: 2px inset #4f5055;
    border-radius: 4px;
    font-family: 'JetBrainsMono NFP';
}
.whkd-popup .keybind-button.special {
    background-color: #343538;
}
.whkd-popup .keybind-row:hover{
    background-color: rgba(136, 138, 155, 0.2);
    border-radius: 8px;
}
.whkd-popup .plus-separator {
    padding: 0 0px;
    border:none;
    font-size: 16px;
    font-weight: bold;
    background-color:transparent
}
.whkd-popup .filter-input {
    padding: 0 8px 2px 8px;
    font-size: 14px;
    font-family: 'Segoe UI', sans-serif;
    border: 1px solid #2e2e2e;
    border-radius: 4px;
    outline: none;
    color: white;
    background-color: #2e2e2e;
    min-height: 32px;
}
.whkd-popup .filter-input:focus {
    border: 1px solid #0078D4;
}
.whkd-popup .keybind-command {
    font-size: 14px;
}
.whkd-popup .keybind-header {
    font-size: 16px;
    font-weight: 600;
    color: white;
    padding: 8px 0;
    margin-top: 20px;
    background-color: rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 8px;
}

/* VOLUMEN Settings */
.volume-widget {
    padding-right: 0;
}
.volume-widget .widget-container{
    border-bottom-right-radius: 0;
    border-top-right-radius: 0;
}
.volume-widget .icon {
    color: var(--mauve);
    margin-right: 4px;
} 
.volume-slider {
    border: none;
}
.volume-slider::groove {
    background-color: var(--mauve);
    border-radius: 2px;
    height: 4px;
    margin: 4px 0;
}
.volume-slider::handle{
    background-color: var(--mauve);
    border: none;
    height: 16px;
    width: 10px;
    margin: -8px 0;
    border-radius: 2px;  
}

.audio-menu {
    background-color:var(--crust); 
}
.audio-container .device {
    background-color:transparent;
    border: none;
    padding:6px 8px 6px 4px;
    margin: 2px 0;
    font-size: 12px;
    border-radius: 4px;
}
.audio-container .device.selected {
    background-color: rgba(255, 255, 255, 0.085);
}
.audio-container .device:hover {
    background-color: rgba(255, 255, 255, 0.06);
}

/* LANGUAGE Settings */
.language-widget {
    padding-left: 0;
}
.language-widget .widget-container{
    border-bottom-left-radius: 0;
    border-top-left-radius: 0;
}
.language-widget .icon {
    color: var(--mauve);
    margin-right: 4px;
}

/* WEATHER Settings */
.weather-widget .icon {
    font-size: 18px;
    margin: 0 4px 1px 0;
    color: var(--mauve);
}
.weather-card {
    background-color:var(--crust);
}
 
.weather-card-today .label {
    font-size: 12px;
}
.weather-card-today .label.location {
    font-size: 24px;
    font-weight: 700;
}
.weather-card-today .label.arert {
    font-size: 12px;
    font-weight: 700;
    background-color: rgba(247, 199, 42, 0.05);
    border: 1px solid rgba(247, 209, 42, 0.1);
    color: rgba(196, 181, 162, 0.85);
    border-radius: 6px;
    padding: 5px 0;
}
.weather-card-day {
    border-radius: 8px;
    background-color: var(--crust);
}
.weather-card-day .label {
    font-size: 12px;
}

/* TASKBAR Settings */
.taskbar-widget {
    /* padding: 0; */
    /* margin: 0; */
    border: none;
}
.taskbar-widget .app-icon {
    padding: 0 5px;
    border: none;
    margin: 0;    
}
.taskbar-widget .app-icon.foreground{
    background-color: rgba(168, 168, 168, 0.45);
    border: 1px solid rgba(255, 255, 255, 0.12);
    border-radius: 6px;
}
.taskbar-widget {
    padding-left: 0;
}
.taskbar-widget .widget-container {
    border-bottom-left-radius: 0;
    border-top-left-radius: 0;
    /* padding-left: 6px; */
}

/* ACTIVE WINDOW Settings */
.active-window-widget .icon {
    padding: 0 9px;
}
.active-window-widget {
    padding-right: 0;
}
.active-window-widget .widget-container {
    padding: auto;
    border-bottom-right-radius: 0;
    border-top-right-radius: 0;
}

/* HOME Settings */
.home-widget {
    padding: 2px 4px 2px 0px;    
}
.home-widget .widget-container {
    background-color: var(--widget-background);
    border-radius: 8px;    
}
.home-widget .icon:hover {
    color: var(--text);
}
.home-menu {
    background-color: var(--crust);
}
.home-menu .menu-item {
    padding: 8px 48px 9px 16px;
    font-size: 12px;
    font-family: 'JetBrainsMono NFP', Tahoma, Geneva, Verdana, sans-serif;
    color: var(--text);
    font-weight: 600;
}
.home-menu .menu-item:hover {
    background-color: rgba(157, 180, 141, 0.116);
    color: #fff;
}
.home-menu .separator {
    max-height: 1px;
    background-color: rgba(157, 180, 141, 0.116);
}

/* MEDIA Settings */
.media-widget {
	padding: 0;
	margin: 0;
    border-radius: 0;
}
.media-widget .label {
	color: var(--text);
    padding: 0px;
	padding-left: 8px;
	font-size: 12px;
    max-width: 220px;
    min-width: 220px;
}
.media-widget .btn {
	color: var(--mauve);
	padding:0 1px;
	margin: 0;
    font-size: 12px;
}
.media-widget .btn:hover {
	color: #babfd3;
}
.media-widget .btn.play {
	font-size: 17px;
    max-width: 22px;
    min-width: 22px;
}
.media-widget .btn.disabled:hover,
.media-widget .btn.disabled {
	color: var(--surface1);
}

/* NOTIFICATION Settings */
.notification-widget .icon {
    color: var(--mauve);
}
.notification-widget .icon.new-notification {
    color: var(--mauve);
}
.notification-widget .label.new-notification {
    color: var(--mauve);
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["Mi Monitor"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: false 
      acrylic: true 
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      windows_app_bar: true
    dimensions:
      width: "75%"
      height: 32
    padding:
      top: 1
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
        # "home",
        "komorebi_workspaces",
        "disk",
        "apps",
        "whkd",
        "media",
        "cava"
      ]
      center: [
        "clock"
      ]
      right: [
        "active_window",
        "taskbar",
        "cpu",
        "memory",
        "weather",
        "volume",
        "language",
        "wifi"
        # "notifications",
        # "power_menu"
        ]
widgets:
  wifi:
      type: "yasb.wifi.WifiWidget"
      options:
        label: "<span>{wifi_icon}</span>"
        label_alt: "{wifi_name} {wifi_strength}%"
        update_interval: 5000
        callbacks:
          on_left: "exec cmd.exe /c start ms-settings:network"
          on_middle: "do_nothing"
          on_right: "toggle_label"
        container_padding:
          top: 0
          left: 8
          bottom: 0
          right: 8
        wifi_icons: [
          "\udb82\udd2e",  # Icon for 0% strength
          "\udb82\udd1f",  # Icon for 1-20% strength
          "\udb82\udd22",  # Icon for 21-40% strength
          "\udb82\udd25",  # Icon for 41-80% strength
          "\udb82\udd28"   # Icon for 81-100% strength
        ]
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\udb81\udeb6"
      label_expanded: "\udb82\ude03"
      label_position: "left" # Can be "left" or "right"
      icon_size: 15 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      # show_unpinned_button: true
      # show_network: true 
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "<span>\uf11c</span>{lang[country_code]}"
      update_interval: 5
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 8
  whkd:
    type: "yasb.whkd.WhkdWidget"
    options:
      label: "<span>\uf11c</span>"
      special_keys:
        - key: "lwin"
          key_replace: "\ue70f"
        - key: "left"
          key_replace: "\u2190"
        - key: "right"
          key_replace: "\u2192"
        - key: "up"
          key_replace: "\u2191"
        - key: "down"
          key_replace: "\u2193"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 8
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "<span>\uf473</span>"
        label_alt: "<span>\uf473</span>"
        update_interval: 60
        group_label:
          volume_labels: ["C", "D", "E", "F"]
          show_label_name: false
          blur: True
          round_corners: True
          round_corners_type: "small"
          border_color: "System"
          alignment: "left"
          direction: "down"
          distance: 6
        callbacks:
          on_left: "toggle_group"
          on_middle: "toggle_label"
          on_right: "exec explorer C:\\" # Open disk C in file explorer
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      min_bar_height: 0
      gradient: 1
      reverse: 0
      foreground: "#89b4fa"
      gradient_color_1: '#70C4BD'
      gradient_color_2: '#fff4bd'
      gradient_color_3: '#f393ae'
      bars_number: 10
      bar_spacing: 2
      bar_width: 4
      sleep_timer: 2
      hide_empty: true
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 32
      max_length_ellipsis: "..."
      monitor_exclusive: false 
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 0
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 6
        bottom: 0
        right: 8
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 12
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb81\udf17</span>"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "~\\Downloads" }
      - { title: "Documents", path: "~\\Documents" }
      - { title: "Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      border_color: "None"
      round_corners_type: "small"
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 12
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{artist} - {title}"
      label_alt: "{title}"
      max_field_size:
        label: 48
        label_alt: 64
      show_thumbnail: false
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 150
      thumbnail_padding: 8
      thumbnail_corner_radius: 0
      icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 12
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span> {%a, %d/%m/%y %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      callbacks:
        on_left: "toggle_calendar"
      calendar: 
        blur: True
        round_corners: True
        round_corners_type: "small"
        border_color: "None"
        alignment: "center"
        direction: "down"
        distance: 6
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "\u23fc Offline"
      label_workspace_btn: "\uf444"
      label_workspace_active_btn: "\uf192"
      label_workspace_populated_btn: "\uf444"
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: false
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "xxxxxxx"
      update_interval: 600
      hide_decimal: true
      location: "xxxxx"
      callbacks:
        on_left: "toggle_card"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\U0001F319"
        cloudyDay: "\U00002601"
        cloudyNight: "\U0001F315"
        rainyDay: "\U0001F327"
        rainyNight: "\U0001F327\U0001F311"
        snowyIcyDay: "\U00002744"
        snowyIcyNight: "\U0001F328"
        blizzard: "\U0001F32C"
        # default: "\udb81\udd99"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      weather_card: 
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "None"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 64
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
      audio_menu:
        blur: True
        round_corners: True
        round_corners_type: "small"
        border_color: "None"
        alignment: "right"
        direction: "down"
        distance: 6
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding:
        top: 0
        left: 4
        bottom: 0
        right: 0
      label: "{data}"
      app_list:
        # - { icon: "\uf422", launch: "search" }
        - { icon: "\ueb03", launch: "cmd /c Taskmgr" }
        - { icon: "\uf268",launch: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" }
        - { icon: "\uf489", launch: "wt" }
        # - { icon: "\uf1ff",launch: "Discord.exe" }
        - { icon: "\udb82\ude1e",launch: "Code.exe" }
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation:
        enabled: true
      icon_size: 16
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
```

### Readme

```markdown
If you are going to use this theme, please change path for application widget and weather location/api and install cava. Theme support Komorebi.
```
