### ISSUE TITLE
[create-theme]: Catppuccin Mocha

### ISSUE THREAD

**Issue by amnweb** [amnweb/yasb-themes#7]
### Name

Catppuccin Mocha

### Description

Soothing pastel theme for YASB.

### Homepage

https://github.com/amnweb/yasb

### Image

https://i.imgur.com/BaAQHWI.png

### Theme Styles

```css
* {
	font-size: 12px;
	color: #cdd6f4;
	font-weight: 500;
	font-family: "JetBrainsMono NFP";
	margin: 0;
	padding: 0;
}
.yasb-bar {
	padding: 0 8px;
	margin: 0;
    background-color: #1e1e2e;
    border-radius: 12px;
}
.widget {
	padding: 0 10px;
	margin: 0;
}
.widget .label {
	padding: 2px 2px 1px 2px;
 
}
.widget .label.alt {
	padding: 1px 8px 1px 8px;
}
 .clock-widget .label {
    padding-left:8px;
}
.komorebi-workspaces .ws-btn {
	font-size: 18px;
    background-color: transparent;
	padding: 0 2px 0 2px;
	color: #95a0ad;
}

.komorebi-workspaces .ws-btn.populated {
	color: #74c7ec;
}
.komorebi-workspaces .ws-btn:hover,
.komorebi-workspaces .ws-btn.populated:hover,
.komorebi-workspaces .ws-btn.active {
	color: #89b4fa;
}
/*POWER MENU WIDGET*/
/* Uptime text */
.uptime {
	font-size: 14px;
	margin-bottom: 10px;
	color: rgba(191, 202, 219, 0.726);
	font-weight: 600;
	font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
}
.power-menu-widget .label {
	color: #eba0ac;
	font-size: 16px;
}
.power-menu-popup .button {
	padding: 0;
	width: 160px;
	height: 240px;
	border-radius: 4px;
	background-color: rgba(41, 42, 58, 0.75);
	font-family: "SegoeUI";
	color: white;
	border: 4px solid rgba(255, 255, 255, 0);
 
}
.power-menu-popup .button.hover {
	background-color: rgb(55, 56, 75);
	border: 4px solid rgb(55, 56, 75);
}
.power-menu-popup .button .label {
	margin-bottom: 8px;
	font-size: 16px;
	font-weight: 600;
	color: rgba(255, 255, 255, 0.6);
	font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
}
.power-menu-popup .button .icon {
	font-size: 64px;
	padding-top: 54px;
	color: rgba(255, 255, 255, 0.25);
}
.power-menu-popup .button.cancel .icon {
	color: rgba(243, 139, 168, 0.55);
}
.power-menu-popup .button.cancel .label {
	color: rgba(243, 139, 168, 0.95);
}
 

/* ICONS */
.icon {
	font-size: 16px;
}
.volume-widget .icon {
	color: #89b4fa;
	margin: 1px 2px 0 0;
} 
.start-menu .icon {
    font-size: 18px;
	color: #89b4fa
}
.clock-widget .icon {
	color: #cba6f7;
    font-size: 14px;
}
/* WEATHER WIDGET */
.weather-widget .icon {
	font-size: 16px;
	margin: 0 2px 0px 0;
}
.weather-widget .icon.sunnyDay {
	color: rgb(221, 210, 107);
}
.weather-widget .icon.clearNight {
	color: rgb(107, 189, 221);
	font-size: 18px;
	margin: -1px 2px 0px 0;
}
.weather-widget .icon.rainyNight {
    font-size: 16px;
}
.weather-widget .icon.cloudyDay {
    font-size: 18px;
    color: rgb(221, 210, 107);
}
.weather-widget .icon.rainyDay {
    color: rgb(245, 224, 220)
} 
.media-widget {
	padding: 0;
	margin: 0;
}
.media-widget .label {
	color: #b4befe;
    padding: 0px;
	padding-right: 4px;
}
 /* Hide media widget buttons */
.media-widget .btn {
	padding: 0;
	margin: 0 -6px;
    padding-left: 4px;
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false
# This komorebi setting will be used for tray context menu.
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"

bars:
  status-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark: false
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 34
    padding:
      top: 8
      left: 8
      bottom: 4
      right: 8
    widgets:
      left:
        [
          "custom_button",
          "media"
        ]
      center: [
         "komorebi_workspaces"
        ]
      right:
        [
          "weather",
          "volume",
          "clock",
          "power_menu"
        ]
widgets:

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\uf001</span> {title}"
      label_alt: "<span>\uf001</span> {artist}"
      max_field_size:
        label: 30
        label_alt: 24
      show_thumbnail: false
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 250
      thumbnail_padding: 8
      thumbnail_corner_radius: 0
      icons:
        prev_track: ""
        next_track: ""
        play: ""
        pause: ""

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf4ab</span> {%H:%M}"
      label_alt: "<span>\uf4ab</span> {%A, %d %B %Y %H:%M}"
      timezones: [] #Looking up time zone info from registry
 

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "Komorebi Offline"
        label_workspace_btn: "\udb85\udcfc"
        label_workspace_active_btn: "\udb85\udcfb"
        label_default_name: "{index}"
        label_zero_index: false
        hide_empty_workspaces: false
        hide_if_offline: true

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts: ['bsp', 'columns', 'rows', 'grid', 'vertical_stack', 'horizontal_stack', 'ultrawide_vertical_stack','right_main_vertical_stack']
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        vertical_stack: "V-STACK"
        horizontal_stack: "H-STACK"
        ultrawide_vertical_stack: "W-STACK"
        right_main_vertical_stack: "RMV-STACK"
        monocle: "MONOCLE"
        maximised: "MAX"
        floating: "FLOATING"
        paused: "PAUSED"
      callbacks:
        on_left: 'next_layout'
        on_middle: 'toggle_monocle'
        on_right: 'prev_layout'

  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp_c}"
      label_alt: "{location}: Min {min_temp_c}, Max {max_temp_c}, Humidity {humidity}"
      api_key: '3bf4cf9a7c3f40d6b31174128242807'
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: 'Cairo'
      callbacks:
        on_left: "toggle_label"
      icons: 
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzard: "\uebaa"
        default: "\uebaa"
        # https://www.weatherapi.com/docs/
        # Usage {temp_c}, {min_temp_c}, {max_temp_c}, {temp_f}, {min_temp_f}, {max_temp_f}, {location}, {humidity}, {icon}, {conditions}


  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"

 
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 250 # Milisecond 
      button_row: 5 # Number of buttons in row, min 1 max 5
      buttons:
        signout: ["\udb80\udf43","Sign out"]
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        hibernate: ["\uf28e","Hibernate"]
        cancel: ["\udb81\udf3a","Cancel"]
 

  custom_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\uf40e</span>"
      label_alt: "<span>\uf40e</span>"
      class_name: "start-menu"
      callbacks:
        on_left: "exec start_menu"
```

### Readme

```markdown
# Catppuccino Mocha Theme for YASB

![Catppuccino Mocha Theme](https://i.imgur.com/8ZoONkB.png)

## Description

The Catppuccino Mocha Theme is a soothing pastel theme created for YASB.
```
