### ISSUE TITLE
[create-theme]: Comfyppuccin

### ISSUE THREAD

**Issue by CosmicCatOS** [amnweb/yasb-themes#70]
### Name

Comfyppuccin

### Description

A catppuccin theme that feels comfy!

### Image

https://imgur.com/KZQkQX0

### Theme Styles

```css
/* -------------------------------------------------------------------------------------------------- */
/* Variables                                                                                         */
/* -------------------------------------------------------------------------------------------------- */

:root {
	--rosewater: rgb(245, 224, 220);
	--flamingo: rgb(242, 205, 205);
	--pink: rgb(245, 194, 231);
	--mauve: rgb(203, 166, 247);
	--red: rgb(243, 139, 168);
	--maroon: rgb(235, 160, 172);
	--peach: rgb(250, 179, 135);
	--yellow: rgb(249, 226, 175);
	--green: rgb(166, 227, 161);
	--teal: rgb(148, 226, 213);
	--sky: rgb(137, 220, 235);
	--sapphire: rgb(116, 199, 236);
	--blue: rgb(137, 180, 250);
	--lavender: rgb(180, 190, 254);
	--text: rgb(205, 214, 244);
	--subtext1: rgb(186, 194, 222);
	--subtext0: rgb(166, 173, 200);
	--overlay2: rgb(147, 153, 178);
	--overlay1: rgb(127, 132, 156);
	--overlay0: rgb(108, 112, 134);
	--surface2: rgb(88, 91, 112);
	--surface1: rgb(69, 71, 90);
	--surface0: rgb(40, 41, 54);
	--base: rgb(30, 30, 46);
	--mantle: rgb(24, 24, 37);
	--crust: rgb(17, 17, 27);
}

/* -------------------------------------------------------------------------------------------------- */
/* 1. Layout and Containers                                                                           */
/* -------------------------------------------------------------------------------------------------- */

* {
	font-size: 12px;
	color: #cdd6f4;
	font-weight: 500;
	font-family: "SF Pro Rounded", "JetBrainsMono NFP";
	margin: 0;
	padding: 0;
}
.yasb-bar {
	padding: 0 8px;
	margin: 0;
	background-color: #1e1e2e;
	border-radius: 8px;
}

.widget {
	padding: 0 10px;
	margin: 0;
}

.widget .label {
	padding: 2px 2px 1px 2px;

}

.widget .label.alt {
	padding: 1px 8px 1px 8px;
}

/* -------------------------------------------------------------------------------------------------- */
/* 2. Widget Containers                                                                               */
/* -------------------------------------------------------------------------------------------------- */

.glazewm-workspaces .widget-container {
	background-color: var(--mantle);
	margin: 4px 0px 4px 0px;
	border-radius: 8px;
}

/* -------------------------------------------------------------------------------------------------- */
/* 3. Widgets                                                                                         */
/* -------------------------------------------------------------------------------------------------- */

/***-------------------------------      • Windows Desktops •      --------------------------------***/

.glazewm-workspaces {
	margin: 0;
}

.glazewm-workspaces .ws-btn {
	background-color: var(--surface1);
	width: 10px;
	height: 10px;
	border-radius: 4px;
	color: rgba(0, 0, 0, 0);
	margin-right: 5px;
	margin-left: 5px;
}

.glazewm-workspaces .ws-btn.active {
	color: rgba(0, 0, 0, 0);
	background-color: var(--mauve);
	margin-right: 5px;
	margin-left: 5px;
	width: 28px;
	height: 10px;
}

.glazewm-workspaces .ws-btn.populated {
	color: var(--surface1);
}

.glazewm-workspaces .ws-btn.empty {
	color: #7D8B9D;
}

.glazewm-workspaces .ws-btn:hover,
.glazewm-workspaces .ws-btn.populated:hover,
.glazewm-workspaces .ws-btn.empty:hover {
	background-color: var(--surface2);
}

/***---------------------------------      • Audio Widget •      ----------------------------------***/

.audio-menu {
	background-color: var(--mantle);
}
.audio-container .device {
	background-color: var(--base);
	border: none;
	padding: 6px 8px 6px 4px;
	margin: 2px 0;
	font-size: 12px;
	border-radius: 4px;
	font-family: "SF Pro Text";
}
.audio-container .device.selected {
	background-color: var(--crust);
} 
.audio-container .device:hover {
	background-color: var(--base);
}

.volume-slider::groove {
	color: transparent;
}
.volume-slider::handle {
	background-color: transparent;
}
.audio-menu {
	background-color: rgba(17, 17, 27, 0.4);
}

/***------------------------------      • Notification Widget •      -------------------------------***/

.notification-widget {
	padding: 0 4px 0 4px;
}

.notification-widget .icon {
	font-size: 12px;
	padding-right: 5px;
	padding-left: 2px;
}
.notification-widget .icon.new-notification {
	color: var(--mauve);
}
.notification-widget .label.new-notification {
	color: var(--mauve);
}

/***-------------------------------      • Power Menu Widget •      --------------------------------***/

.power-menu-popup {
	background: var(--crust);
	border-radius: 8px;
}

.power-menu-widget .label {
	color: #eba0ac;
	font-size: 16px;
	font-family: "JetBrainsMono NF";
}
.power-menu-popup .button {
	padding: 0px;
	margin: 5px;
	width: 250px;
	height: 175px;
	border-radius: 8px;
	background-color: var(--base);
	font-family: "SF Pro Rounded";
	color: white;

}
.power-menu-popup .button.hover {
	background-color: var(--base);
}
.power-menu-popup .button .label {
	margin-bottom: 0px;
	font-size: 16px;
	font-weight: 600;
	color: var(--text);
	font-family: "SF Pro Rounded";
}
.power-menu-popup .button .icon {
	font-size: 55px;
	padding-top: 25px;
	padding-right: 10px;
	color: var(--text);
}
.power-menu-popup .button.cancel .icon {
	color: var(--red);
}
.power-menu-popup .button.cancel .label {
	color: var(--red);
}

.clock-widget {
	padding: 0 4px 0 4px;
}

/* --------------------------------------------------------------------------------------------------- */
/* 6. Icons & Typography                                                                               */
/* --------------------------------------------------------------------------------------------------- */

.icon {
	font-size: 16px;
}
.volume-widget .icon {
	color: var(--mauve);
	margin: 1px 2px 0 0;
}
.start-menu .icon {
	font-size: 18px;
	color: #89b4fa
}
.clock-widget .icon {
	color: #cba6f7;
	font-size: 14px;
	margin-right: 7px;
}

/***---------------------------------      • Weather Icons •      ----------------------------------***/

.weather-widget .icon.cloudyDay {
	color: var(--mauve);
}
.weather-widget .icon.cloudyNight {
	color: var(--mauve);
}
.weather-widget .icon.rainyDay {
	color: var(--mauve);
}
.weather-widget .icon.rainyNight {
	color: var(--mauve);
}
.weather-widget .icon.snowyIcyDay {
	color: var(--mauve);
}
.weather-widget .icon.snowyIcyNight {
	color: var(--mauve);
}
.weather-widget .icon.blizzard {
	color: var(--mauve);
}
.weather-widget .icon.default {
	color: var(--mauve);
}

/***----------------------------------      • Weather Card •      -----------------------------------***/

.weather-card {
	background-color: var(--mantle);
}
.weather-card-today {
	border-radius: 8px;
	background-color: var(--base);
	color: var(--text);
}
.weather-card-today .label {
	font-size: 12px;
	font-family: "SF Pro Rounded";
}
.weather-card-today .label.location {
	font-size: 24px;
	font-weight: 800;
	font-family: "SF Pro Rounded";
}
.weather-card-today .label.alert {
	font-size: 12px;
	font-weight: 700;
	background-color: rgba(247, 199, 42, 0.05);
	border: 1px solid rgba(247, 209, 42, 0.1);
	color: rgba(196, 181, 162, 0.85);
	border-radius: 6px;
	padding: 5px 0;
}
.weather-card-day {
	border-radius: 8px;
	background-color: var(--base);
}
.weather-card-day .label {
	font-size: 12px;
	font-family: "SF Pro Rounded";
}

/* Media Widget */

.media-widget {
	padding: 0;
	margin-left: 0;
}
.media-widget .label {
	color: var(--lavender);
    padding-left: 5px;
}

/* Hide media widget buttons */

.media-widget .btn {
	max-width: 0;
}

.calendar {
	background-color: var(--mantle);
}
.calendar .calendar-table,
.calendar .calendar-table::item {
	background-color: rgba(17, 17, 27, 0);
	color: var(--overlay1);
	font-family: "SF Pro Rounded";
	margin: 0;
	padding: 0;
	border: none;
	outline: none;
}

.calendar .calendar-table::item:selected {
	color: #4c4f69;
	background: var(--mauve);
	border-radius: 8px;
}
.calendar .day-label {
	margin-top: 20px;
}
.calendar .day-label,
.calendar .month-label,
.calendar .date-label {
	font-family: "SF Pro Rounded";
	font-size: 16px;
	color: var(--text);
	font-weight: 700;
	min-width: 180px;
	max-width: 180px;
}
.calendar .month-label {
	font-weight: normal;
	padding-bottom: 12px;
}
.calendar .date-label {
	font-size: 88px;
	font-weight: 900;
	color: var(--text);
	margin-top: -20px;
}

.home-menu {
	background-color: var(--mantle);
	border-radius: 8px;
	padding: 0;
	margin-left: 0px;
}
.home-menu .menu-item {
	padding: 8px 48px 8px 12px;
	font-size: 13px;
	font-family: "SF Pro Rounded";
	font-weight: 600;
}
.home-menu .menu-item:hover {
	background-color: #cba6f4;
	color: #181825;
	margin: 4px 6px;
	border-radius: 4px;
}
.home-menu .separator {
	max-height: 1px;
	background-color: #45475a;
	margin: 0 8px;
}

.wallpapers-gallery-window {
	background-color: var(--mantle);
	border: 2px;
	margin: 0;
}

.battery-widget .widget-container .label.status-low {
	color: var(--red);
	background: rgba(243, 139, 168, 0.245);
	margin: 4px 0px 4px 0px;
	padding: 0 6px 0 6px;
	border-radius: 8px;
}
.battery-widget .widget-container .label.status-medium {
	color: var(--yellow);
	background: rgba(249, 226, 175, 0.25);
	margin: 4px 0px 4px 0px;
	padding: 0 6px 0 6px;
	border-radius: 8px;
}
.battery-widget .widget-container .label.status-high {
	color: var(--teal);
	background: rgba(148, 226, 213, 0.25);
	margin: 4px 0px 4px 0px;
	padding: 0 6px 0 6px;
	border-radius: 8px;
}
.battery-widget .widget-container .label.status-full {
	color: var(--green);
	background: rgba(166, 227, 161, 0.25);
	margin: 4px 0px 4px 0px;
	padding: 0 6px 0 6px;
	border-radius: 8px;
}
.battery-widget .widget-container .label.status-charging {
	color: var(--blue);
	background: rgba(137, 180, 250, 0.25);
	margin: 4px 0px 4px 0px;
	padding: 0 6px 0 6px;
	border-radius: 8px;
}

.battery-widget .widget-container .icon.status-low {
	color: var(--red);
}
.battery-widget .widget-container .icon.status-medium {
	color: var(--yellow);
}
.battery-widget .widget-container .icon.status-high {
	color: var(--teal);
	padding-right: 4px;
}
.battery-widget .widget-container .icon.status-full {
	color: var(--green);
	padding-right: 4px;
}
.battery-widget .widget-container .icon.status-charging {
	color: var(--blue);
}

.volume-slider {
	border: none;
}
.volume-slider::groove {
}
.volume-slider::handle {
}
.audio-menu {
	background-color: rgba(17, 17, 27, 0.4);
}
.audio-container .device {
	background-color: transparent;
	border: none;
	padding: 6px 8px 6px 4px;
	margin: 2px 0;
	font-size: 12px;
	border-radius: 4px;
}
.audio-container .device.selected {
	background-color: rgba(255, 255, 255, 0.085);
}
.audio-container .device:hover {
	background-color: rgba(255, 255, 255, 0.06);
}

.wallpapers-gallery-buttons {
	background-color: var(--base);
	color: var(--text);
	border: none;
	font-size: 16px;
	padding: 8px 0px;
	border-radius: 8px;
	margin: 8px 8px 8px 8px;
	width: 600px;
	font-family: "SF Pro Rounded";
}

.wallpapers-widget {
    padding: 0 6px 0 6px;
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false

komorebi:
  start_command: "komorebic start"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start"

bars:
  status-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 800
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 35
    padding:
      top: 9
      left: 9
      bottom: 9
      right: 9
    widgets:
      left:
        [
          "home",
          "wallpaper",
          "media",
          "notifications",
        ]
      center:
        [
          "glazewm_workspaces",
          "active_window",
        ]
      right:
        [
          "weather",
          "volume",
          "clock",
          "battery",
          "power_menu"
        ]
widgets:
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
      container_padding:
        top: 0
        left: 6
        bottom: 0
        right: 6
  wallpaper:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\uf03e</span>"
      image_path: "C:\\Users\\tundr\\Downloads\\Wallpapers\\Catppuccin"
      change_automatically: false # Automatically change wallpaper
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 250
        image_per_page: 4
        show_buttons: true
        orientation: "portrait"
        image_spacing: 15
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 8
        enable_cache: true
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      gradient: 1
      reverse: 0
      foreground: "#cba6f7"
      gradient_color_1: '#cba6f7'
      gradient_color_2: '#B4BEFE'
      bars_number: 8
      bar_spacing: 2
      bar_width: 5
      noise_reduction: 0.25
      sleep_timer: 2
      hide_empty: true
      container_padding:
        top: 0
        left: 4
        bottom: 0
        right: 4
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
        - { title: "Home", path: "~" }
        - { title: "Downloads", path: "C:\\Users\\elrond\\Downloads"}
        - { title: "Documents", path: "C:\\Users\\elrond\\Documents"}
        - { title: "Pictures", path: "C:\\Users\\elrond\\Pictures"}
        - { title: "Videos", path: "C:\\Users\\elrond\\Videos"}
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: ""
      distance: 10
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\udb80\udf87</span> {title}"
      label_alt: "<span>\udb80\udf87</span> {artist}"
      hide_empty: false
      max_field_size:
        label: 20
        label_alt: 20
      show_thumbnail: false
      controls_only: false
      controls_left: true
      thumbnail_alpha: 50
      thumbnail_padding: 0
      thumbnail_corner_radius: 8
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\ue769</span>{%I:%M %p}"
      label_alt: "{%a, %d %b %H:%M:%S}"
      timezones: [] #Looking up time zone info from registry
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: {conditions}, Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: '3bf4cf9a7c3f40d6b31174128242807'
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: "Hillsboro, Oregon"
      units: "imperial"
      callbacks:
        on_left: "toggle_card"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\ue3c2"
        cloudyDay: "\ue21d"
        cloudyNight: "\ue226"
        rainyDay: "\ue371"
        rainyNight: "\ue371"
        snowyIcyDay: "\udb81\udf17"
        snowyIcyNight: "\udb81\udf17"
        blizzard: "\udb81\udd99"
        default: "\udb81\udd99"
      weather_card:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "#45475a"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 48
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" 
        - "\uf026"
        - "\uf027" 
        - "\uf027"  
        - "\uf028"
      audio_menu:
        blur: True
        round_corners: True
        round_corners_type: 'normal'
        border_color: '#45475a'
        alignment: 'right'
        direction: 'down'
        distance: 6
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 250
      button_row: 3
      buttons:
        signout: ["\udb80\udf43","Sign out"]
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        sleep: ["\udb82\udd04","Sleep"]
        lock: ["\uf023","Lock"]
        cancel: ["\udb81\udf3a","Cancel"]
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: ""
      label_no_window: ""
      label_icon: true
      label_icon_size: 12
      max_length: 20
      max_length_ellipsis: "..."
      monitor_exclusive: true
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "{icon} {percent}%"
      label_alt: "{icon} {percent}% | time: {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"
      status_icons:
        icon_charging: "\udb80\udc84"
        icon_critical: "\udb80\udc7a"
        icon_low: "\udb80\udc7b"
        icon_medium: "\udb80\udc7e"
        icon_high: "\udb80\udc80"
        icon_full: "\udb80\udc79"
      status_thresholds:
        critical: 10
        low: 45
        medium: 75
        high: 85
        full: 100
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\uf03e</span>"
      image_path: "C:\\Users\\tundr\\Downloads\\Wallpapers\\Catppuccin" # Example path to folder with images
      change_automatically: false # Automatically change wallpaper
      update_interval: 60 # If change_automatically is true, update interval in seconds
      gallery:
        enabled: true
        blur: false
        image_width: 200
        image_per_page: 8
        show_buttons: true
        orientation: "portrait"
        image_spacing: 8
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 20
        enable_cache: true
      icons:
        recording: "\ueba7"
        stopped: "\ueba5"
        paused: "\ueba7"
      hide_when_not_recording: true
      blinking_icon: true
```

### Readme

```markdown
This theme has the Mocha flavor with the mauve accent, you may customize this theme to your liking.
```
