### ISSUE TITLE
[create-theme]: Fluent Design

### ISSUE THREAD

**Issue by ashwinjadhav818** [amnweb/yasb-themes#73]
### Name

Fluent Design

### Description

Theme inspired by Windows Fluent Design System

### Homepage

https://github.com/ashwinjadhav818/dotfiles

### Image

https://iili.io/356XFxp.png

### Theme Styles

```css
/* --- Root Variables (Colors) --- */
:root {
    /* --- Mica Inspired Color Variables --- */
    --background-color: rgba(30, 34, 40, 0.7);
    --foreground-color: rgb(237, 238, 240);
    --accent-color: #0078d4;
    --border-color: rgb(53, 59, 69);
    --icon-color: rgb(169, 174, 184);
    --icon-hover: rgba(169, 174, 184, 0.8);
    --hover-color: rgba(93, 114, 135, 0.12);
    --active-color: rgb(93, 114, 135);
    --inactive-color: rgba(93, 114, 135, 0.5);
}

/* --- Base Styles --- */
* {
    font-size: 12px;
    color: var(--foreground-color);
    font-weight: 600;
    font-family: "SegoeUI Nerd Font";
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

/* --- Yasb Bar Itself --- */
.yasb-bar {
    background-color: var(--background-color);
    border-radius: 8px;
    border: 1px solid var(--border-color);
}

/* --- Individual Widgets --- */
.widget {
    padding: 0 12px;
    margin: 0;
}

.container-right .widget .icon:hover {
    color: var(--icon-hover);
}

/* --- Icons --- */
.icon {
    font-size: 14px;
    color: var(--icon-color);
}

/* --- Widget Labels --- */
.widget .label {
    padding: 0px 2px;
}

/* --- Apps Widget Specific --- */
.apps-widget {
    padding: 0 4p 0 2px;
}

.apps-widget .widget-container .label {
    font-size: 12px;
}

/* --- Komorebi Active Layout --- */
.komorebi-active-layout {
    padding: 0 4px;
}

.komorebi-active-layout .label {
    font-weight: 600;
    padding-bottom: 2px;
}

/* --- Workspace and Layout Containers --- */
.apps-widget .widget-container,
.komorebi-workspaces .widget-container,
.komorebi-active-layout .widget-container,
.glazewm-workspaces .widget-container,
.glazewm-tiling-direction .widget-container {
    background-color: var(--background-color);
    border-radius: 12px;
    margin: 4px 0;
    border: 1px solid var(--border-color);
}

/* --- Komorebi & GlazeWM Workspaces --- */
.komorebi-workspaces,
.glazewm-workspaces {
    padding: 0;
}

.komorebi-workspaces .offline-status,
.glazewm-workspaces .offline-status {
    color: var(--foreground-color);
    font-size: 12px;
    padding: 0 4px;
    font-weight: 600;
}

.komorebi-workspaces .ws-btn,
.glazewm-workspaces .ws-btn {
    color: transparent;
    width: 10px;
    height: 10px;
    background-color: var(--active-color);
    border-radius: 5px;
    margin: 0 2px;
    font-size: 1px;
}

.komorebi-workspaces .ws-btn:hover,
.glazewm-workspaces .ws-btn:hover {
    color: var(--accent-color);
    background-color: var(--hover-color);
}

.komorebi-workspaces .ws-btn.populated,
.glazewm-workspaces .ws-btn.populated {
    width: 10px;
    height: 10px;
    background-color: var(--active-color);
    border-radius: 5px;
    margin: 0 2px;
    font-size: 1px;
}

.komorebi-workspaces .ws-btn.active,
.glazewm-workspaces .ws-btn.active {
    color: transparent;
    background-color: var(--icon-color);
    width: 36px;
    height: 10px;
    border-radius: 5px;
}

/* --- Glazewm Tiling Direction --- */
.glazewm-tiling-direction {
    background-color: transparent;
    padding: 0;
    margin: 4px 0;
}

.glazewm-tiling-direction .btn {
    font-size: 14px;
    width: 14px;
    padding: 0 4px 0 12px;
    color: var(--foreground-color);
    border: none;
    display: flex;
    justify-content: center;
    align-items: center;
    margin: 0 2px;
}

.glazewm-tiling-direction .btn:hover {
    background-color: var(--hover-color);
}

/* --- Apps Widget Label --- */
.apps-widget .label {
    font-size: 14px;
    padding: 0 2px;
    color: var(--foreground-color);
}

/* --- Uptime Widget --- */
.uptime {
    font-size: 14px;
    margin-bottom: 10px;
    color: var(--foreground-color);
    font-weight: 600;
}

/* --- Power Menu Widget --- */
.power-menu-widget .label {
    font-size: 13px;
}

/* --- Power Menu Popup --- */
.power-menu-popup {
    background-color: rgba(20, 13, 14, 0.9);
    border-radius: 6px;
    padding: 10px;
    backdrop-filter: blur(6px);
    -webkit-backdrop-filter: blur(6px);
}

.power-menu-popup .button {
    padding: 0;
    width: 180px;
    height: 230px;
    border-radius: 8px;
    background-color: rgba(255, 255, 255, 0.08);
    color: var(--foreground-color);
    border-left: 4px solid rgba(0, 0, 0, 0.05);
    border-right: 4px solid rgba(0, 0, 0, 0.05);
    border-top: 8px solid rgba(0, 0, 0, 0.05);
    border-bottom: 8px solid rgba(0, 0, 0, 0.05);
    margin: 0px;
    display: flex;
    align-items: center;
    justify-content: flex-start;
}

.power-menu-popup .button:hover {
    background-color: rgba(255, 255, 255, 0.12);
    border-left: 4px solid rgba(0, 0, 0, 0.1);
    border-right: 4px solid rgba(0, 0, 0, 0.1);
    border-top: 8px solid rgba(0, 0, 0, 0.1);
    border-bottom: 8px solid rgba(0, 0, 0, 0.1);
}

.power-menu-popup .button .label {
    margin-bottom: 8px;
    font-size: 16px;
    font-weight: 500;
    color: var(--accent-color);
}

.power-menu-popup .button .icon {
    font-size: 64px;
    padding-top: 32px;
    color: var(--foreground-color);
}

.power-menu-popup .button.cancel .icon {
    padding: 0;
    margin: 0;
}

.power-menu-popup .button.cancel .label {
    color: var(--foreground-color);
    margin: 0;
}

.power-menu-popup .button.cancel {
    height: 32px;
    border-radius: 4px;
}

/* --- Volume Widget --- */
.volume-widget .icon {
    color: var(--foreground-color);
    margin: 1px 2px 0 0;
}

/* --- Battery Widget --- */
.battery-widget .icon {
    margin-right: 6px;
    color: var(--foreground-color);
}

/* --- Brightness Widget --- */
.brightness-widget {
    margin-right: -10px;
}

.brightness-widget .icon {
    color: var(--foreground-color);
}

/* --- Common Widget Padding --- */
.weather-widget,
.battery-widget,
.wifi-widget,
.volume-widget,
.brightness-widget {
    padding: 0 6px;
}

/* --- Weather Widget --- */
.weather-widget .icon {
    font-size: 18px;
    margin: 0 2px 1px 0;
}

/* --- Wallpapers Widget --- */
.wallpapers-widget .icon {
    color: var(--foreground-color);
    font-size: 14px;
    margin: 0;
}

/* --- Taskbar Widget --- */
.taskbar-widget {
    padding: 0;
    margin: 0;
    border: none;
}

.taskbar-widget .app-icon {
    padding: 0 6px;
    border: none;
    margin: 0;
    display: flex;
    align-items: center;
    justify-content: center;
}

.taskbar-widget .app-icon:hover {
    background-color: var(--hover-color);
    border-radius: 3px;
}

/* --- Whkd Widget --- */
.whkd-widget {
    padding: 0 6px 0 6px;
}

.whkd-widget .icon {
    font-size: 14px;
    color: var(--foreground-color);
}

/* --- Wallpapers Gallery Window --- */
.wallpapers-gallery-window {
    background-color: rgba(20, 13, 14, 0.9);
    border: 0;
    margin: 0;
    border-radius: 8px;
    backdrop-filter: blur(6px);
    -webkit-backdrop-filter: blur(6px);
}

.wallpapers-gallery-buttons {
    background-color: rgba(255, 255, 255, 0.08);
    color: var(--foreground-color);
    border: none;
    font-size: 14px;
    padding: 8px 0;
    border-radius: 8px;
    margin: 0 8px 8px 8px;
    width: 600px;
}

.wallpapers-gallery-buttons:hover {
    background-color: rgba(255, 255, 255, 0.12);
}

.wallpapers-gallery-image {
    border: 4px solid transparent;
    border-radius: 10px;
}

.wallpapers-gallery-image:hover {
    border: 4px solid var(--accent-color);
}

.wallpapers-gallery-image.focused {
    border: 4px solid var(--accent-color);
}

/* --- Systray --- */
.systray {
    border: none;
    margin-right: -15px;
    display: flex;
    align-items: center;
}

.systray .unpinned-container {
    border-radius: 8px;
    padding: 2px;
}

.systray .pinned-container {
    background: transparent;
    padding: 2px;
}

.systray .button {
    margin: 0 2px;
    color: var(--foreground-color);
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 3px;
}

.systray .button:hover {
    background: var(--hover-color);
}

.systray .unpinned-visibility-btn {
    border-radius: 4px;
    font-size: 20px;
}

/* --- Common Styles --- */
.wifi-widget,
.brightness-widget,
.systray {
    margin-top: 2.4px;
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --masir --ahk"
  stop_command: "komorebic stop --masir --ahk"
  reload_command: "komorebic stop --masir --ahk && komorebic start --masir --ahk"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true 
      acrylic: false
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 34
    padding:
      top: 6
      left: 10
      bottom: 0
      right: 10
    widgets:
      left: ["power_menu","komorebi_workspaces","komorebi_active_layout","active_window"]
      center: ["clock","apps"]
      right: ["systray","brightness","wallpapers","weather","wifi","battery","volume"]
widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: false
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M:%S}"
      timezones: []
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "\u23fc Offline"
      label_workspace_btn: ""
      label_workspace_active_btn: ""
      label_workspace_populated_btn: ""
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: true 
      hide_if_offline: true
      animation: true
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: false
      label: "{icon}"
      layouts: ['bsp', 'columns', 'rows', 'grid', 'vertical_stack', 'horizontal_stack', 'ultrawide_vertical_stack']
      layout_icons:
        bsp: "[\\\\]"
        columns: "[||]"
        rows: "[==]"
        grid: "[G]"
        vertical_stack: "[V]="
        horizontal_stack: "[H]="
        ultrawide_vertical_stack: "||="
        monocle: "[M]"
        maximised: "[X]"
        floating: "><>"
        paused: "[P]"
      callbacks:
        on_left: "next_layout"
        on_middle: "toggle_monocle"
        on_right: "prev_layout" 
      container_padding: 
        top: 0
        left: 8
        bottom: 0
        right: 8 
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: true
  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "\udb81\udce1"
      vertical_label: "\udb81\udce2"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807"
      show_alerts: true
      update_interval: 600
      hide_decimal: true
      units: "metric"
      location: "auto:ip"
      callbacks:
        on_left: "toggle_card"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      icons: 
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzard: "\uebaa"
        default: "\uebaa"
      weather_card: 
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 64
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}% | time: {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"
  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "Brightness {percent}%"
      tooltip: true
      auto_light: false 
      auto_light_icon: "\udb80\udce1"
      auto_light_night_level: 35
      auto_light_night_start_time: "19:00"
      auto_light_night_end_time: "06:45"
      auto_light_day_level: 75
      brightness_icons: [
        "\udb80\udcde",
        "\udb80\udcdd",
        "\udb80\udcdf",
        "\udb80\udce0"
      ]       
      callbacks:
        on_left: "toggle_label"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "exec quick_settings"
        on_middle: "exec cmd.exe /c start ms-settings:network"
        on_right: "toggle_label"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\ue62a"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\udb80\udf5e"
      label_expanded: "\udb80\udf5f"
      label_position: "right"
      icon_size: 16
      pin_click_modifier: "alt"
      show_unpinned: true
      show_battery: false
      show_volume: false
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: "{title}"
      hide_empty: true
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      max_field_size:
        label: 20
        label_alt: 30
      show_thumbnail: true
      controls_only: false
      controls_left: false
      controls_hide: false
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\udb81\udc0a"
        pause: "\udb80\udfe4"
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      label: "{data}"
      app_list:
        - { icon: "\uf0a2", launch: "notification_center" }
        - { icon: "\uf002", launch: "search" }
        - { icon: "\uf437", launch: "cmd /c Taskmgr" }
        - { icon: "\uf489", launch: "wezterm-gui" }
  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\ueba1</span>"
      label_alt: "Notifications {data}"
      token: env
      max_notification: 30
      only_unread: false
      max_field_size: 54
      menu_width: 400
      menu_height: 400
      menu_offset: 240
      update_interval: 60
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation: true
      icon_size: 16
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\uf03e</span>"
      image_path: "C:\\Wallpapers"
      change_automatically: false 
      update_interval: 60 
      gallery:
        enabled: true 
        blur: true
        image_width: 220
        image_per_page: 8
        show_buttons: false
        orientation: "portrait"
        image_spacing: 8
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 20
        enable_cache: false
```

### Readme

```markdown
A minimal theme following the Windows Fluent Design System.
```
