### ISSUE TITLE
[create-theme]: Moonlit Harmony

### ISSUE THREAD

**Issue by amnweb** [amnweb/yasb-themes#76]
### Name

Moonlit Harmony

### Description

A sleek, modern YASB + Komorebi bar with minimalistic styling and interactive widgets.

### Homepage

https://github.com/amnweb

### Image

https://i.imgur.com/5Ffa40i.png

### Theme Styles

```css
:root {
    --background-color: #12151b;
    --foreground-color: #cdd6f4;
    --border-color: #313244;
    --highlight-color: #313244;
    --blue-color: #89b4fa;
    --font-family: "JetBrainsMono NFP";
}
QToolTip { margin:6px; color: #cdd6f4;font-size:12px; background-color: #12151b; border: 0px solid #313244; border-radius: 6px; }
*{
	font-size: 14px;
	color: var(--foreground-color);
	font-weight: 400;
	font-family: var(--font-family);
	margin: 0;
	padding: 0;
}
.yasb-bar {
	padding: 0 8px;
	margin: 0; 
    background-color: var(--background-color);
}
.widget {
    padding: 0 8px;
    margin: 0;
}
/* Clock widget */
.clock-widget .label {
    font-size: 20px;
    font-weight: 900;
    background-color: var(--blue-color);
    margin: 0;
    padding: 0;
    color: var(--background-color);
}
.clock-widget .icon {
    font-size: 50px;
    margin: 0 -1px;
    padding: 0;
    font-weight: 600;
    color: var(--blue-color)
}
.clock-widget {
    border-top-left-radius: 24px;
    border-bottom-right-radius: 24px;
    padding: 0 20px;
}
.calendar {
    background-color: var(--background-color);
}
.calendar .calendar-table,
.calendar .calendar-table::item {
    background-color: rgba(17, 17, 27, 0);
    color: rgba(162, 177, 196, 0.85);
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    margin: 0;
    padding: 0;
    border: none;
    outline: none;  
}
.calendar .calendar-table::item:selected {
    color: rgb(255, 255, 255);
    background-color: var(--highlight-color);
    border-radius: 12px;
}
.calendar .day-label {
    margin-top: 20px;
}
.calendar .day-label,
.calendar .month-label,
.calendar .date-label {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-size: 16px;
    color: var(--foreground-color);
    font-weight: 600;
    min-width: 180px;
    max-width: 180px;
}
.calendar .month-label {
    font-weight: normal;
}
.calendar .date-label {
    font-size: 88px;
    font-weight: 900;
    color: #ffffff;
    margin-top: -20px;
}
/* Home menu widget */
.home-widget .icon {
    color: #b4befe;
    font-size: 20px;
}
.home-widget .icon:hover {
    color: #cdd6f4;
}
.home-menu {
    background-color:var(--background-color); 
}
.home-menu .menu-item {
    padding: 8px 48px 9px 16px;
    font-size: 14px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: var(--foreground-color); 
    font-weight: 600;
}
.home-menu .menu-item:hover {
    background-color:rgba(128, 130, 158, 0.15);
    color: #fff;
}
.home-menu .separator {
    max-height: 1px;
    background-color:rgba(128, 130, 158, 0.3);
}
/* Power Menu Widget */
.power-menu-widget .label { 
    font-size: 18px;
    color: #f38ba8;
}
.power-menu-popup .button {
	padding: 0;
	width: 180px;
	height: 230px;
	border-radius: 8px;
    border:2px solid var(--border-color);
	background-color: var(--background-color);
	color:var(--foreground-color);
}
.power-menu-popup .button:hover {
	border:2px solid #ffffff
}
.power-menu-popup .button .label {
	margin-bottom: 8px;
	font-size: 16px;
	font-weight: 500;
	color: var(--foreground-color)
}
.power-menu-popup .button .icon {
	font-size: 64px;
	padding-top: 32px;
	color: var(--foreground-color)
}
/* Volume widget */
.volume-widget .icon {
    font-size: 18px;
    color: #a6e3a1;
    padding-right: 4px;
}
.volume-slider {
    border: none;
}
.audio-menu {
    background-color:var(--background-color); 
}
.audio-container .device {
    background-color:transparent;
    border: none;
    padding:6px 8px 6px 4px;
    margin: 2px 0;
    font-size: 12px;
    border-radius: 4px;
}
.audio-container .device.selected {
    background-color: rgba(255, 255, 255, 0.085);
}
.audio-container .device:hover {
    background-color: rgba(255, 255, 255, 0.06);
}
/* Weather Widget */
.weather-widget .icon {
    font-size: 22px;
    padding-right: 4px;
    color: #f9e2af;
}
/* Weather card style */
.weather-card {
    background-color:var(--background-color);
}
 
.weather-card-today .label {
    font-size: 12px;
}
.weather-card-today .label.location {
    font-size: 24px;
    font-weight: 600;
}
.weather-card-today .label.arert {
    font-size: 12px;
    font-weight: 600;
    background-color: rgb(167, 108, 0);
    color: rgb(255, 255, 255);
    border-radius: 6px;
    padding: 5px 0;
}
.weather-card-day {
    border: 1px solid #282936;
    border-radius: 8px;
}
.weather-card-day .label {
    font-size: 12px;
}
/* Komorebi Control Widget */
.komorebi-control-widget .icon {
    font-size: 20px;
}
.komorebi-control-menu {
    background-color: var(--background-color)
}
.komorebi-control-menu .button {
    color: rgba(162, 177, 199, 0.4);
    padding: 8px 16px;
    font-size: 32px;
    border-radius: 8px;
    background-color: rgba(255, 255, 255, 0.04);
}
.komorebi-control-menu .button.active {
    color: rgb(228, 228, 228);
    background-color: rgba(255, 255, 255, 0.04);
}
.komorebi-control-menu .button:disabled,
.komorebi-control-menu .button.active:disabled {
    background-color: rgba(255, 255, 255, 0.01);
    color: rgba(255, 255, 255, 0.2);
}
.komorebi-control-menu .footer .text {
    font-size: 12px;
    color: #6c7086;
}
/* Komorebi Workspace Widget */
.komorebi-workspaces .ws-btn {
    border: none;
    color:transparent;
	margin:0 3px;
    border-radius: 8px;
    font-size:1px;
    background-color: #4f5868;
    height: 16px;
    width: 16px;
}
.komorebi-workspaces .ws-btn:hover {
    background-color: var(--blue-color)
}
.komorebi-workspaces .ws-btn.populated {
    background-color: #b4befe;
}
.komorebi-workspaces .ws-btn.active {
    width: 46px;
    max-width: 46px;
    background-color: var(--blue-color)
}
.komorebi-workspaces .float-override {
    color: #a6e3a1;
    padding-left: 6px;
}
.komorebi-workspaces .workspace-layer {
    padding-left:6px;
}
.komorebi-workspaces .workspace-layer.tiling {
    color: #a6e3a1;
}
.komorebi-workspaces .workspace-layer.floating {
    color: #eba0ac;
}
/* Notifications Widget */
.notification-widget .icon {
    font-size: 18px;
    padding-right: 4px;
}
.notification-widget .icon.new-notification {
    color: var(--blue-color);
}
.notification-widget .label.new-notification {
    color: var(--blue-color)
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 8
      left: 8
      bottom: 0
      right: 8
    widgets:
      left:
      - "home"
      - "komorebi_control"
      - "komorebi_workspaces"
      center:
      - "clock"
      right:
      - "media"
      - "weather"
      - "volume"
      - "notifications"
      - "power_menu"
widgets:
  komorebi_control:
    type: "komorebi.control.KomorebiControlWidget"
    options:
      label: "<span>\udb80\uddd9</span>"
      icons:
        start: "\uead3"
        stop: "\uead7"
        reload: "\uead2"
      run_ahk: false
      run_whkd: true
      show_version: true
      komorebi_menu:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: None
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb81\udf17</span>"
      menu_list:
        - { title: "User Home", path: "~" }
        - { title: "Download", path: "~/Downloads" }
        - { title: "Documents", path: "~/Documents" }
        - { title: "Pictures", path: "~/Pictures" }
      system_menu: true
      power_menu: true
      offset_top: 6
      alignment: "center"
      blur: true
      round_corners: true
      border_color: None
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "\uf001 {title}"
      label_alt: "\uf001 {artist}"
      max_field_size:
        label: 40
        label_alt: 24
      show_thumbnail: false
      controls_only: false
      controls_left: true
      controls_hide: true
      hide_empty: true
      thumbnail_alpha: 100
      thumbnail_padding: 8
      thumbnail_corner_radius: 0
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      callbacks:
        on_left: "toggle_play_pause"
        on_middle: "toggle_label"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\ue0ba</span>{%H:%M}<span>\ue0bc</span>"
      label_alt: "<span>\ue0ba</span>{%A, %d %B %Y}<span>\ue0bc</span>"
      callbacks:
        on_left: "toggle_calendar"
      calendar:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: None
        alignment: "center"
        direction: "down"
        offset_left: 0
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: ""
      label_workspace_active_btn: ""
      label_workspace_populated_btn: ""
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      toggle_workspace_layer:
        enabled: false
        tiling_label: "\udb81\ude40 Tiling"
        floating_label: "\udb80\udd37 Floating"
      animation: true
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>\udb81\udd99</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: env
      update_interval: 120
      hide_decimal: true
      units: "metric"
      location: env
      show_alerts: true
      callbacks:
        on_left: "toggle_card"
        on_middle: "toggle_label"
      weather_card:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: None
        alignment: "center"
        direction: "down"
        icon_size: 32
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{level}"
      tooltip: false
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      audio_menu:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: None
        alignment: 'right'
        direction: 'down'
      callbacks:
        on_middle: "toggle_label"
        on_right: "toggle_mute"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "<span>\uf011</span>"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200 # Milisecond
      button_row: 3
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["\udb81\udf3a", "Cancel"]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: true
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
```

### Readme

```markdown
A minimal and modern YASB + Komorebi bar theme featuring a sleek color palette and dynamic widgets. Change location and API key for weather widget.
```
