### ISSUE TITLE
[create-theme]: Gruvbox Material Dark

### ISSUE THREAD

**Issue by kkanden** [amnweb/yasb-themes#78]
### Name

Gruvbox Material Dark

### Description

Theme implements the Gruvbox Material Dark mix-medium/soft palette. A consistent accent color is chosen throughout the bar.

### Homepage

https://github.com/sainnhe/gruvbox-material

### Image

https://imgur.com/a/IOvFRXj

### Theme Styles

```css
:root {
    /* colors from the gruvbox material mix medium/soft palette */
    --yellow: #e9b143;
    --red: #f2594b;
    --bg0: #32302f;
    --bg1: #32302f;
    --bg2: #3c3836;
    --bg3: #45403d;
    --bg4: #504945;
    --bg5: #665c54;
    --bg_dim: #282828;
    --grey0: #7c6f64;
    --grey1: #928374;
    --grey2: #a89984;
    --fg0: #e2cca9;

    --accent: #e9b143;
    --background: rgba(69, 64, 61, 0.85); /*bg3*/
    --background-widget: rgba(50, 48, 45, 0.6); /*bg0*/
    --text: #e2cca9;
}

/* GLOBAL */
* {
    font-size: 11px;
    color: var(--text);
    font-weight: 900;
    font-family: "JetBrainsMono NFP";
    margin: 0;
    padding: 0;
}

.yasb-bar {
    padding: 0 2px;
    background-color: var(--background);
    border-radius: 6px;
}

.icon {
    color: var(--accent);
    font-size: 14px;
    margin: 0 5px;
}

.label {
    padding: 0 6px 0 0;
    margin: 0 3px 0 0;
}

.widget {
    padding: 0 3px;
    margin: 0;
}

.widget-container {
    background-color: var(--background-widget);
    margin: 4px 0px;
    border-radius: 6px;
}

.widget .label {
    padding: 2px 2px 1px 5px;
}


/* CALENDAR */

.calendar {
    background-color: var(--bg_dim);
    border-radius: 6px;
    border: 1px solid var(--grey1);
}

.calendar .calendar-table,
.calendar .calendar-table::item {
    background-color: var(--bg_dim);
    color: var(--fg0);
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    margin: 0;
    padding: 0;
}

.calendar .calendar-table::item:selected {
    color: rgb(255, 255, 255);
    border-radius: 6;
    border: 1px solid var(--accent)
}

.calendar .day-label {
    margin-top: 20px;
}

.calendar .day-label,
.calendar .month-label,
.calendar .date-label {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-size: 16px;
    color: var(--fg0);
    font-weight: 700;
    min-width: 180px;
    max-width: 180px;
}

.calendar .month-label {
    font-weight: normal;
}

.calendar .date-label {
    font-size: 88px;
    font-weight: 900;
    color: var(--fg0);
    margin-top: -20px;
}

.komorebi-workspaces .offline-status {
    color: var(--text);
    font-size: 12px;
    padding: 0 0px;
    font-weight: 600;
}

.komorebi-workspaces .ws-btn {
    border: none;
    margin: 0 3px;
    height: 10px;
    width: 9px;
    border-radius: 2px;
    background-color: var(--bg4);
    color: rgba(0, 0, 0, 0);
}

.komorebi-workspaces .ws-btn:hover {
    color: rgba(0, 0, 0, 0);
    background-color: var(--grey0);
}

.komorebi-workspaces .ws-btn.populated:hover {
    color: rgba(0, 0, 0, 0);
    background-color: var(--grey1);
}

.komorebi-workspaces .ws-btn.populated {
    color: rgba(0, 0, 0, 0);
    background-color: var(--grey1);
}

.komorebi-workspaces .ws-btn.active {
    color: rgba(0, 0, 0, 0);
    background-color: var(--accent);
    height: 13px;
}

.komorebi-active-layout {
    padding: 0 0px 0 0;
}

.komorebi-active-layout .label {
    font-weight: 600;
    padding: 2px 0 0 0;
}

/*POWER MENU WIDGET*/

.power-menu-widget .label {
    color: var(--accent);
    font-size: 16px;
}

.power-menu-popup .button {
    width: 160px;
    height: 240px;
    border-radius: 6px;
    background-color: var(--bg3);
    font-family: "SegoeUI";
    color: white;
    border: 4px solid rgba(255, 255, 255, 0);

}

.power-menu-popup .button.hover {
    background-color: var(--bg1);
    border: 4px solid var(--bg1);
}

.power-menu-popup .button .label {
    padding: 0;
    margin: 0;
    font-size: 16px;
    font-weight: 600;
    color: var(--fg0);
    font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
    display: inline-block;
    text-align: center;
}

.power-menu-popup .button .icon {
    font-size: 64px;
    padding-top: 54px;
    color: var(--fg0);
}

.power-menu-popup .button.cancel {
    height: 32px;
}

.power-menu-popup .button.cancel .label {
    color: var(--red);
}

/* WEATHER */
.weather-widget .icon {
    font-size: 16px;
}
 
/* Weather Card*/

.weather-card-today {
    border: 1px solid var(--grey1);
    border-radius: 8px;
    background-color: var(--background);
}

.weather-card-today .label {
    font-size: 12px;
}

.weather-card-today .label.location {
    font-size: 24px;
    font-weight: 700;
}

.weather-card-today .label.arert {
    font-size: 12px;
    font-weight: 700;
    background-color: rgba(247, 199, 42, 0.05);
    border: 1px solid rgba(247, 209, 42, 0.1);
    color: rgba(196, 181, 162, 0.85);
    border-radius: 6px;
    padding: 5px 0;
}

.weather-card-day {
    border: 1px solid var(--grey1);
    border-radius: 8px;
    background-color: var(--bg_dim);
}

.weather-card-day .label {
    font-size: 12px;
}

/* MEDIA */

.media-widget .label {
    padding: 0 10px;
}

.media-widget .btn {
    color: var(--accent);
    padding: 0 0px;
    padding-right: 0px;
    margin: 4px 0;
    font-family: Segoe Fluent Icons;
}

.media-widget .btn:hover {
    color: var(--subtext0);
}

.media-widget .btn.disabled:hover,
.media-widget .btn.disabled {
    color: var(--surface1);
    font-size: 12px;
    background-color: rgba(0, 0, 0, 0);
}

/* VOLUME */

.volume-slider {
    border: none;
}
.volume-slider::groove {
    color: var(--accent)
}
.volume-slider::handle{
    color: var(--accent)
} 
.audio-menu {
    background-color: var(--bg_dim); 
    border: 1px solid var(--grey1);
    border-radius: 6px;
}
.audio-container .device {
    background-color:transparent;
    border: none;
    padding:6px 8px 6px 4px;
    margin: 2px 0;
    font-size: 12px;
    border-radius: 4px;
}
.audio-container .device.selected {
    background-color: rgba(255, 255, 255, 0.085);
}
.audio-container .device:hover {
    background-color: rgba(255, 255, 255, 0.06);
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false

komorebi:
    start_command: "komorebic start --whkd"
    stop_command: "komorebic stop"
    reload_command: "komorebic stop && komorebic start --whkd"

bars:
    status-bar:
        enabled: true
        screens: ["1"]
        class_name: "yasb-bar"
        alignment:
            position: "top"
            center: false
        blur_effect:
            enabled: false
            acrylic: true
            dark_mode: false
            round_corners: false
            border_color: None
        window_flags:
            always_on_top: false
            windows_app_bar: true
        dimensions:
            width: "100%"
            height: 28
        padding:
            top: 3
            left: 3
            bottom: 0
            right: 3
        widgets:
            left: ["weather", "komorebi_workspaces", "active_window"]
            center: ["clock"]
            right: ["language", "cava", "media", "volume", "power_menu"]
widgets:
    cava:
        type: "yasb.cava.CavaWidget"
        options:
            bar_height: 12
            framerate: 120
            sleep_timer: 60
            hide_empty: true
            gradient: 0
            foreground: "#e2cca9"
            container_padding:
                top: 3
                right: 2
                bottom: 3
                left: 3
    media:
        type: "yasb.media.MediaWidget"
        options:
            label: "<span>\uf001</span> {artist} - {title}"
            hide_empty: true
            max_field_size:
                label: 20
            show_thumbnail: false
            controls_hide: true
            thumbnail_alpha: 50
            thumbnail_padding: 70
            thumbnail_corner_radius: 5
            icons:
                prev_track: "\ue892"
                next_track: "\ue893"
                play: "\ue768"
                pause: "\ue769"
            callbacks:
                on_left: "do_nothing"

    clock:
        type: "yasb.clock.ClockWidget"
        options:
            label: "<span>\uf017</span> {%d/%m/%Y, %H:%M:%S}"
            timezones: [] #Looking up time zone info from registry
            calendar:
                alignment: "center"
            callbacks:
                on_left: "toggle_calendar"
                on_right: "do_nothing"
    taskbar:
        type: "yasb.taskbar.TaskbarWidget"
        options:
            icon_size: 16
            animation: true
            ignore_apps:
                processes: []
                titles: []
                classes: []
            container_padding:
                top: 0
                left: 8
                bottom: 0
                right: 8
    komorebi_workspaces:
        type: "komorebi.workspaces.WorkspaceWidget"
        options:
            label_offline: "\u26a1 Offline"
            label_workspace_btn: "\udb81\udc3d"
            label_workspace_active_btn: "\udb81\udc3e"
            label_workspace_populated_btn: "\udb81\udc3e"
            label_default_name: "{index}"
            label_zero_index: true
            hide_empty_workspaces: false
            hide_if_offline: true
            animation: true
            container_padding:
                top: 0
                left: 0
                bottom: 0
                right: 0
    weather:
        type: "yasb.weather.WeatherWidget"
        options:
            label: "<span>{icon}</span> {conditions} {temp} \u00b7 \u2193 {min_temp} \u2191 {max_temp} \u00b7 {precip}"
            api_key: "3bf4cf9a7c3f40d6b31174128242807"
            update_interval: 600
            units: "metric"
            hide_decimal: true
            location: "Poland Wroclaw"
            show_alerts: true
            weather_card:
                alignment: "center"
                offset_left: 150
            callbacks:
                on_left: "toggle_card"
            icons:
                sunnyDay: "\ue30d"
                clearNight: "\ue32b"
                cloudyDay: "\udb81\udd99"
                cloudyNight: "\ue311"
                rainyDay: "\udb81\ude7e"
                rainyNight: "\udb81\ude7e"
                snowyIcyDay: "\udb81\udd98"
                snowyIcyNight: "\udb81\udd98"
                blizzard: "\uebaa"
                default: "\uebaa"
    volume:
        type: "yasb.volume.VolumeWidget"
        options:
            label: "<span>{icon}</span> {level}"
            label_alt: "{volume}"
            volume_icons:
                - "\ueee8" # Icon for muted
                - "\uf026" # Icon for 0-10% volume
                - "\uf027" # Icon for 11-30% volume
                - "\uf027" # Icon for 31-60% volume
                - "\uf028" # Icon for 61-100% volume
            callbacks:
                on_right: "exec cmd.exe /c start ms-settings:sound"
                on_middle: "toggle_mute"
    power_menu:
        type: "yasb.power_menu.PowerMenuWidget"
        options:
            label: "\uf011"
            uptime: False
            blur: False
            blur_background: True
            animation_duration: 100 # Milisecond
            button_row: 4 # Number of buttons in row, min 1 max 5
            buttons:
                shutdown: ["\uf011", "Shut Down"]
                restart: ["\uead2", "Restart"]
                signout: ["\udb80\udf43", "Sign out"]
                sleep: ["\u23fe", "Sleep"]
                cancel: ["", "Cancel"]
    active_window:
        type: "yasb.active_window.ActiveWindowWidget"
        options:
            label: "{win[process][name]}"
            label_alt: ""
            label_no_window: ""
            label_icon: true
            label_icon_size: 14
            max_length: 40
            max_length_ellipsis: "..."
            monitor_exclusive: false
            callbacks:
                on_left: "do_nothing"
    language:
        type: "yasb.language.LanguageWidget"
        options:
            label: "<span>\uf11c</span> {lang[language_code]}"
            label_alt: "{lang[full_name]}"
            update_interval: 1
            callbacks:
                on_left: "do_nothing"
                on_middle: "do_nothing"
                on_right: "do_nothing"
            container_padding:
                bottom: 1
```

### Readme

```markdown
Theme implements the Gruvbox Material Dark mix-medium/soft palette. A consistent accent color is chosen throughout the bar.
```
