### ISSUE TITLE
[create-theme]: hyprlandcustomdock

### ISSUE THREAD

**Issue by NgXuanChat** [amnweb/yasb-themes#81]
### Name

thebar

### Description

this is bar clean and beautiful

### Image

https://media.discordapp.net/attachments/1342145133973344260/1361612182793490674/image.png?ex=67ff63a9&is=67fe1229&hm=63228f0c9e68e462141a85f17e0c46035dc70a47162ab9250a068c3c1294fd34&=&format=webp&quality=lossless&width=603&height=23

### Theme Styles

```css
:root {
  --bg: rgba(0,0,0,0.6);
  --main: #9ba2a7;
  --wallpaper: url("C:/Users/ngxuanchat/Wallpapers/hi.jpg");
  --color1: #3d3c6a;
  --background: #07060c;
  --color9: #3d3c6a;
  --color7: #c1c0c2;
  --color14: #9f97c2;
  --color10: #555280;
  --color3: #486192;
  --cursor: #c1c0c2;
  --color2: #555280;
  --color5: #877dae;
  --color13: #877dae;
  --color0: #07060c;
  --color15: #c1c0c2;
  --color6: #9f97c2;
  --color4: #6d6697;
  --foreground: #c1c0c2;
  --color11: #486192;
  --color8: #555568;
  --color12: #6d6697;
}
*{
font-size: 13px;
color: var(--main);
font-weight: 600;
font-family: "JetBrainsMono NFP";
margin: 0;
padding: 0;
}
.yasb-bar {
padding: 0;
margin: 0;
  background-color: var(--bg);
  border-radius: 0px;
}
.widget {
padding: 0 12px;
margin: 0;
}
.icon {
font-size: 16px;
  padding-right: 4px;
  padding-left: 4px;
  margin-left: 0px;
  color: var(--main);
}
.widget .label {
padding: 0px 2px;
  color
}




.komorebi-workspaces .offline-status {
  color: var(--main);
  font-size: 12px;
  padding: 0 0 0 4px;
  font-weight:600;
}
.komorebi-workspaces .ws-btn {
  border: none;
  color: var(--main);
margin:0;
  font-size: 24px;
  height: 34px;
  width: 34px;
  padding: 0 3px;
  background: transparent;
  border-radius: 0px;
  transition: all 0.4s cubic-bezier(0.55, -0.68, 0.48, 1.682);
}
.komorebi-workspaces .ws-btn:hover {
  background: transparent;
  background-color: var(--color1);
}
.komorebi-workspaces .ws-btn.populated {
  color: var(--main);
}
.komorebi-workspaces .ws-btn.active {
  background-color: var(--color1);
  border-radius: 20px;
  margin-left: 0px;
  padding-left: 15px;
  padding-right: 15px;
  margin-right: px;
  transition: all 0.8s cubic-bezier(0.55, -0.68, 0.48, 1.682);

}
.komorebi-workspaces .ws-btn.active:hover {
  background-color: var(--color2);
  transition: all 0.8s cubic-bezier(0.55, -0.68, 0.48, 1.682)
}

.volume-widget .icon {
  padding-right: 3px;
  padding-left: 0px;
  font-size: 14px;
  max-width: 20px;
  min-width: 22px;
  margin-left: 2px;
}
.clock-widget .icon {
  color: var(--blue);
  padding-right: 6px;
  padding-left: 0px;
}
.volume-slider {
  border: none;
}
.audio-menu {
  background-color:rgba(13, 6, 10, 0.3);
}
.audio-container .device {
  background-color:transparent;
  border: none;
  padding:6px 8px 6px 4px;
  margin: 2px 0;
  font-size: 12px;
  border-radius: 4px;
}
.audio-container .device.selected {
  background-color: rgba(255, 255, 255, 0.085);
}
.audio-container .device:hover {
  background-color: rgba(255, 255, 255, 0.06);
}
.calendar {
  background-color: rgba(17, 17, 27, 0.4);
}
.calendar .calendar-table,
.calendar .calendar-table::item {
  background-color: rgba(17, 17, 27, 0);
  color: rgba(162, 177, 196, 0.85);
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  margin: 0;
  padding: 0;
  border: none;
  outline: none;
}
.calendar .calendar-table::item:selected {
  color: rgb(255, 255, 255);
}
.calendar .day-label {
  margin-top: 20px;
}
.calendar .day-label,
.calendar .month-label,
.calendar .date-label {
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  font-size: 16px;
  color: #fff;
  font-weight: 700;
  min-width: 180px;
  max-width: 180px;
}
.calendar .month-label {
  font-weight: normal;
}
.calendar .date-label {
  font-size: 88px;
  font-weight: 900;
  color: rgb(255, 255, 255);
  margin-top: -20px;
}
.volume-slider {
  border: none;
}
.volume-slider::groove {}
.volume-slider::handle{}
.audio-menu {
  background-color:rgba(17, 17, 27, 0.4);
}
.audio-container .device {
  background-color:transparent;
  border: none;
  padding:6px 8px 6px 4px;
  margin: 2px 0;
  font-size: 12px;
  border-radius: 0px;
}
.audio-container .device.selected {
  background-color: rgba(255, 255, 255, 0.085);
}
.audio-container .device:hover {
  background-color: rgba(255, 255, 255, 0.06);
}
.div-widget .label {
  color: var(--surface1)
}
.div-widget {
  margin-left: 0px;
  padding-left: 0px;
  padding-right: 0px;
}
.volume-widget {
  margin-right: 3px;
}
.clock-widget {
  margin: 0;
  padding: 0;
}
.widget {
  padding: 0;
}
.wifi-widget {
  margin-right: 8px;
}
.brightness-widget {
  margin-right: 2px;
  margin-left: 0px;
}
.brightness-widget .icon {
  margin-left: 0px;
  padding-left: 0px;
}
.systray {
  background: transparent;
  border: None;
  margin: 0;
}

.systray .unpinned-container {
  background: transparent;
  border-radius: 8px;
}

.systray .pinned-container {
  background: transparent;
}

.systray .pinned-container[forceshow=true] {
  background: red;
}

.systray .button {
  border-radius: 4px;
  padding: 2px 2px;
}

.systray .button:hover {
  background: #727272;
}

.systray .button[dragging=true] {
  background: orange;
  border-color: #FF8800;
}

.systray .unpinned-visibility-btn {
  border-radius: 4px;
  height: 20px;
  width: 16px;
}

.systray .unpinned-visibility-btn:checked {
  background: transparent;
}

.systray .unpinned-visibility-btn:hover {
  border: 0px solid #AAAAAA;
  border-radius: 4px;
  border-color: #AAAAAA;
}
.wallpapers-widget {
  padding: 0 7px 0 7px;
}
.wallpapers-gallery-window {
  background-color: rgba(85, 42, 240, 0.01);
  border: 0;
  margin: 0;
}
.wallpapers-gallery-buttons {
  background-color:rgba(255, 255, 255, 0);
  color:var(--text);
  border: none;
  font-size: 16px;
  padding: 8px 0;
  border-radius: 8px;
  margin:0 8px 8px 8px;
  width: 600px;
}
.wallpapers-gallery-buttons:hover {
  background-color:rgba(255, 255, 255, 0.1)
}
.wallpapers-gallery-image {
  border: 4px solid transparent;
  border-radius: 10px;

}
.wallpapers-gallery-image:hover {
  border: 4px solid var(--sapphire);
}
.wallpapers-gallery-image.focused {
  border: 4px solid var(--sapphire);

}
/* --- Power Menu Popup --- */
/* Uptime text */
.uptime {
  font-size: 12px;
  margin: 0 0 4px;
}
.power-menu-widget .label {
  font-size: 14px;
  margin-left: 0px;
}
.power-menu-popup {
  background-color: rgba(2, 2, 2, 0.466);
  border-radius: 12px;
  border: 0px solid rgb(0, 0, 0);
}
.power-menu-popup .button {
  padding: 0;
  width: 200px;
  height: 160px;
  border-radius: 4px;
  background-color: rgba(66, 66, 68, 0.247);
  color: white;
  border: 1px solid rgba(255, 255, 255, 0.1);
  margin: 4px;
}


.power-menu-popup .button.hover {
  background-color: rgb(64, 64, 68);
  border: 1px solid rgb(26, 26, 27);
}
.power-menu-popup .button .label {
  margin-bottom: 8px;
  font-size: 16px;
  font-weight: 600;
  color: rgba(255, 255, 255, 0.425);
  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
}
.power-menu-popup .button .icon {
  font-size: 72px;
  padding-top: 20px;
  color: rgba(255, 255, 255, 0.25);
}
.power-menu-popup .button.cancel .icon {
  color: rgba(139, 201, 243, 0.568);
}
.power-menu-popup .button.cancel .label {
  color: rgba(139, 201, 243, 0.568);
}
.power-menu-popup .button.shutdown .icon {
  color: rgba(255, 9, 9, 0.685);
}
.power-menu-popup .button.shutdown .label {
  color: rgba(255, 9, 9, 0.685);
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd --masir"
  stop_command: "komorebic stop --whkd --masir"
  reload_command: "komorebic stop --whkd --masir && komorebic start --whkd --masir"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: true
      round_corners_type: "normal"
      border_color: none
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 34
    padding:
      top: 16
      left: 240
      bottom: -2
      right: 240
    widgets:
      left: ["komorebi_workspaces","wallpapers"]
      center: ["clock"]
      right: ["systray","brightness","divider","volume","divider","memory","divider","uwifi","power_menu"]
widgets:
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%I:%M %b %d}"
      label_alt: "{%H:%M %b %d}"
      timezones: []
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "\u23fc Offline"
      label_workspace_btn: ""
      label_workspace_active_btn: "󰫢"
      label_workspace_populated_btn: "󰫣"
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "grid",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "right_main_vertical_stack",
        ]
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        vertical_stack: "V-STACK"
        horizontal_stack: "H-STACK"
        ultrawide_vertical_stack: "W-STACK"
        right_main_vertical_stack: "RMV-STACK"
        monocle: "MONOCLE"
        maximised: "MAX"
        floating: "FLOATING"
        paused: "PAUSED"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      callbacks:
        on_left: "next_layout"
        on_middle: "toggle_monocle"
        on_right: "prev_layout"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      audio_menu:
        blur: True
        round_corners: True
        round_corners_type: 'normal'
        border_color: 'System'
        alignment: 'right'
        direction: 'down'
        distance: 6
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
  divider:
    type: "yasb.custom.CustomWidget"
    options:
      label: "|"
      label_alt: "|"
      class_name: "div-widget"
  battery:
    type: "yasb.battery.BatteryWidget"
    options: 
      label: "<span>{icon}</span>{percent}%"
      label_alt: "{icon} {percent}% | time: {time_remaining}"
      charging_options: {icon_format: '{charging_icon} {icon}', blink_charging_icon: True}
      status_thresholds: {critical: 10, low: 25, medium: 75, high: 95, full: 100}
      status_icons: {icon_charging: '\uf0e7', icon_critical: '\uf244', icon_low: '\uf243', icon_medium: '\uf242', icon_high: '\uf241', icon_full: '\uf240'}
      animation: {'enabled': True, 'type': 'fadeInOut', 'duration': 200}
      callbacks: {on_left: 'toggle_label', on_middle: 'do_nothing', on_right: 'do_nothing'}
      container_padding: {'top': 0, 'left': 0, 'bottom': 0, 'right': 0}
  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
     label: "<span>{icon}</span> {percent}%"
     label_alt: "Brightness {percent}%"
     tooltip: true
     hide_unsupported: true
     brightness_toggle_level: [0, 50, 100]
     auto_light: false
     auto_light_icon: "\udb80\udce1"
     auto_light_night_level: 35
     auto_light_night_start_time: "19:00"
     auto_light_night_end_time: "06:45"
     auto_light_day_level: 75
     brightness_icons: [
       "\uf522",  # Icon for 0-25% brightness
       "\uf522",  # Icon for 26-50% brightness
       "\uf522",  # Icon for 51-75% brightness
       "\uf522"   # Icon for 76-100% brightness
     ]
     brightness_menu:
       blur: true
       round_corners: true
       round_corners_type: "normal"
       border_color: "System"
       alignment: "right"
       direction: "down"
       distance: 6
     callbacks:
       on_left: "toggle_label"
     container_padding:
       top: 0
       left: 8
       bottom: 0
       right: 8
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uf4bc</span> {virtual_mem_percent}%"
      label_alt: "<span>\uf4bc</span> VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
  network:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span> {wifi_name}"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:network"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      wifi_icons: [
        "\udb82\udd2e",  # Icon for 0% strength
        "\udb82\udd1f",  # Icon for 1-20% strength
        "\udb82\udd22",  # Icon for 21-40% strength
        "\udb82\udd25",  # Icon for 41-80% strength
        "\udb82\udd28"   # Icon for 81-100% strength
        ]
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "󰚥 "
      label_expanded: "📎 "
      label_position: "right"
      icon_size: 14
      pin_click_modifier: "alt"
      show_unpinned: true
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<h2>󰸉</h2>"
      image_path: "C:\\Users\\ngxuanchat\\Wallpapers"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 296
        image_per_page: 6
        show_buttons: true
        orientation: "portrait"
        image_spacing: 10
        lazy_load: true
        lazy_load_delay: 10
        lazy_load_fadein: 200
        image_corner_radius: 20
        enable_cache: true
  uwifi:
    type: "yasb.custom.CustomWidget"
    options:
      label: "󰀄 ngxuanchat "
      label_alt: "󰀄 ngxuanchat "
      class_name: "uwifi-widget"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
```

### Readme

```markdown
this is bar clean and beautiful
```
