### ISSUE TITLE
[create-theme]: Comfyppuccin Reimagined

### ISSUE THREAD

**Issue by AlmiWasFound** [amnweb/yasb-themes#83]
### Name

Comfyppuccin Reimagined

### Description

A comfy catppuccin theme for all those great desktop ricing legends. An upgraded version of the original comfyppuccin theme. Really complements a dark-themed or catppuccin-theme based setup/rice.

### Homepage

https://github.com/AlmiWasFound

### Image

https://imgur.com/RoGTTjM.png

### Theme Styles

```css
/* -------------------------------------------------------------------------------------------------- */
/* Variables                                                                                         */
/* -------------------------------------------------------------------------------------------------- */

:root {
	--rosewater: rgb(245, 224, 220);
	--flamingo: rgb(242, 205, 205);
	--pink: rgb(245, 194, 231);
	--mauve: rgb(203, 166, 247);
	--red: rgb(243, 139, 168);
	--maroon: rgb(235, 160, 172);
	--peach: rgb(250, 179, 135);
	--yellow: rgb(249, 226, 175);
	--green: rgb(166, 227, 161);
	--teal: rgb(148, 226, 213);
	--sky: rgb(137, 220, 235);
	--sapphire: rgb(116, 199, 236);
	--blue: rgb(137, 180, 250);
	--lavender: rgb(180, 190, 254);
	--text: rgb(205, 214, 244);
	--subtext1: rgb(186, 194, 222);
	--subtext0: rgb(166, 173, 200);
	--overlay2: rgb(147, 153, 178);
	--overlay1: rgb(127, 132, 156);
	--overlay0: rgb(108, 112, 134);
	--surface2: rgb(88, 91, 112);
	--surface1: rgb(69, 71, 90);
	--surface0: rgb(40, 41, 54);
	--base: rgb(30, 30, 46);
	--mantle: rgb(24, 24, 37);
	--crust: rgb(17, 17, 27);
}

/* -------------------------------------------------------------------------------------------------- */
/* 1. Layout and Containers                                                                           */
/* -------------------------------------------------------------------------------------------------- */

* {
	font-size: 12px;
	color: #cdd6f4;
	font-weight: 900;
	font-family: "JetBrainsMono NFP";
	margin: 0;
	padding: 0;
}
.yasb-bar {
	padding: 0 8px;
	margin: 0;
	background-color: #1e1e2e;
	border-radius: 8px;
}

.widget {
	padding: 0 10px;
	margin: 0;
}

.widget .label {
	padding: 2px 2px 1px 2px;

}

.widget .label.alt {
	padding: 1px 8px 1px 8px;
}

/* -------------------------------------------------------------------------------------------------- */
/* 2. Widget Containers                                                                               */
/* -------------------------------------------------------------------------------------------------- */

.glazewm-workspaces .widget-container {
	background-color: var(--mantle);
	margin: 3px 0px 3px 0px;
	border-radius: 8px;
}

/* -------------------------------------------------------------------------------------------------- */
/* 3. Widgets                                                                                         */
/* -------------------------------------------------------------------------------------------------- */

/***-------------------------------      • Windows Desktops •      --------------------------------***/

.glazewm-workspaces {
	margin: 0;
}
.glazewm-workspaces .offline-status {
    color: rgb(205, 214, 244);
    font-size: 12px;
    padding: 0 4px;
    font-weight: 900;
}
.glazewm-workspaces .ws-btn {
    border: none;
    background-color: var(--surface2);
    margin: 0px 4px;
    padding: 0;
    color: rgba(0, 0, 0, 0);
    border-radius: 5px;
    height: 10px;
    width: 10px;
}
.glazewm-workspaces .ws-btn.populated {
    background-color:var(--surface2);
}
.glazewm-workspaces .ws-btn.active {
    color: rgba(0, 68, 255, 0);
    background-color:var(--mauve);
    width: 28px;
    height: 10px;
    border-radius: 5px;
}

/***---------------------------------      • Audio Widget •      ----------------------------------***/

.audio-menu {
	background-color: var(--mantle);
}
.audio-container .device {
	background-color: var(--base);
	border: none;
	padding: 6px 8px 6px 4px;
	margin: 2px 0;
	font-size: 12px;
	border-radius: 4px;
	font-family: "SF Pro Text";
}
.audio-container .device.selected {
	background-color: var(--crust);
}
.audio-container .device:hover {
	background-color: var(--base);
}

.volume-slider::groove {
	color: transparent;
}
.volume-slider::handle {
	background-color: transparent;
}
.audio-menu {
	background-color: rgba(17, 17, 27, 0.4);
}

/***-------------------------------      • Power Menu Widget •      --------------------------------***/

.power-menu-popup {
	background: var(--crust);
	border-radius: 8px;
}

.power-menu-widget .label {
	color: #eba0ac;
	font-size: 16px;
	font-family: "JetBrainsMono NF";
}
.power-menu-popup .button {
	padding: 0px;
	margin: 5px;
	width: 250px;
	height: 175px;
	border-radius: 8px;
	background-color: var(--base);
	font-family: "SF Pro Rounded";
	color: white;

}
.power-menu-popup .button.hover {
	background-color: var(--base);
}
.power-menu-popup .button .label {
	margin-bottom: 0px;
	font-size: 16px;
	font-weight: 600;
	color: var(--text);
	font-family: "SF Pro Rounded";
}
.power-menu-popup .button .icon {
	font-size: 55px;
	padding-top: 25px;
	padding-right: 10px;
	color: var(--text);
}
.power-menu-popup .button.cancel .icon {
	color: var(--red);
}
.power-menu-popup .button.cancel .label {
	color: var(--red);
}


/* --------------------------------------------------------------------------------------------------- */
/* 6. Icons & Typography                                                                               */
/* --------------------------------------------------------------------------------------------------- */

.icon {
	font-size: 16px;
}
.volume-widget .icon {
	color: var(--mauve);
	margin: 1px 2px 0 0;
}
.start-menu .icon {
	font-size: 18px;
	color: #89b4fa
}
.clock-widget .icon {
	color: #cba6f7;
	font-size: 14px;
	margin-right: 7px;
}

/***---------------------------------      • Weather Icons •      ----------------------------------***/

.weather-widget .icon.cloudyDay {
	color: var(--mauve);
}
.weather-widget .icon.cloudyNight {
	color: var(--mauve);
}
.weather-widget .icon.rainyDay {
	color: var(--mauve);
}
.weather-widget .icon.rainyNight {
	color: var(--mauve);
}
.weather-widget .icon.snowyIcyDay {
	color: var(--mauve);
}
.weather-widget .icon.snowyIcyNight {
	color: var(--mauve);
}
.weather-widget .icon.blizzard {
	color: var(--mauve);
}
.weather-widget .icon.default {
	color: var(--mauve);
}

/***----------------------------------      • Weather Card •      -----------------------------------***/

.weather-card {
	background-color: var(--mantle);
}
.weather-card-today {
	border-radius: 8px;
	background-color: var(--base);
	color: var(--text);
}
.weather-card-today .label {
	font-size: 12px;
	font-family: "SF Pro Rounded";
}
.weather-card-today .label.location {
	font-size: 24px;
	font-weight: 800;
	font-family: "SF Pro Rounded";
}
.weather-card-today .label.alert {
	font-size: 12px;
	font-weight: 700;
	background-color: rgba(247, 199, 42, 0.05);
	border: 1px solid rgba(247, 209, 42, 0.1);
	color: rgba(196, 181, 162, 0.85);
	border-radius: 6px;
	padding: 5px 0;
}
.weather-card-day {
	border-radius: 8px;
	background-color: var(--base);
}
.weather-card-day .label {
	font-size: 12px;
	font-family: "SF Pro Rounded";
}

/* Media Widget */

.media-widget {
	padding: 0;
	margin-left: 0;
}
.media-widget .label {
	color: var(--lavender);
    padding-left: 5px;
}

/* Hide media widget buttons */

.media-widget .btn {
	max-width: 0;
}

.calendar {
	background-color: var(--mantle);
}
.calendar .calendar-table,
.calendar .calendar-table::item {
	background-color: rgba(17, 17, 27, 0);
	color: var(--overlay1);
	font-family: "SF Pro Rounded";
	margin: 0;
	padding: 0;
	border: none;
	outline: none;
}

.calendar .calendar-table::item:selected {
	color: #4c4f69;
	background: var(--mauve);
	border-radius: 8px;
}
.calendar .day-label {
	margin-top: 20px;
}
.calendar .day-label,
.calendar .month-label,
.calendar .date-label {
	font-family: "SF Pro Rounded";
	font-size: 16px;
	color: var(--text);
	font-weight: 700;
	min-width: 180px;
	max-width: 180px;
}
.calendar .month-label {
	font-weight: normal;
	padding-bottom: 12px;
}
.calendar .date-label {
	font-size: 88px;
	font-weight: 900;
	color: var(--text);
	margin-top: -20px;
}

.home-menu {
	background-color: var(--mantle);
	border-radius: 8px;
	padding: 0;
	margin-left: 0px;
}
.home-menu .menu-item {
	padding: 8px 48px 8px 12px;
	font-size: 13px;
	font-family: "SF Pro Rounded";
	font-weight: 600;
}
.home-menu .menu-item:hover {
	background-color: #cba6f4;
	color: #181825;
	margin: 4px 6px;
	border-radius: 4px;
}
.home-menu .separator {
	max-height: 1px;
	background-color: #45475a;
	margin: 0 8px;
}

.wallpapers-gallery-window {
	background-color: var(--mantle);
	border: 2px;
	margin: 0;
}

.volume-slider {
	border: none;
}
.volume-slider::groove {
}
.volume-slider::handle {
}
.audio-menu {
	background-color: rgba(17, 17, 27, 0.4);
}
.audio-container .device {
	background-color: transparent;
	border: none;
	padding: 6px 8px 6px 4px;
	margin: 2px 0;
	font-size: 12px;
	border-radius: 4px;
}
.audio-container .device.selected {
	background-color: rgba(255, 255, 255, 0.085);
}
.audio-container .device:hover {
	background-color: rgba(255, 255, 255, 0.06);
}

.wallpapers-gallery-buttons {
	background-color: var(--base);
	color: var(--text);
	border: none;
	font-size: 16px;
	padding: 8px 0px;
	border-radius: 8px;
	margin: 8px 8px 8px 8px;
	width: 600px;
	font-family: "SF Pro Rounded";
}

.wallpapers-widget {
    padding: 0 6px 0 6px;
}


/***----------------------------------      • Disk •      -----------------------------------***/

.disk-widget {
    padding: 0 6px 0 6px;
}
.disk-group {
    background-color:rgba(17, 17, 27, 0.4);
}
.disk-group-row {
    min-width: 220px;
    max-width: 220px;
    max-height: 40px;
    margin: 0;
    padding: 0;
    border-radius: 6px;
    border: 1px solid rgba(128, 128, 128, 0);
}
.disk-group-row:hover {
    background-color:rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
}
.disk-group-label-bar{
    max-height:8px;
    border:0px solid rgba(128, 128, 128, 0);
    background-color: rgba(137, 180, 250, 0.1);
    border-radius: 4px;
}
.disk-group-label-bar::chunk{
    background-color: rgb(203, 166, 247);
    border-radius: 4px;
}
.disk-group-label {
    font-size: 10px;
}
.disk-group-label-size {
    font-size: 10px;
    color: rgb(203, 166, 247);
}
.disk-widget .icon {
  color: var(--mauve);
}


.cava-widget {
    padding: 0;
    margin: 0;
}
.cava-widget .widget-container {}


/* CPU MEMORY Setting */
.cpu-widget {
    padding-right: 0;
}
.memory-widget {
    padding-left: 0;
}
.cpu-widget .widget-container {
    border-bottom-right-radius: 0;
    border-top-right-radius: 0;
}
.memory-widget .widget-container {
    border-bottom-left-radius: 0;
    border-top-left-radius: 0;
}
.memory-widget .label {
    min-width: 34px;
    max-width: 34px;
}
.cpu-widget .label {
    min-width: 34px;
    max-width: 34px;
}
.cpu-widget .icon {
    color: var(--mauve);
    margin-right: 4px;
}
.memory-widget .icon {
    color: var(--mauve);
    margin-right: 4px;
}


/* WIFI Setting */
.wifi-widget .icon{
    color: var(--mauve) !important;
}


.update-check-widget {
    padding: 0 0px 0 0px;
}
.update-check-widget .icon {
    font-size: 16px;
}
.update-check-widget .widget-container.winget,
.update-check-widget .widget-container.windows {
    background: var(--mauve);
    margin: 0px 0px 0px 0px;
    border-radius: 10px;
    border: 0px solid var(--sapphire);
}
.update-check-widget .widget-container.winget .icon,
.update-check-widget .widget-container.windows .icon {
    color: var(--base);
    margin: 0 2px 0 6px;
}
.update-check-widget .widget-container.winget .label,
.update-check-widget .widget-container.windows .label {
    margin: 0 6px 0 1px;
    color: var(--base);
    font-weight: 900;
    font-size: 14px;
}



.traffic-widget .icon {
    color: rgb(203, 166, 247);
    padding-right: 6px;
    padding-left: 6px;
}
.traffic-widget .label {
color: rgb(203, 166, 247);
}


.widget {
   border-radius: 8px;
    margin: 8px 4px;
    background-color: var(--surface0);
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false

komorebi:
  start_command: "komorebic start"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start"

bars:
  status-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 800
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: true
      border_color: none
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 9
      left: 9
      bottom: 9
      right: 9
    widgets:
      left:
        [
          "home",
          "wallpaper",
          "media",
          "update_check",
          "traffic"
        ]
      center:
        [
          "glazewm_workspaces",
          "active_window",
        ]
      right:
        [
          "weather",
          "clock",
          "cava",
          "volume",
          "cpu",
          "memory",
          "wifi",
          "disk",
          "power_menu"
        ]
widgets:
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
  wallpaper:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\uf03e</span>"
      image_path: "C:\\Users\\HP\\Pictures\\Wallpapers"
      change_automatically: false # Automatically change wallpaper
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 250
        image_per_page: 4
        show_buttons: true
        orientation: "portrait"
        image_spacing: 15
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 8
        enable_cache: true
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      gradient: 1
      reverse: 0
      foreground: "#cba6f7"
      gradient_color_1: '#cba6f7'
      gradient_color_2: '#B4BEFE'
      bars_number: 8
      bar_spacing: 2
      bar_width: 5
      noise_reduction: 0.25
      sleep_timer: 2
      hide_empty: false
      container_padding:
        top: 0
        left: 4
        bottom: 0
        right: 4
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
        - { title: "Home", path: "~" }
        - { title: "Downloads", path: "C:\\Users\\HP\\Downloads"}
        - { title: "Documents", path: "C:\\Users\\HP\\Documents"}
        - { title: "Pictures", path: "C:\\Users\\HP\\Pictures"}
        - { title: "Videos", path: "C:\\Users\\HP\\Videos"}
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: ""
      distance: 10
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\udb80\udf87</span> {title}"
      label_alt: "<span>\udb80\udf87</span> {artist}"
      hide_empty: false
      max_field_size:
        label: 20
        label_alt: 20
      show_thumbnail: false
      controls_only: false
      controls_left: true
      thumbnail_alpha: 50
      thumbnail_padding: 0
      thumbnail_corner_radius: 8
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\ue769</span>{%I:%M %p}"
      label_alt: "{%a, %d %b %H:%M:%S}"
      timezones: [] #Looking up time zone info from registry
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: {conditions}, Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: '3bf4cf9a7c3f40d6b31174128242807'
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: "Dhaka"
      units: "imperial"
      callbacks:
        on_left: "toggle_card"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\ue3c2"
        cloudyDay: "\ue21d"
        cloudyNight: "\ue226"
        rainyDay: "\ue371"
        rainyNight: "\ue371"
        snowyIcyDay: "\udb81\udf17"
        snowyIcyNight: "\udb81\udf17"
        blizzard: "\udb81\udd99"
        default: "\udb81\udd99"
      weather_card:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "#45475a"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 48
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" 
        - "\uf026"
        - "\uf027" 
        - "\uf027"  
        - "\uf028"
      audio_menu:
        blur: True
        round_corners: True
        round_corners_type: 'normal'
        border_color: '#45475a'
        alignment: 'right'
        direction: 'down'
        distance: 6
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 250
      button_row: 3
      buttons:
        signout: ["\udb80\udf43","Sign out"]
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        sleep: ["\udb82\udd04","Sleep"]
        lock: ["\uf023","Lock"]
        cancel: ["\udb81\udf3a","Cancel"]
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: ""
      label_no_window: ""
      label_icon: true
      label_icon_size: 12
      max_length: 20
      max_length_ellipsis: "..."
      monitor_exclusive: true
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\uf03e</span>"
      image_path: "C:\\Users\\HP\\Pictures\\Wallpapers" # Example path to folder with images
      change_automatically: false # Automatically change wallpaper
      update_interval: 60 # If change_automatically is true, update interval in seconds
      gallery:
        enabled: true
        blur: false
        image_width: 200
        image_per_page: 8
        show_buttons: true
        orientation: "portrait"
        image_spacing: 8
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 20
        enable_cache: true
      icons:
        recording: "\ueba7"
        stopped: "\ueba5"
        paused: "\ueba7"
      hide_when_not_recording: true
      blinking_icon: true
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "<span>\uf473</span>"
        label_alt: "<span>\uf473</span>"
        group_label:
          volume_labels: ["C", "D", "E", "F"]
          show_label_name: true 
          blur: True
          round_corners: True
          round_corners_type: "normal"
          border_color: "System"
          alignment: "right"
          direction: "down"
          distance: 6
        callbacks:
          on_left: "toggle_group"
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 5
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 0
  wifi:
      type: "yasb.wifi.WifiWidget"
      options:
        label: "<span>{wifi_icon}</span>"
        label_alt: "{wifi_name} {wifi_strength}%"
        update_interval: 5000
        callbacks:
          on_left: "exec cmd.exe /c start ms-settings:network"
          on_middle: "do_nothing"
          on_right: "toggle_label"
        container_padding:
          top: 0
          left: 0
          bottom: 0
          right: 0
        wifi_icons: [
          "\udb82\udd2e",  # Icon for 0% strength
          "\udb82\udd1f",  # Icon for 1-20% strength
          "\udb82\udd22",  # Icon for 21-40% strength
          "\udb82\udd25",  # Icon for 41-80% strength
          "\udb82\udd28"   # Icon for 81-100% strength
        ]
  update_check:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      winget_update:
        enabled: true
        label: "<span>\uf0ab</span>{count}"
        interval: 180
        exclude: []
      windows_update:
        enabled: false
        label: "<span>\uf0ab</span>{count}"
        interval: 240
        exclude: []
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\udb82\udcfa</span> \uea9a{download_speed} \ueaa1{upload_speed}"
      label_alt: "<span>\udb82\udcfa</span> Download {download_speed} | Upload {upload_speed}"
      update_interval: 1000
      callbacks:
        on_left: 'toggle_label'
        on_right: 'exec cmd /c Taskmgr'
```

### Readme

```markdown
A comfy catppuccin theme for all those great desktop ricing legends. An upgraded version of the original comfyppuccin theme.  Really complements a dark-themed or catppuccin-theme based setup/rice.
```
