### ISSUE TITLE
[create-theme]: i3-Style

### ISSUE THREAD

**Issue by Louis047** [amnweb/yasb-themes#85]
### Name

i3-bar

### Description

A half-minimal i3-inspired bar for the old school lovers.

### Image

https://media-hosting.imagekit.io/4d34175e9b3d476f/screenshot_1744996269445.png?Expires=1839604272&Key-Pair-Id=K2ZIVPTIP2VGHC&Signature=uAe-SVIyCna0koM~TAaLP5qO4c~BTbey30Qqzm-XjrpxcwQT4rqmQnEMVkkPMX5ytpZSilzIWRjwTCYC5sB5y2bn0EGjGrj37pZUgM~ExF5Gu0H4UYU66hTyXgpMC~MuIqbcuUHYKBbopa85rJwfeSc0MchYNRztdPk0OUkoVVK-Upmi6GxVdASNXW7LPUa~zdr~YdxnfAnuPUKh6A2YJiBL6cbD1aP4bAZUlkc2RtkWcDLGxZTjvs7~aZ8seu-kPZsZYLntsKR1crLLj1~rjv1Bs0l0vdFTqf3I9DgRZ02bHfTp4Vf80AWG8H8fqJuk926ohAbByj2SYyKbC5ge6A__

### Theme Styles

```css
/* 
This is default and very simple styles file for Yasb. 
For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
*/
:root {
    --rosewater: #f5e0dc;
    --flamingo: #f2cdcd;
    --pink: #f5c2e7;
    --mauve: #cba6f7;
    --red: #f38ba8;
    --maroon: #eba0ac;
    --peach: #fab387;
    --yellow: #f9e2af;
    --green: #a6e3a1;
    --teal: #94e2d5;
    --sky: #89dceb;
    --sapphire: #74c7ec;
    --blue: #89b4fa;
    --lavender: #b4befe;
    --text: #cdd6f4;
    --subtext1: #bac2de;
    --subtext0: #a6adc8;
    --overlay2: #9399b2;
    --overlay1: #7f849c;
    --overlay0: #6c7086;
    --surface2: #585b70;
    --surface1: #45475a;
    --surface0: #282936;
    --base: #1e1e2e;
    --mantle: rgba(24, 24, 37, 0.5);
    --crust: rgba(17, 17, 27, 0.85);
    --main: #10151d;
}
/* Global styles for ToolTip */
QToolTip {
    padding: 6px;
    color: #ffffff;
    font-size: 12px;
    background-color: #1e1e2e;
    border: 0px solid #313244;
    border-radius: 6px;
}
* {
    font-size: 12px;
    /* color: var(--subtext0); */
    color: white;
    font-weight: 600;
    font-family: "JetBrainsMono NFP";
    margin: 0;
    padding: 0;
}
.yasb-bar {
    padding: 0;
    margin: 0;
    background-color: black;
    border-radius: 0px;
}
.widget {
    padding: 0 3px;
    margin: 0;
}
.icon {
    font-size: 15px;
}
.widget .label {
    padding: 0px 2px;
}
.komorebi-active-layout {
    padding: 0 4px 0 0;
}
/* .komorebi-active-layout .label {
    font-weight: 600;
    padding: 2px 0 0 0;
} */
.apps-widget .widget-container,
.komorebi-workspaces .widget-container,
.komorebi-active-layout .widget-container {
    background-color: var(--crust);
    margin: 3px 0 3px 0;
    border-radius: 12px;
    border: 1px solid var(--surface0);
}
.komorebi-workspaces .widget-container {
    border-top-left-radius: 6px;
    border-bottom-left-radius: 6px;
    margin-left: 4px;
}
.komorebi-workspaces {
    border-top-right-radius: 14px;
    border-bottom-right-radius: 14px;
    padding: 0 4px 0 0;
}
.komorebi-workspaces .offline-status {
    color: var(--surface2);
    font-size: 12px;
    padding: 0 0 0 4px;
    font-weight: 600;
}
.komorebi-workspaces .ws-btn {
    border: none;
    background-color: transparent;
    margin: 0;
    font-size: 12px;
    color: var(--overlay1);
    height: 28px;
    width: 18px;
}
.komorebi-workspaces .ws-btn:hover {
    color: var(--subtext1);
}
.komorebi-workspaces .ws-btn.populated {
    color: transparent;
    width: 10px;
    height: 10px;
    background-color: var(--lavender);
    border-radius: 5px;
    margin: 0 4px;
    font-size: 1px;
}
.komorebi-workspaces .ws-btn.active {
    color: transparent;
    background-color: var(--blue);
    width: 36px;
    max-width: 36px;
    height: 10px;
    margin: 0 4px;
    border-radius: 5px;
}
.apps-widget {
    padding: 0 4px 0 2px;
}
.apps-widget .label {
    font-size: 14px;
    padding: 0 2px;
    color: var(--subtext0);
}
.apps-widget .label:hover {
    color: var(--text);
}

.power-menu-widget .label {
    color: #00ece0;
    font-size: 13px;
    padding: 0px 2px 0px 0px;
}
.power-menu-popup {
    background-color: transparent;
}
.power-menu-popup .button {
    padding: 0;
    width: 180px;
    height: 230px;
    border-radius: 8px;
    /* background-color: var(--crust);
    color: var(--text); */
    background-color:black;
    color: black;
    border-left: 4px solid rgba(255, 255, 255, 0);
    border-right: 4px solid rgba(255, 255, 255, 0);
    border-top: 4px solid rgba(255, 255, 255, 0);
    border-bottom: 4px solid rgba(255, 255, 255, 0);
    margin: 0px;
}
.power-menu-popup .button.hover {
    /* background-color: var(--base); */
    background-color: white;
    color: black;
    border-left: 4px solid white;
    border-right: 4px solid white;
    border-top: 4px solid white;
    border-bottom: 4px solid white;
}

.power-menu-popup .button .label {
    margin-bottom: 8px;
    font-size: 16px;
    font-weight: 500;
    color: var(--overlay2);
}

.power-menu-popup .button .icon {
    font-size: 64px;
    padding-top: 32px;
    color: var(--surface2);
}

.power-menu-popup .button.cancel .icon {
    padding: 0;
    margin: 0;
}
.power-menu-popup .button.cancel .label {
    color: var(--red);
    margin: 0;
}
.power-menu-popup .button.cancel {
    height: 32px;
    border-radius: 4px;
}
.glazewm-workspaces {
    margin: 0;
}

.glazewm-workspaces .ws-btn {
    font-size: 15px;
    background-color: transparent;
    border: none;
    padding: 4px 8px; /* Increased padding */
    margin: 0; /* Remove margin between buttons */
    color: black;
    /* color: #CDD6F4;
    transition: all 0.2s ease;
    height: 100%; 
    display: flex;
    align-items: center;
    justify-content: center; */
}

.glazewm-workspaces .ws-btn.active,
.glazewm-workspaces .ws-btn:hover {
    background-color: #ffffff;
    border-radius: 0px; /* Optional: Add slight rounding */
}

/* Keep existing populated/empty state colors */
.glazewm-workspaces .ws-btn.populated {
    color: #ffffff;
}

.glazewm-workspaces .ws-btn.empty {
    color: #7D8B9D;
}
.glazewm-workspaces .ws-btn:hover,
.glazewm-workspaces .ws-btn.populated:hover,
.glazewm-workspaces .ws-btn.empty:hover {
    /* height: 100%;  
    width: 100%;   */
    background: grey;
    margin: 0;     
    display: flex;  
    align-items: center; 
    justify-content: center;  
}


.uptime {
    font-size: 26px;
    margin-bottom: 10px;
    /* color: var(--surface2); */
    color: white;
    font-weight: 600;
    margin-bottom: 40px;
}

.microphone-widget {
    padding: 0 6px 0 6px;
}
.microphone-widget .icon {
    font-size: 18px;
}
.microphone-widget .icon {
    color: var(--mauve);
}
.volume-widget .icon {
    color: var(--blue);
    margin: 1px 2px 0 0;
}
.weather-widget,
.volume-widget {
    padding: 0 4px;
}
.weather-widget .icon {
    font-size: 18px;
    margin: 0 2px 1px 0;
    color: var(--yellow);
}
.media-widget {
    padding: 0;
    margin: 0;
    border-radius: 0;
}
.media-widget .label {
    color: #bac2db;
    background-color: rgba(24, 24, 37, 0.7);
    padding: 0px;
    padding-right: 4px;
    font-size: 12px;
}
.media-widget .label.maintext {
    padding-top: 3px;
}
.media-widget .btn {
    color: #989caa;
    padding: 0 1px;
    margin: 0;
    font-family: Segoe Fluent Icons;
    font-weight: 400;
}
.media-widget .btn:hover {
    color: #babfd3;
}
.media-widget .btn.play {
    font-size: 16px;
}
.media-widget .btn.disabled:hover,
.media-widget .btn.disabled {
    color: #4e525c;
    font-size: 12px;
    background-color: rgba(0, 0, 0, 0);
}
.taskbar-widget {
    padding: 0;
    margin: 0;
    border: none;
}

.home-widget {
    padding: 0 0px 0 8px;
}
.home-widget .icon {
    color: var(--lavender);
}
.home-widget .icon:hover {
    color: var(--text);
}
.home-menu {
    background-color: var(--crust);
}
.home-menu .menu-item {
    padding: 8px 48px 9px 16px;
    font-size: 12px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: var(--text);
    font-weight: 600;
}
.home-menu .menu-item:hover {
    background-color: rgba(128, 130, 158, 0.15);
    color: #fff;
}
.home-menu:separator {
    height: 1px;
    background-color: rgba(128, 130, 158, 0.3);
}
.clock-widget .label {
    font-size: 14px;
    /* color: var(--pink); */
}

/*New Additions*/
.systray {
    background: transparent;
    border: None;
    margin: 0;
}

.systray .unpinned-container {
    background: transparent;
    border-radius: 0px;
}

.systray .pinned-container {
    background: transparent;
}

.systray .pinned-container[forceshow=true] {
    background: transparent;
}

.systray .button {
    border-radius: 0px;
    padding: 1px 1px;
}

.systray .button:hover {
    background: #747474;
}

.systray .button[dragging=true] {
    background: rgb(255, 255, 255);
    border-color: #fcf3ef00;
}

.systray .unpinned-visibility-btn {
    border-radius: 0px;
    height: 10px;
    width: 12px;
}

.systray .unpinned-visibility-btn:checked {
    background: transparent;
}

.systray .unpinned-visibility-btn:hover {
    color: white;
}

.wifi-widget .widget-container .icon {
    color:lightgray;
    background: transparent;
    padding: 3px 0px;
}

.battery-widget .widget-container .icon {
    padding: 0px 3px;
}

.battery-widget .widget-container .icon.status-low {
    color: red;
    background: transparent;
}

.battery-widget .widget-container .icon.status-medium {
    color: yellow;
    background: transparent;
}

.battery-widget .widget-container .icon.status-charging {
    color: rgb(128, 0, 255);
    background: transparent;
}


.wallpapers-widget {
    padding: 0 6px 0 6px;
}
.wallpapers-gallery-window {
    background-color: rgba(85, 42, 240, 0.01);
    border: 0;
    margin: 0;
}
.wallpapers-gallery-buttons {
    background-color:rgba(255, 255, 255, 0);
    color: white;
    border: none;
    font-size: 14px;
    padding: 8px 0;
    border-radius: 8px;
    margin:0 8px 8px 8px;
    width: 600px;
}
.wallpapers-gallery-buttons:hover {
    background-color:rgba(255, 255, 255, 0.1)
}
.wallpapers-gallery-image {
    border: 4px solid transparent;
    border-radius: 10px;
}
.wallpapers-gallery-image:hover {
    border: 4px solid rgb(66, 68, 83);
}
.wallpapers-gallery-image.focused {
    border: 4px solid #ffffff;
}

.clock-widget .widget-container .label {
    padding: 0px 0px 2px;
}

.calendar {
    background-color: rgba(17, 17, 27, 0.4);
}
.calendar .calendar-table,
.calendar .calendar-table::item {
    background-color: rgba(17, 17, 27, 0);
    color: rgba(162, 177, 196, 0.85);
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    margin: 0;
    padding: 0;
    border: none;
    outline: none;  
}
.calendar .calendar-table::item:selected {
    color: rgb(255, 255, 255);
}
.calendar .day-label {
    margin-top: 20px;
}
.calendar .day-label,
.calendar .month-label,
.calendar .date-label {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-size: 16px;
    color: #fff;
    font-weight: 700;
    min-width: 180px;
    max-width: 180px;
}
.calendar .month-label {
    font-weight: normal;
}
.calendar .date-label {
    font-size: 88px;
    font-weight: 900;
    color: rgb(255, 255, 255);
    margin-top: -20px;
}

.memory-widget .icon {
    color:rgb(163, 255, 76);
    padding: 0px 3px;
}

.cpu-widget .widget-container .icon {
    color:rgb(240, 224, 99);
    padding: 0px 3px;
}

.notification-widget {
    padding: 0 2px 0 2px;
}
.notification-widget .widget-container {
	background: transparent;
	margin: 3px 0 3px 0;
	border-radius: 12px;
}
.notification-widget .icon {
    font-size: 12px;
}
.notification-widget .icon.new-notification {
    color: #9089fa;
}
.notification-widget .label.new-notification {
    color: #9089fa;
}
```

### Theme Config

```yaml
# Changes made from the base config, make sure to read the docs provided in the third comment to modify according to one's liking
# This is solely meant for GlazeWM users as I haven't touched Komorebi for I love the GlazeWM's simplicity.
# For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
watch_stylesheet: true
watch_config: true
debug: false
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "System"
    window_flags:
      always_on_top: false
      windows_app_bar: false
    dimensions:
      width: "100%"
      height: 25
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
        "glazewm_workspaces"
      ]
      center: [
        "clock"
      ]
      right: [
        "systray",
        "disk",
        "memory",
        "cpu",
        "battery",
        "wifi",
        "brightness",
        "volume",
        "weather",
        "wallpapers",
        "notifications",
        "power_menu"
      ]
widgets:
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span>"
      label_alt: "{count} notifications"
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> SWAP: {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]:.0f}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\Lone\\Pictures\\Wallpapers"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 296
        image_per_page: 6
        show_buttons: false
        orientation: "portrait"
        image_spacing: 10
        lazy_load: true
        lazy_load_delay: 10
        lazy_load_fadein: 200
        image_corner_radius: 20
        enable_cache: true
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "<span>\uf473</span>"
        # label_alt: "<span>\uf473</span>"
        label_alt: "{volume_label}:{space[used][percent]}"
        volume_label: "C"
        update_interval: 60
        group_label:
          volume_labels: ["C", "D", "E", "O"]
          show_label_name: true
          blur: false
          round_corners: false
          round_corners_type: "small"
          border_color: "System"
          alignment: "right"
          direction: "down"
          offset_top: 6
          offset_left: 120
        callbacks:
          on_left: "toggle_group"
          on_right: "toggle_label"
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\udb80\udf5e"
      label_expanded: "\udb80\udf5f"
      label_position: "right" # Can be "left" or "right"
      icon_size: 15 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb81\udf17</span>"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "~\\Downloads" }
      - { title: "Documents", path: "~\\Documents" }
      - { title: "Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: false
  glazewm_workspaces:
      type: "glazewm.workspaces.GlazewmWorkspacesWidget"
      options:
        offline_label: "GlazeWM Offline"
        hide_empty_workspaces: true
        hide_if_offline: true
  media:
      type: "yasb.media.MediaWidget"
      options:
        label: "{title}"
        label_alt: "{artist}"
        max_field_size:
          label: 64
          label_alt: 24
        show_thumbnail: true
        controls_only: false
        controls_left: true
        hide_empty: true
        thumbnail_alpha: 250
        thumbnail_padding: 30
        thumbnail_corner_radius: 0
        icons:
          prev_track: "\ue892"
          next_track: "\ue893"
          play: "\ue768"
          pause: "\ue769"

  clock:
      type: "yasb.clock.ClockWidget"
      options:
        label: "{%a %d %b %H:%M}"
        label_alt: "{%A %d %B %Y %H:%M}"
        timezones: []
        calendar:
          blur: false
          round_corners: false
          offset_top: 6
          offset_left: 160

  weather:
      type: "yasb.weather.WeatherWidget"
      options:
        label: "<span>{icon}</span> {temp}"
        label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
        api_key: "3bf4cf9a7c3f40d6b31174128242807"
        update_interval: 600
        hide_decimal: true
        location: "Tuticorin"
        callbacks:
          on_left: "toggle_card"
        weather_card: 
          blur: false
          round_corners: false
          round_corners_type: "normal"
          border_color: "System"
          alignment: "right"
          direction: "down"
          icon_size: 64

  wifi:
      type: "yasb.wifi.WifiWidget"
      options:
        label: "<span>{wifi_icon}</span>"
        label_alt: "{wifi_name} {wifi_strength}%"
        update_interval: 5000
        callbacks:
          on_left: "exec cmd.exe /c start ms-settings:network"
          on_right: "toggle_label"
        wifi_icons: [
          "\udb82\udd2e",  # 0% strength icon
          "\udb82\udd1f",  # 1-20% strength
          "\udb82\udd22",  # 21-40% strength
          "\udb82\udd25",  # 41-80% strength
          "\udb82\udd28"   # 81-100% strength
        ]
  volume:
      type: "yasb.volume.VolumeWidget"
      options:
        label: "<span>{icon}</span> {level}"
        label_alt: "{volume}"
        tooltip: false

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
        label: "<span>{icon}</span>{percent}%"
        label_alt: "time: {time_remaining}"
        charging_options:
          icon_format: "{charging_icon}"
        status_thresholds:
          critical: 10 
          low: 25 
          medium: 75 
          high: 95 
          full: 100
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 100
      button_row: 4
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  
  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "Brightness {percent}%"
      tooltip: true
      auto_light: false
      auto_light_icon: "\udb80\udce1"
      auto_light_night_level: 35
      auto_light_night_start_time: "19:00"
      auto_light_night_end_time: "06:45"
      auto_light_day_level: 75
      brightness_icons: [
        "\udb80\udcde",  # Icon for 0-25% brightness
        "\udb80\udcdd",  # Icon for 26-50% brightness
        "\udb80\udcdf",  # Icon for 51-75% brightness
        "\udb80\udce0"   # Icon for 76-100% brightness
      ]
      callbacks:
          on_left: "toggle_label"
      container_padding:
        top: 2
        left: 0
        bottom: 0
        right: 0

  apps:
      type: "yasb.applications.ApplicationsWidget"
      options:
        container_padding:
          top: 0
          left: 8
          bottom: 0
          right: 8
        label: "{data}"
        app_list:
          - { icon: "\uf422", launch: "search" }
          - { icon: "\ueb03", launch: "cmd /c Taskmgr" }
          - { icon: "\udb80\ude39", launch: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" }
```

### Readme

```markdown
Inspiration from i3-bar, made with love. Meant for GlazeWM users (Sorry Komorebi people).
```
