### ISSUE TITLE
[create-theme]: Fluent Overhaul

### ISSUE THREAD

**Issue by Louis047** [amnweb/yasb-themes#87]
### Name

Fluency

### Description

A fluent status bar, but better with added goodies. Compatible with komorebi with controls.

### Image

https://imgur.com/a/9aJ8GEm

### Theme Styles

```css
/* 
Base Configuration, modified from i3-style with a new look. I missed transparency :)
For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
*/
:root {
    --red: #ff4d4d;
    --maroon: #eba0ac;
    --peach: #fab387;
    --yellow: #f9e2af;
    --green: #a6e3a1;
    --teal: #94e2d5;
    --sky: #89dceb;
    --sapphire: #74c7ec;
    --blue: #89b4fa;
    --text: #c3c3c3;
}
/* Global styles for ToolTip */
QToolTip {
    padding: 6px;
    color: #ffffff;
    font-size: 12px;
    background-color: #3939397d;
    border: 0px solid #9f9f9f;
    border-radius: 6px;
}

/*                                 COMMON YASB ELEMENTS                          */
* {
    font-size: 14px;
    color: var(--text);
    font-weight: 600;
    font-family: "JetBrainsMono NFP";
    margin: 0;
    padding: 0;
}
.yasb-bar {
    padding: 0;
    margin: 0;
    background-color: rgba(0, 0, 0, 0.45);
    border-radius: 0px;
}
.widget {
    padding: 0 3px;
    margin: 0;
}
.icon {
    font-size: 15px;
}
.widget .label {
    padding: 0px 2px;
}

/*                                      WIDGETS                                     */
/*              Power Menu                     */
.power-menu-widget .label {
    color: #ff1100;
    font-size: 15px;
    padding: 0px 10px 0px 3px;
}
.power-menu-popup {
    background-color: transparent;
}
.power-menu-popup .button {
    padding: 0;
    width: 180px;
    height: 230px;
    border-radius: 8px;
    background-color:rgba(61, 61, 61, 0.4);
    color: black;
    border-left: 2px solid rgb(61, 61, 61);
    border-right:2px solid rgb(61, 61, 61);
    border-top: 2px solid rgb(61, 61, 61);
    border-bottom: 2px solid rgb(61, 61, 61);
    margin: 0px;
}
.power-menu-popup .button.hover {
    background-color: rgba(97, 97, 97, 0.5);
    color: black;
    border-left: 2px solid rgba(130, 130, 130, 0.65);
    border-right: 2px solid rgba(130, 130, 130, 0.65);
    border-top: 2px solid rgba(130, 130, 130, 0.65);
    border-bottom: 2px solid rgba(130, 130, 130, 0.65);
}
.power-menu-popup .button .label {
    margin-bottom: 8px;
    font-size: 16px;
    font-weight: 500;
    color:rgba(197, 197, 197, 0.85);
}
.power-menu-popup .button .icon {
    font-size: 64px;
    padding-top: 32px;
    color:rgba(116, 116, 116, 0.85);
}
.power-menu-popup .button.cancel .icon {
    padding: 0;
    margin: 0;
}
.power-menu-popup .button.cancel .label {
    color: var(--red);
    margin: 0;
}
.power-menu-popup .button.cancel {
    height: 32px;
    border-radius: 4px;
}
.uptime {
    font-size: 26px;
    margin-bottom: 10px;
    color: white;
    font-weight: 600;
    margin-bottom: 40px;
}

/*              GlazeWM                      */
.glazewm-workspaces {
    margin: 0;
    padding: 0;
}
.glazewm-workspaces .ws-btn {
    font-size: 15px;
    background-color: transparent;
    border: none;
    padding: 4px 8px; /* Increased padding */
    margin: 0; /* Remove margin between buttons */
    color: black;
}
.glazewm-workspaces .ws-btn.active,
.glazewm-workspaces .ws-btn:hover {
    background-color: #ffffff;
    border-radius: 0px; /* Optional: Add slight rounding */
}
/* Keep existing populated/empty state colors */
.glazewm-workspaces .ws-btn.populated {
    color: #ffffff;
}
.glazewm-workspaces .ws-btn.empty {
    color: #7D8B9D;
}
.glazewm-workspaces .ws-btn:hover,
.glazewm-workspaces .ws-btn.populated:hover,
.glazewm-workspaces .ws-btn.empty:hover {
    background: grey;
    margin: 0;     
    display: flex;  
    align-items: center; 
    justify-content: center;  
}

/*                           Komorebi                        */
/*                         Control Part                      */
.komorebi-control-widget .label {
    font-size: 14px;
    color: #cdd6f4;
    font-weight: 600;
}
.komorebi-control-menu {
    background-color: rgba(17, 17, 27, 0.2);
}
.komorebi-control-menu .button {
    color: rgba(102, 102, 102, 0.4);
    padding: 8px 16px;
    font-size: 32px;
    border-radius: 8px;
    background-color: rgba(255, 255, 255, 0.04);
}
.komorebi-control-menu .button:hover {
    color: rgba(255, 255, 255, 0.4);
    background-color: rgba(100, 100, 100, 0.04);
}
.komorebi-control-menu .button.active:hover {
    color: rgba(255, 255, 255, 0.4);
    background-color: rgba(100, 100, 100, 0.04);
}
.komorebi-control-menu .button.active {
    color: rgb(228, 228, 228);
    background-color: rgba(255, 255, 255, 0.04);
}
.komorebi-control-menu .button:disabled,
.komorebi-control-menu .button.active:disabled {
    background-color: rgba(255, 255, 255, 0.01);
    color: rgba(255, 255, 255, 0.2);
}
.komorebi-control-menu .footer .text {
    font-size: 12px;
    color: #6c7086;
}

.volume-widget .icon {
    color: var(--blue);
    margin: 1px 2px 0 0;
}

/*                      Workspace Part                       */
.komorebi-workspaces .widget-container{
    background-color: rgba(0, 0, 0, 0.4);
    border-radius: 0px;
    margin: 0px 4px;
}
.komorebi-workspaces{
    margin: 0;
    padding: 0;
}
.komorebi-workspaces .offline-status{
    font-size: 14px;
    padding: 0 2px;
    font-weight: 600;
}
.komorebi-workspaces .ws-btn{
    color: rgba(128, 128, 128, 0.5);
    width: 10px;
    height: 10px;
    padding: 0 4px 0 4px;
    border-radius: 5px;
    margin: 0 2px;
    font-size: 14px;
}
.komorebi-workspaces .ws-btn:hover{
    color: var(--text);
}
.komorebi-workspaces .ws-btn.populated{
    width: 10px;
    height: 10px;
    border-radius: 5px;
    margin: 0 2px;
    font-size: 14px;
}
.komorebi-workspaces .ws-btn.active{
    color: white;
    width: 10px;
    height: 10px;
    border-radius: 5px;
}

.weather-widget,
.volume-widget {
    padding: 0 4px;
}
.weather-widget .icon {
    font-size: 18px;
    margin: 0 2px 1px 0;
    color: var(--yellow);
}

/*                          Media                              */
.media-widget {
    padding: 0;
    margin: 0;
    border-radius: 0;
}
.media-widget .label {
    color: #d4eced;
    background-color: rgba(0, 0, 0, 0.236);
    padding: 0px;
    padding-right: 4px;
    font-size: 12px;
}
.media-widget .label.maintext {
    padding-top: 3px;
}
.media-widget .btn {
    color: #989caa;
    padding: 0 4px;
    margin: 0;
    font-family: Segoe Fluent Icons;
    font-weight: 400;
}
.media-widget .btn:hover {
    color: #babfd3;
}
.media-widget .btn.play {
    font-size: 16px;
}
.media-widget .btn.disabled:hover,
.media-widget .btn.disabled {
    color: #939496;
    font-size: 12px;
    background-color: rgba(0, 0, 0, 0);
}

/*                                  System Tray                         */
.systray {
    background: transparent;
    border: None;
    margin: 0;
}
.systray .unpinned-container {
    background: transparent;
    border-radius: 8px;
}
.systray .pinned-container {
    background: transparent;
}
.systray .pinned-container[forceshow=true] {
    background: red;
}
.systray .button {
    border-radius: 10px;
    padding: 3px 3px;
}
.systray .button:hover {
    background: #727272;
}
.systray .button[dragging=true] {
    background: orange;
    border-color: #FF8800;
}
.systray .unpinned-visibility-btn {
    border-radius: 4px;
    height: 20px;
    width: 16px;
}
.systray .unpinned-visibility-btn:checked {
    background: transparent;
}
.systray .unpinned-visibility-btn:hover {
    border: 1px solid #AAAAAA;
    border-radius: 4px;
    border-color: #AAAAAA;
}

/*                          Wi-Fi                           */
.wifi-widget .widget-container .icon {
    color:lightgray;
    background: transparent;
    padding: 3px 0px;
}

/*                          Battery                           */
.battery-widget .widget-container .icon {
    padding: 0px 3px;
}
.battery-widget .widget-container .icon.status-low {
    color: red;
    background: transparent;
}
.battery-widget .widget-container .icon.status-medium {
    color: yellow;
    background: transparent;
}
.battery-widget .widget-container .icon.status-charging {
    color: rgb(128, 0, 255);
    background: transparent;
}

/*                          Wallpaper                          */
.wallpapers-widget {
    padding: 0 6px 0 6px;
    color: rgb(128, 0, 255);
}
.wallpapers-gallery-window {
    background-color: rgba(85, 42, 240, 0.01);
    border: 0;
    margin: 0;
}
.wallpapers-gallery-buttons {
    background-color:rgba(255, 255, 255, 0);
    color: rgb(255, 255, 255);
    border: none;
    font-size: 14px;
    padding: 8px 0;
    border-radius: 8px;
    margin:0 8px 8px 8px;
    width: 600px;
}
.wallpapers-gallery-buttons:hover {
    background-color:rgba(255, 255, 255, 0.1)
}
.wallpapers-gallery-image {
    border: 4px solid transparent;
    border-radius: 10px;
}
.wallpapers-gallery-image:hover {
    border: 4px solid rgb(80, 80, 80);
}
.wallpapers-gallery-image.focused {
    border: 4px solid #ffffff;
}

/*                          Clock & Calendar                            */
.clock-widget .label {
    font-size: 16px;
    font-weight: 900;
    background-color: rgba(197, 197, 197, 0.5);
    margin: 0;
    padding: 0;
    color:rgba(22, 22, 22, 0.6);
}
.clock-widget .icon {
    font-size: 25px;
    margin: 0 -1px;
    padding: 0;
    font-weight: 600;
    color:rgba(197, 197, 197, 0.5);
}
.clock-widget {
    border-top-left-radius: 24px;
    border-bottom-right-radius: 24px;
    padding: 0 20px;
}
.clock-widget .widget-container .label {
    padding: 0px 0px 2px;
}
.calendar {
    background-color: rgba(21, 21, 21, 0.4);
}
.calendar .calendar-table,
.calendar .calendar-table::item {
    background-color: rgba(33, 33, 33, 0.736);
    color: rgba(197, 197, 197, 0.85);
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    margin: 0;
    padding: 0;
    border: none;
    outline: none;  
}
.calendar .calendar-table::item:selected {
    color: rgb(255, 255, 255);
}
.calendar .day-label {
    margin-top: 20px;
}
.calendar .day-label,
.calendar .month-label,
.calendar .date-label {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-size: 16px;
    color: #fff;
    font-weight: 700;
    min-width: 180px;
    max-width: 180px;
}
.calendar .month-label {
    font-weight: normal;
}
.calendar .date-label {
    font-size: 88px;
    font-weight: 900;
    color: rgb(255, 255, 255);
    margin-top: -20px;
}

/*                             Memory                           */
.memory-widget .icon {
    color:rgb(163, 255, 76);
    padding: 0px 3px;
}

/*                              CPU                             */
.cpu-widget .widget-container .icon {
    color:rgb(240, 224, 99);
    padding: 0px 3px;
}

/*                          Notifications                        */
.notification-widget {
    padding: 0 3px 0 3px;
}
.notification-widget .widget-container {
	background: transparent;
	margin: 3px 0 3px 0;
	border-radius: 12px;
}
.notification-widget .icon {
    font-size: 14px;
}
.notification-widget .icon.new-notification {
    color: #9089fa;
}
.notification-widget .label.new-notification {
    color: #9089fa;
}

/*                              Disk                                */
.disk-widget {
    padding: 0 6px 0 6px;
}
.disk-group {
    background-color:rgba(17, 17, 27, 0.15); 
    border: 1px solid rgb(94, 94, 94);
}

/*                              Home                                */
.home-widget {
    padding: 0 6px 0 12px;
}
.home-widget .icon {
    color: #b4befe;
    font-size: 18px;
}
.home-widget .icon:hover {
    color: #cdd6f4;
}
.home-menu {
    background-color:rgba(0, 0, 0, 0.5); 
}
.home-menu .menu-item {
    padding: 6px 48px 7px 16px;
    font-size: 12px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: rgb(208, 208, 208);
    font-weight: 600;
}
.home-menu .menu-item:hover {
    background-color:rgba(0, 0, 0, 0.15);
    color: #fff;
}
.home-menu .separator {
    max-height: 1px;
    background-color:rgba(192, 192, 192, 0.3);
}

/*                          Notes                       */
.notes-widget {
    padding: 0 6px 0 8px;
}
.notes-widget .label {
   font-size: 14px;
   color: #dbfeb4;;
}
.notes-widget .icon {
    font-size: 16px;
    color: #dbfeb4;
}
.notes-menu {
    min-width: 400px;
    max-width: 400px;
    background-color: rgba(0, 0, 0, 0.4);
}
.notes-menu .note-item {
    background-color:transparent;
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}
.notes-menu .note-item:hover {
    background-color: rgba(255, 255, 255, 0.1);
}
.notes-menu .note-item .icon {
    font-size: 16px;
    padding: 0 4px;
}
.notes-menu .delete-button {
    color: #ff6b6b;
    background: transparent;
    border: none;
    font-size: 8px;
    padding: 7px 8px;
    border-radius: 3px;
}
.notes-menu .delete-button:hover {
    background-color: rgba(128, 128, 128, 0.5);
}
.notes-menu .note-item .title {
    font-size: 13px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}
.notes-menu .note-item .date {
    font-size: 12px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: rgba(255, 255, 255, 0.4);
}
.notes-menu .empty-list {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: rgba(255, 255, 255, 0.2);
    font-size: 24px;
    font-weight: 600;
    padding: 10px 0 20px 0;     
}
.notes-menu .add-button,  
.notes-menu .cancel-button {
    padding: 8px;
    background-color: rgba(255, 255, 255, 0.1);
    border: none;
    border-radius: 4px;
    color: white;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}
.notes-menu .cancel-button {
    margin-left: 4px;
}
.notes-menu .add-button:hover,
.notes-menu .cancel-button:hover {
    background-color: rgba(255, 255, 255, 0.2);
}
.notes-menu .scroll-area {
    background: transparent; 
    border: none; 
    border-radius:0;
}
.notes-menu .note-input {
    background-color:rgba(17, 17, 27, 0.2);
    border: 1px solid rgba(255, 255, 255, 0.1);
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-size: 14px;
    max-height: 30px;
    padding: 4px;
    border-radius: 6px;
}
.note-input:focus {
    border: 1px solid #717171;
}
```

### Theme Config

```yaml
# Changes made from the base config, make sure to read the docs provided in the third comment to modify according to one's liking
# UPDATE: Done modifying with Komorebi!
# For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
watch_stylesheet: true
watch_config: true
debug: false
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: True
      acrylic: True
      dark_mode: True
      round_corners: True
      round_corners_type: "normal"
      border_color: "System"
    window_flags:
      always_on_top: false
      windows_app_bar: true # This interferes with apps in full-screen. Notably while watching videos in full screen
    dimensions:
      width: "100%"
      height: 30
    padding:
      top: 10
      left: 12
      bottom: 0
      right: 12
    widgets:
      left: [
        "home",
        "komorebi_control",
        "komorebi_workspaces",
        "notes",
        "media"
      ]
      center: [
        "clock"
      ]
      right: [
        "systray",
        "disk",
        "memory",
        "cpu",
        "battery",
        "wifi",
        "volume",
        "weather",
        "wallpapers",
        "notifications",
        "power_menu"
      ]
widgets:
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: ""
      label_workspace_active_btn: ""
      label_workspace_populated_btn: ""
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: true
      hide_if_offline: false
      animation: true
      container_padding: 
        top: 0
        left: 12
        bottom: 0
        right: 12
      btn_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [ 1, 1 ]
  komorebi_control:
    type: "komorebi.control.KomorebiControlWidget"
    options:
      label: "<span>\udb84\udc47</span>"
      icons:
        start: "\uead3"
        stop: "\uead7"
        reload: "\uead2"
      run_ahk: false
      run_whkd: true
      show_version: false
      komorebi_menu:
        blur: True
        round_corners: True
        round_corners_type: 'normal'
        border_color: 'System'
        alignment: 'left'
        direction: 'down'
        offset_top: 6
        offset_left: -32
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  notes:
    type: "yasb.notes.NotesWidget"
    options:
      label: "<span>\udb82\udd0c</span> {count}"
      label_alt: "{count} notes"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 220
        max_title_size: 150
        show_date_time: true
      icons:
        note: "\udb82\udd0c"
        delete: "\ue20d"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [ 1, 1 ]
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\ue62a</span>"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "D:\\Downloads" }
      - { title: "Documents", path: "C:\\Users\\amn\\Documents" }
      - { title: "Pictures", path: "C:\\Users\\amn\\Pictures" }
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "System"
      offset_top: 6
      offset_left: 0
      container_padding: 
        top: 0
        left: 0
        bottom: 0
        right: 0
      alignment: "left"
      direction: "down"
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [ 1, 1 ]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span>"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: true
      callbacks:
        on_left: "toggle_notification"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [ 1, 1 ]
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> SWAP: {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [ 1, 1 ]
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]:.0f}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [ 1, 1 ]      
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\Lone\\Pictures\\Wallpapers"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 296
        image_per_page: 6
        show_buttons: false
        orientation: "portrait"
        image_spacing: 10
        lazy_load: true
        lazy_load_delay: 10
        lazy_load_fadein: 200
        image_corner_radius: 20
        enable_cache: true
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "<span>\uf473</span>"
        # label_alt: "<span>\uf473</span>"
        label_alt: "{volume_label}:{space[used][percent]}"
        volume_label: "C"
        update_interval: 60
        group_label:
          volume_labels: ["C", "D", "E", "O"]
          show_label_name: true
          blur: True
          round_corners: true
          round_corners_type: "normal"
          border_color: "System"
          alignment: "right"
          direction: "down"
          offset_top: 6
          offset_left: 120
        callbacks:
          on_left: "toggle_group"
          on_right: "toggle_label"
        label_shadow:
          enabled: true
          color: "black"
          radius: 6
          offset: [ 1, 1 ] 
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\udb80\udf5e"
      label_expanded: "\udb80\udf5f"
      label_position: "right" # Can be "left" or "right"
      icon_size: 15 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
  glazewm_workspaces:
      type: "glazewm.workspaces.GlazewmWorkspacesWidget"
      options:
        offline_label: "GlazeWM Offline"
        hide_empty_workspaces: true
        hide_if_offline: true
  media:
      type: "yasb.media.MediaWidget"
      options:
        label: "{title}"
        label_alt: "{title} - {artist}"
        max_field_size:
          label: 24
          label_alt: 24
        show_thumbnail: true
        controls_only: false
        controls_left: true
        hide_empty: true
        thumbnail_alpha: 255
        thumbnail_padding: 30
        thumbnail_corner_radius: 0
        icons:
          prev_track: "\ue892"
          next_track: "\ue893"
          play: "\ue768"
          pause: "\ue769"
        label_shadow:
          enabled: true
          color: "black"
          radius: 6
          offset: [ 1, 1 ]
        container_shadow:
          enabled: true
          color: "black"
          radius: 6
          offset: [ 1, 1 ]
  clock:
      type: "yasb.clock.ClockWidget"
      options:
        label: "<span>\ue0b2</span> {%H:%M} <span>\ue0b0</span>"
        label_alt: "<span>\ue0c2</span>{%A %d %B %Y %H:%M}<span>\ue0c0</span>"
        timezones: []
        calendar:
          blur: True
          round_corners: true
          offset_top: 10
          offset_left: 200
  weather:
      type: "yasb.weather.WeatherWidget"
      options:
        label: "<span>{icon}</span> {temp}"
        label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
        api_key: "3bf4cf9a7c3f40d6b31174128242807"
        update_interval: 600
        hide_decimal: true
        location: "Tuticorin"
        callbacks:
          on_left: "toggle_card"
        weather_card: 
          blur: true
          round_corners: true
          round_corners_type: "normal"
          border_color: "System"
          alignment: "right"
          direction: "down"
          icon_size: 64
          offset_top: 6
          offset_left: 74
        label_shadow:
          enabled: true
          color: "black"
          radius: 6
          offset: [ 1, 1 ]
  wifi:
      type: "yasb.wifi.WifiWidget"
      options:
        label: "<span>{wifi_icon}</span>"
        label_alt: "{wifi_name} {wifi_strength}%"
        update_interval: 5000
        callbacks:
          on_left: "exec cmd.exe /c start ms-settings:network"
          on_right: "toggle_label"
        wifi_icons: [
          "\udb82\udd2e",  # 0% strength icon
          "\udb82\udd1f",  # 1-20% strength
          "\udb82\udd22",  # 21-40% strength
          "\udb82\udd25",  # 41-80% strength
          "\udb82\udd28"   # 81-100% strength
        ]
        label_shadow:
          enabled: true
          color: "black"
          radius: 6
          offset: [ 1, 1 ]
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      audio_menu:
        blur: True
        round_corners: True
        round_corners_type: 'normal'
        border_color: 'System'
        alignment: 'right'
        direction: 'down'
        offset_top: 6
        offset_left: 80
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [ 1, 1 ]
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
        label: "<span>{icon}</span>{percent}%"
        label_alt: "time: {time_remaining}"
        charging_options:
          icon_format: "{charging_icon}"
        status_thresholds:
          critical: 10 
          low: 25 
          medium: 75 
          high: 95 
          full: 100
        label_shadow:
          enabled: true
          color: "black"
          radius: 6
          offset: [ 1, 1 ]
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 100
      button_row: 4
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [ 1, 1 ]
```

### Readme

```markdown
A status bar that has it all: the base goodies. 

>[!NOTE]
For wallpapers, you have to change the directory provided in `config.yaml`
```
