### ISSUE TITLE
[create-theme]: Yasb 006

### ISSUE THREAD

**Issue by szbmrk** [amnweb/yasb-themes#91]
### Name

tokyonight

### Description

A theme inspired by the Yasb 004 theme.

### Image

https://i.imgur.com/NnE8Ha3.png

### Theme Styles

```css
/* ===================== */
/* === COLOR VARIABLES === */
/* ===================== */
:root {
    /* Catppuccin Mocha color palette */
    --rosewater: #f5e0dc;
    --flamingo: #f2cdcd;
    --pink: #f5c2e7;
    --mauve: #cba6f7;
    --red: #f38ba8;
    --maroon: #eba0ac;
    --peach: #fab387;
    --yellow: #f9e2af;
    --green: #a6e3a1;
    --teal: #94e2d5;
    --sky: #89dceb;
    --sapphire: #74c7ec;
    --blue: #89b4fa;
    --lavender: #b4befe;

    /* Text colors */
    --text: #cdd6f4;
    --subtext1: #bac2de;
    --subtext0: #a6adc8;

    /* Overlay colors */
    --overlay2: #9399b2;
    --overlay1: #7f849c;
    --overlay0: #6c7086;

    /* Surface colors */
    --surface2: #585b70;
    --surface1: #45475a;
    --surface0: #282936;

    /* Base colors */
    --base: #1e1e2e;
    --mantle: rgba(24, 24, 37, 0.5);
    --crust: rgba(17, 17, 27, 0.75);
}

/* ================= */
/* === BASE STYLES === */
/* ================= */
* {
    font-size: 12px;
    color: var(--subtext0);
    font-weight: 700;
    font-family: "JetBrainsMono NFP";
    margin: 0;
    padding: 0;
}

/* ================= */
/* === BAR LAYOUT === */
/* ================= */
.yasb-bar {
    padding: 0;
    margin: 0;
    background-color: var(--crust);
}

/* Common widget styles */
.widget {
    padding: 0 8px;
    margin: 0 2px;
}

.widget .label {
    padding: 0px 2px;
}

.widget .label.alt {
    padding: 0px 2px;
}

.icon {
    font-size: 16px;
    margin: 0 4px 0 0;
}

/* ==================== */
/* === POWER MENU === */
/* ==================== */
.power-menu-widget .label {
    color: var(--red);
    font-size: 13px;
}

.power-menu-popup {
    background-color: transparent;
}

.power-menu-popup .button {
    padding: 0;
    width: 180px;
    height: 230px;
    border-radius: 8px;
    background-color: var(--base);
    border: 8px solid rgba(58, 59, 83, 0);
    margin: 0px;
}

.power-menu-popup .button.hover {
    background-color: var(--surface0);
    border: 8px solid var(--surface0);
}

.power-menu-popup .button .label {
    margin-bottom: 8px;
    font-size: 16px;
    font-weight: 500;
    color: var(--lavender);
}

.power-menu-popup .button .icon {
    font-size: 64px;
    padding-top: 32px;
    color: var(--lavender);
}

/* Cancel button specific styles */
.power-menu-popup .button.cancel {
    height: 32px;
    border-radius: 4px;
}

.power-menu-popup .button.cancel .icon {
    padding: 0;
    margin: 0;
}

.power-menu-popup .button.cancel .label {
    color: var(--red);
    margin: 0;
}

/* ==================== */
/* === VOLUME WIDGET === */
/* ==================== */
.volume-widget .icon {
    color: var(--blue);
    margin: 1px 2px 0 0;
}

/* Audio dropdown menu */
.audio-menu {
    background-color: var(--mantle);
}

.audio-container .device {
    font-size: 20px;
    background-color: transparent;
    border: none;
    padding: 6px 8px 6px 4px;
    margin: 2px 0;
    font-size: 12px;
    border-radius: 4px;
}

.audio-container .device.selected {
    background-color: rgba(255, 255, 255, 0.085);
}

.audio-container .device:hover {
    background-color: rgba(255, 255, 255, 0.06);
}

/* ================= */
/* === DISK WIDGET === */
/* ================= */
.disk-widget .icon {
    color: var(--teal);
}

/* Disk dropdown */
.disk-group {
    background-color: var(--mantle);
}

.disk-group-row {
    min-width: 220px;
    max-width: 220px;
    max-height: 40px;
    margin: 0;
    padding: 0;
    border-radius: 6px;
    border: 1px solid transparent;
}

.disk-group-row:hover {
    background-color: rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
}

.disk-group-label-bar {
    max-height: 8px;
    border: 0;
    background-color: rgba(148, 226, 213, 0.3);
    border-radius: 4px;
}

.disk-group-label-bar::chunk {
    background-color: var(--teal);
    border-radius: 4px;
}

.disk-group-label {
    font-size: 13px;
}

.disk-group-label-size {
    font-size: 12px;
    color: rgba(205, 214, 244, 0.5);
}

/* ================= */
/* === CLOCK WIDGET === */
/* ================= */
.clock-widget {
    background-color: var(--crust);
    margin: 4px 0;
    border-radius: 12px;
    border: 0;
}

.clock-widget .icon {
    font-size: 14px;
    color: var(--sky)
}

.clock-widget .label {
    font-size: 14px;
    font-weight: 700;
    color: var(--subtext0);
}

/* Calendar dropdown */
.calendar {
    background-color: var(--mantle);
}

.calendar .calendar-table,
.calendar .calendar-table::item {
    background-color: transparent;
    color: rgba(162, 177, 196, 0.85);
    margin: 0;
    padding: 0;
    border: none;
    outline: none;
}

.calendar .calendar-table::item:selected {
    color: var(--crust);
    background-color: var(--lavender);
    border-radius: 5px;
}

.calendar .day-label {
    margin-top: 20px;
}

.calendar .day-label,
.calendar .month-label,
.calendar .date-label {
    font-size: 16px;
    color: var(--lavender);
    font-weight: 700;
    min-width: 180px;
    max-width: 180px;
}

.calendar .month-label {
    font-weight: normal;
}

.calendar .date-label {
    font-size: 88px;
    font-weight: 900;
    color: rgb(255, 255, 255);
    margin-top: -20px;
}

/* ==================== */
/* === WEATHER WIDGET === */
/* ==================== */
.weather-widget .icon {
    font-size: 20px;
    margin: 0 2px 1px 0;
    color: var(--maroon);
}

.weather-card {
    background-color: var(--mantle);
}

/* ====================== */
/* === WORKSPACE WIDGET === */
/* ====================== */
.glazewm-workspaces {
    background-color: var(--crust);
    margin: 4px 0;
    border-radius: 12px;
    border: 0;
}

.glazewm-workspaces .ws-btn {
    font-size: 14px;
    border: none;
    color: var(--overlay0);
    padding: 0 6px;
    cursor: pointer;
}

.glazewm-workspaces .ws-btn.active {
    color: var(--red);
    font-weight: 900;
}


/* ================= */
/* === WIFI WIDGET === */
/* ================= */
.wifi-widget .icon {
    color: var(--yellow);
}

/* ===================== */
/* === BATTERY WIDGET === */
/* ===================== */
.battery-widget .icon {
    color: var(--flamingo);
}

/* ==================== */
/* === MEMORY WIDGET === */
/* ==================== */
.memory-widget .icon {
    color: var(--mauve);
}

/* ================= */
/* === UPTIME WIDGET === */
/* ================= */
.uptime {
    font-size: 14px;
    margin-bottom: 10px;
    color: var(--surface2);
    font-weight: 600;
}

/* ================= */
/* === HOME WIDGET === */
/* ================= */
.home-widget {
    padding: 0 4px 0 12px;
}

.home-widget .icon {
    font-size: 18px;
    color: var(--subtext1);
}

.home-menu {
    background-color: var(--mantle);
    padding: 0;
    margin-left: 2px;
}

.home-menu .menu-item {
    padding: 8px 48px 8px 12px;
    font-weight: 600;
    color: var(--text);
}

.home-menu .menu-item:hover {
    background-color: var(--lavender);
    color: var(--surface0);
    margin: 4px 6px;
    border-radius: 4px;
}

.home-menu .separator {
    max-height: 1px;
    background-color: var(--overlay0);
    margin: 0 8px;
}
```

### Theme Config

```yaml
watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    blur_effect:
      enabled: true 
      acrylic: true 
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
          "home", 
          "glazewm_workspaces", 
          "active_window",
      ]
      center: [
          "clock",
        ]
      right: [
          "memory",
          "disk",
          "weather",
          "wifi",
          "volume",
          "battery",
          "power_menu"
      ]
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
        - { title: "Home", path: "~" }
        - { title: "Downloads", path: "~\\Downloads"}
        - { title: "Documents", path: "~\\Documents"}
        - { title: "Pictures", path: "~\\Pictures"}
        - { title: "Videos", path: "~\\Videos"}
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "normal"
      round_corners_type: "small"
      border_color: "#7aa2f7"
      alignment: "left"
      offset_left: 4
      offset_top: 0
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uf4bc</span> {virtual_mem_outof}"
      label_alt: "<span>\uf4bc</span> {virtual_mem_outof}"
      update_interval: 10000
      callbacks:
        on_right: "exec cmd /c Taskmgr"
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "<span>\uf473</span> disks"
        label_alt: "<span>\uf473</span>"
        group_label:
          volume_labels: ["C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
          show_label_name: false 
          blur: true
          round_corners: true
          round_corners_type: "small"
          border_color: '#7aa2f7'
          alignment: 'center'
          offset_top: 0
        callbacks:
          on_left: "toggle_group"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 32
      max_length_ellipsis: "..."
      monitor_exclusive: true
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span>{%H:%M}"
      label_alt: "<span>\uf017</span>{%A, %B %d. %Y %H:%M}"
      locale: "hu_HU"
      timezones: []
      calendar:
        round_corners: true
        round_corners_type: "small"
        border_color: "#7aa2f7"
        alignment: "center"
        offset_top: 0
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: {conditions}, Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: '24b6c2cda6d84066b0304531241908'
      update_interval: 600
      hide_decimal: true
      location: "Hungary, Eger"
      units: "metric"
      callbacks:
        on_left: "toggle_card"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\ue3c2"
        cloudyDay: "\ue21d"
        cloudyNight: "\ue226"
        rainyDay: "\ue371"
        rainyNight: "\ue371"
        snowyIcyDay: "\udb81\udf17"
        snowyIcyNight: "\udb81\udf17"
        blizzard: "\udb81\udd99"
        default: "\udb81\udd99"
      weather_card:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "#7aa2f7"
        alignment: "center"
        direction: "down"
        offset_top: 0
        icon_size: 48
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span> {wifi_strength}%"
      label_alt: "<span>{wifi_icon}</span> {wifi_name} {wifi_strength}%"
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span> {wifi_name}"
      ethernet_icon: "\uf108"
      update_interval: 5000
      callbacks:
        on_left: "exec quick_settings"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      wifi_icons: [
        "\udb82\udd2e",  # Icon for 0% strength
        "\udb82\udd1f",  # Icon for 1-20% strength
        "\udb82\udd22",  # Icon for 21-40% strength
        "\udb82\udd25",  # Icon for 41-80% strength
        "\udb82\udd28"   # Icon for 81-100% strength
      ]
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "#7aa2f7"
        alignment: "center"
        direction: "down"
        offset_top: 0
      callbacks:
        on_right: "toggle_mute"
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>{percent}%"
      label_alt: "<span>{icon}</span> {percent}% | time: {time_remaining}"
      #hide_unsupported: true
      charging_options:
        icon_format: "{charging_icon}" 
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
```

### Readme

```markdown
A theme inspired by the Yasb 004 theme, but made it a bit more minimalistic.
```
